print 'Excel Insert MapNodeInstitutions'
GO

INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (1, 1, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (1, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (1, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (2, 4, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (2, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (2, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (3, 5, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (3, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (3, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (4, 6, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (4, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (4, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (5, 7, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (5, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (5, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (6, 8, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (6, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (6, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (7, 9, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (7, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (7, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (8, 10, 1, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (8, 2, 3, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
INSERT INTO [MapNodeInstitutions] ([MapNodeId], [InstitutionId], [InstitutionTypeId], [ContactName], [ContactPosition], [ContactPhone], [ContactFax], [ContactEmail]) VALUES (8, 3, 2, N'Име на контакт', N'Длъжност', N'Телефонен номер', N'Факс', N'e-mail')
GO

