//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_09998
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-09998";
	}




	[XmlType(TypeName="DirectionsBudgetContract",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class DirectionsBudgetContract
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="id",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="isLocked",DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __isLocked;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __isLockedSpecified;
		
		[XmlIgnore]
		public bool isLocked
		{ 
			get { return __isLocked; }
			set { __isLocked = value; __isLockedSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="programmeCode",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __programmeCode;
		
		[XmlIgnore]
		public string programmeCode
		{ 
			get { return __programmeCode; }
			set { __programmeCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="programmeName",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __programmeName;
		
		[XmlIgnore]
		public string programmeName
		{ 
			get { return __programmeName; }
			set { __programmeName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10093.DirectionSection),ElementName="Directions",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10093.DirectionSection __Directions;
		
		[XmlIgnore]
		public R_10093.DirectionSection Directions
		{
			get {return __Directions;}
			set {__Directions = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10010.Budget),ElementName="Budget",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10010.Budget __Budget;
		
		[XmlIgnore]
		public R_10010.Budget Budget
		{
			get {return __Budget;}
			set {__Budget = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10006.Contract),ElementName="Contract",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10006.Contract __Contract;
		
		[XmlIgnore]
		public R_10006.Contract Contract
		{
			get {return __Contract;}
			set {__Contract = value;}
		}

		public DirectionsBudgetContract()
		{
		}
	}
}
