//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_10014
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10014";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class IndicatorCollection : System.Collections.Generic.List<R_10013.Indicator>
	{
	}



	[XmlType(TypeName="ProgrammeIndicators",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ProgrammeIndicators
	{


		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="id",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="isLocked",DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __isLocked;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __isLockedSpecified;
		
		[XmlIgnore]
		public bool isLocked
		{ 
			get { return __isLocked; }
			set { __isLocked = value; __isLockedSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="programmeCode",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __programmeCode;
		
		[XmlIgnore]
		public string programmeCode
		{ 
			get { return __programmeCode; }
			set { __programmeCode = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="programmeName",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __programmeName;
		
		[XmlIgnore]
		public string programmeName
		{ 
			get { return __programmeName; }
			set { __programmeName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10013.Indicator),ElementName="Indicator",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public IndicatorCollection __IndicatorCollection;
		
		[XmlIgnore]
		public IndicatorCollection IndicatorCollection
		{
			get
			{
				if (__IndicatorCollection == null) __IndicatorCollection = new IndicatorCollection();
				return __IndicatorCollection;
			}
			set {__IndicatorCollection = value;}
		}

		public ProgrammeIndicators()
		{
		}
	}
}
