//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace R_10079
{

	public struct Declarations
	{
		public const string SchemaVersion = "http://ereg.egov.bg/segment/R-10079";
	}




	[XmlType(TypeName="OfferBasicData",Namespace=Declarations.SchemaVersion),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class OfferBasicData
	{

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="id",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlAttribute(AttributeName="isLocked",DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __isLocked;
		
		[System.Web.Script.Serialization.ScriptIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __isLockedSpecified;
		
		[XmlIgnore]
		public bool isLocked
		{ 
			get { return __isLocked; }
			set { __isLocked = value; __isLockedSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10000.PrivateNomenclature),ElementName="BeneficiaryUinType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10000.PrivateNomenclature __BeneficiaryUinType;
		
		[XmlIgnore]
		public R_10000.PrivateNomenclature BeneficiaryUinType
		{
			get {return __BeneficiaryUinType;}
			set {__BeneficiaryUinType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="BeneficiaryUin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BeneficiaryUin;
		
		[XmlIgnore]
		public string BeneficiaryUin
		{ 
			get { return __BeneficiaryUin; }
			set { __BeneficiaryUin = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PlanName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __PlanName;
		
		[XmlIgnore]
		public string PlanName
		{ 
			get { return __PlanName; }
			set { __PlanName = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10001.PublicNomenclature),ElementName="PlanErrandArea",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10001.PublicNomenclature __PlanErrandArea;
		
		[XmlIgnore]
		public R_10001.PublicNomenclature PlanErrandArea
		{
			get {return __PlanErrandArea;}
			set {__PlanErrandArea = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10000.PrivateNomenclature),ElementName="PlanErrandLegalAct",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10000.PrivateNomenclature __PlanErrandLegalAct;
		
		[XmlIgnore]
		public R_10000.PrivateNomenclature PlanErrandLegalAct
		{
			get {return __PlanErrandLegalAct;}
			set {__PlanErrandLegalAct = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10001.PublicNomenclature),ElementName="PlanErrandType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10001.PublicNomenclature __PlanErrandType;
		
		[XmlIgnore]
		public R_10001.PublicNomenclature PlanErrandType
		{
			get {return __PlanErrandType;}
			set {__PlanErrandType = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PlanExpectedAmount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="decimal",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public decimal __PlanExpectedAmount;
		
		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __PlanExpectedAmountSpecified;
		
		[XmlIgnore]
		public decimal PlanExpectedAmount
		{ 
			get { return __PlanExpectedAmount; }
			set { __PlanExpectedAmount = value; __PlanExpectedAmountSpecified = true; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(ElementName="PlanDescription",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __PlanDescription;
		
		[XmlIgnore]
		public string PlanDescription
		{ 
			get { return __PlanDescription; }
			set { __PlanDescription = value; }
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_10071.DifferentiatedPosition),ElementName="DifferentiatedPosition",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_10071.DifferentiatedPosition __DifferentiatedPosition;
		
		[XmlIgnore]
		public R_10071.DifferentiatedPosition DifferentiatedPosition
		{
			get {return __DifferentiatedPosition;}
			set {__DifferentiatedPosition = value;}
		}

		[System.Web.Script.Serialization.ScriptIgnore]
        [Newtonsoft.Json.JsonIgnore]
		[XmlElement(Type=typeof(R_09991.EnumNomenclature),ElementName="BeneficiaryRegistrationVAT",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace=Declarations.SchemaVersion)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public R_09991.EnumNomenclature __BeneficiaryRegistrationVAT;
		
		[XmlIgnore]
		public R_09991.EnumNomenclature BeneficiaryRegistrationVAT
		{
			get {return __BeneficiaryRegistrationVAT;}
			set {__BeneficiaryRegistrationVAT = value;}
		}

		public OfferBasicData()
		{
		}
	}
}
