//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.RegiX.Rio.BABHZhS
{


	using FarmInformation2Collection = System.Collections.Generic.List<Eumis.RegiX.Rio.BABHZhS.FarmInformation2>;

	using AnimalCategory2Collection = System.Collections.Generic.List<Eumis.RegiX.Rio.BABHZhS.AnimalCategory2>;

	using RelatedPersonDataTypeCollection = System.Collections.Generic.List<Eumis.RegiX.Rio.BABHZhS.RelatedPersonDataType>;



	[XmlType(TypeName="Address",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class Address
	{

		[XmlElement(ElementName="DistrictName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __DistrictName;
		
		[XmlIgnore]
		public string DistrictName
		{ 
			get { return __DistrictName; }
			set { __DistrictName = value; }
		}

		[XmlElement(ElementName="MunicipalityName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __MunicipalityName;
		
		[XmlIgnore]
		public string MunicipalityName
		{ 
			get { return __MunicipalityName; }
			set { __MunicipalityName = value; }
		}

		[XmlElement(ElementName="SettlementName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SettlementName;
		
		[XmlIgnore]
		public string SettlementName
		{ 
			get { return __SettlementName; }
			set { __SettlementName = value; }
		}

		[XmlElement(ElementName="AddressDescription",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AddressDescription;
		
		[XmlIgnore]
		public string AddressDescription
		{ 
			get { return __AddressDescription; }
			set { __AddressDescription = value; }
		}

		public Address()
		{
		}
	}


	[XmlType(TypeName="FarmerData2",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FarmerData2
	{

		[XmlElement(ElementName="FarmerName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FarmerName;
		
		[XmlIgnore]
		public string FarmerName
		{ 
			get { return __FarmerName; }
			set { __FarmerName = value; }
		}

		[XmlElement(ElementName="FarmerIdentifier",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FarmerIdentifier;
		
		[XmlIgnore]
		public string FarmerIdentifier
		{ 
			get { return __FarmerIdentifier; }
			set { __FarmerIdentifier = value; }
		}

		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.Address),ElementName="Address",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.BABHZhS.Address __Address;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.BABHZhS.Address Address
		{
			get {return __Address;}
			set {__Address = value;}
		}

		public FarmerData2()
		{
		}
	}


	[XmlType(TypeName="FarmIdentifiers",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FarmIdentifiers
	{

		[XmlElement(ElementName="FarmNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FarmNumber;
		
		[XmlIgnore]
		public string FarmNumber
		{ 
			get { return __FarmNumber; }
			set { __FarmNumber = value; }
		}

		[XmlElement(ElementName="OldFarmNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __OldFarmNumber;
		
		[XmlIgnore]
		public string OldFarmNumber
		{ 
			get { return __OldFarmNumber; }
			set { __OldFarmNumber = value; }
		}

		public FarmIdentifiers()
		{
		}
	}


	[XmlType(TypeName="RelatedPersonDataType",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class RelatedPersonDataType
	{

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Identifier",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Identifier;
		
		[XmlIgnore]
		public string Identifier
		{ 
			get { return __Identifier; }
			set { __Identifier = value; }
		}

		[XmlElement(ElementName="Type",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Type;
		
		[XmlIgnore]
		public string Type
		{ 
			get { return __Type; }
			set { __Type = value; }
		}

		public RelatedPersonDataType()
		{
		}
	}


	[XmlType(TypeName="AnimalCategory2",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class AnimalCategory2
	{

		[XmlElement(ElementName="CategoryCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __CategoryCode;
		
		[XmlIgnore]
		public string CategoryCode
		{ 
			get { return __CategoryCode; }
			set { __CategoryCode = value; }
		}

		[XmlElement(ElementName="CategoryName",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __CategoryName;
		
		[XmlIgnore]
		public string CategoryName
		{ 
			get { return __CategoryName; }
			set { __CategoryName = value; }
		}

		[XmlElement(ElementName="AnimalsCount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="long",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public long __AnimalsCount;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __AnimalsCountSpecified;
		
		[XmlIgnore]
		public long AnimalsCount
		{ 
			get { return __AnimalsCount; }
			set { __AnimalsCount = value; __AnimalsCountSpecified = true; }
		}

		[XmlElement(ElementName="AnimalUnitFactor",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double __AnimalUnitFactor;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __AnimalUnitFactorSpecified;
		
		[XmlIgnore]
		public double AnimalUnitFactor
		{ 
			get { return __AnimalUnitFactor; }
			set { __AnimalUnitFactor = value; __AnimalUnitFactorSpecified = true; }
		}

		[XmlElement(ElementName="AnimalUnits",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double __AnimalUnits;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __AnimalUnitsSpecified;
		
		[XmlIgnore]
		public double AnimalUnits
		{ 
			get { return __AnimalUnits; }
			set { __AnimalUnits = value; __AnimalUnitsSpecified = true; }
		}

		public AnimalCategory2()
		{
		}
	}


	[XmlType(TypeName="RelatedPersonData",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class RelatedPersonData
	{


		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.RelatedPersonDataType),ElementName="Person",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public RelatedPersonDataTypeCollection __PersonCollection;
		
		[XmlIgnore]
		public RelatedPersonDataTypeCollection PersonCollection
		{
			get
			{
				if (__PersonCollection == null) __PersonCollection = new RelatedPersonDataTypeCollection();
				return __PersonCollection;
			}
			set {__PersonCollection = value;}
		}

		public RelatedPersonData()
		{
		}
	}


	[XmlType(TypeName="FarmInformation2",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FarmInformation2
	{

		[XmlElement(ElementName="FarmerRole",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FarmerRole;
		
		[XmlIgnore]
		public string FarmerRole
		{ 
			get { return __FarmerRole; }
			set { __FarmerRole = value; }
		}

		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.FarmIdentifiers),ElementName="FarmIdentifiers",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.BABHZhS.FarmIdentifiers __FarmIdentifiers;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.BABHZhS.FarmIdentifiers FarmIdentifiers
		{
			get {return __FarmIdentifiers;}
			set {__FarmIdentifiers = value;}
		}

		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.Address),ElementName="FarmAddress",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.BABHZhS.Address __FarmAddress;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.BABHZhS.Address FarmAddress
		{
			get {return __FarmAddress;}
			set {__FarmAddress = value;}
		}

		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.RelatedPersonData),ElementName="RelatedPersonData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.BABHZhS.RelatedPersonData __RelatedPersonData;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.BABHZhS.RelatedPersonData RelatedPersonData
		{
			get {return __RelatedPersonData;}
			set {__RelatedPersonData = value;}
		}

		[XmlElement(Type=typeof(AnimalsByCategories),ElementName="AnimalsByCategories",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AnimalsByCategories __AnimalsByCategories;
		
		[XmlIgnore]
		public AnimalsByCategories AnimalsByCategories
		{
			get {return __AnimalsByCategories;}
			set {__AnimalsByCategories = value;}
		}

		[XmlElement(ElementName="FarmType",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FarmType;
		
		[XmlIgnore]
		public string FarmType
		{ 
			get { return __FarmType; }
			set { __FarmType = value; }
		}

		public FarmInformation2()
		{
		}
	}


	[XmlType(TypeName="AnimalsByCategories",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	public partial class AnimalsByCategories
	{


		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.AnimalCategory2),ElementName="AnimalCategory",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public AnimalCategory2Collection __AnimalCategoryCollection;
		
		[XmlIgnore]
		public AnimalCategory2Collection AnimalCategoryCollection
		{
			get
			{
				if (__AnimalCategoryCollection == null) __AnimalCategoryCollection = new AnimalCategory2Collection();
				return __AnimalCategoryCollection;
			}
			set {__AnimalCategoryCollection = value;}
		}

		public AnimalsByCategories()
		{
		}
	}


	[XmlType(TypeName="FarmsData",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class FarmsData
	{


		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.FarmInformation2),ElementName="FarmInformation",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public FarmInformation2Collection __FarmInformationCollection;
		
		[XmlIgnore]
		public FarmInformation2Collection FarmInformationCollection
		{
			get
			{
				if (__FarmInformationCollection == null) __FarmInformationCollection = new FarmInformation2Collection();
				return __FarmInformationCollection;
			}
			set {__FarmInformationCollection = value;}
		}

		public FarmsData()
		{
		}
	}


	[XmlType(TypeName="RegisteredAnimalsInOEZByCategoryResponseType",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class RegisteredAnimalsInOEZByCategoryResponseType
	{

		[XmlElement(ElementName="ValidDate",Form=XmlSchemaForm.Qualified,DataType="dateTime",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __ValidDate;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ValidDateSpecified { get { return __ValidDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? ValidDate
		{ 
			get { return __ValidDate; }
			set { __ValidDate = value; }
		}
		


		[XmlElement(ElementName="ExecutionDate",Form=XmlSchemaForm.Qualified,DataType="dateTime",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __ExecutionDate;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ExecutionDateSpecified { get { return __ExecutionDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? ExecutionDate
		{ 
			get { return __ExecutionDate; }
			set { __ExecutionDate = value; }
		}
		


		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.FarmerData2),ElementName="FarmerData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.BABHZhS.FarmerData2 __FarmerData;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.BABHZhS.FarmerData2 FarmerData
		{
			get {return __FarmerData;}
			set {__FarmerData = value;}
		}

		[XmlElement(Type=typeof(Eumis.RegiX.Rio.BABHZhS.FarmsData),ElementName="FarmsData",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.BABHZhS.FarmsData __FarmsData;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.BABHZhS.FarmsData FarmsData
		{
			get {return __FarmsData;}
			set {__FarmsData = value;}
		}

		public RegisteredAnimalsInOEZByCategoryResponseType()
		{
		}
	}


	[XmlRoot(ElementName="RegisteredAnimalsInOEZByCategoryResponse",Namespace="http://egov.bg/RegiX/BABH/BABHZhS/RegisteredAnimalsInOEZByCategoryResponse",IsNullable=false),Serializable]
	public partial class RegisteredAnimalsInOEZByCategoryResponse : Eumis.RegiX.Rio.BABHZhS.RegisteredAnimalsInOEZByCategoryResponseType
	{

		public RegisteredAnimalsInOEZByCategoryResponse() : base()
		{
		}
	}
}
