-- 8f0f30b Refactor Project permissions

GO
UPDATE PermissionTemplates SET PermissionsString = 'CompanyPermissions,CanRead;CompanyPermissions,CanWrite;UserAdminPermissions,CanAdministrate;UserAdminPermissions,CanControl;RegistrationPermissions,CanRead|1,OperationalMapPermissions,CanRead;1,OperationalMapPermissions,CanWrite;1,ProcedurePermissions,CanRead;1,ProcedurePermissions,CanWrite;1,ProcedurePermissions,CanCheck;1,ProcedurePermissions,CanDelete;1,ProjectPermissions,CanRead;1,ProjectPermissions,CanRegister;2,OperationalMapPermissions,CanRead;2,OperationalMapPermissions,CanWrite;2,ProcedurePermissions,CanRead;2,ProcedurePermissions,CanWrite;2,ProcedurePermissions,CanCheck;2,ProcedurePermissions,CanDelete;2,ProjectPermissions,CanRead;2,ProjectPermissions,CanRegister;3,OperationalMapPermissions,CanRead;3,OperationalMapPermissions,CanWrite;3,ProcedurePermissions,CanRead;3,ProcedurePermissions,CanWrite;3,ProcedurePermissions,CanCheck;3,ProcedurePermissions,CanDelete;3,ProjectPermissions,CanRead;3,ProjectPermissions,CanRegister;4,OperationalMapPermissions,CanRead;4,OperationalMapPermissions,CanWrite;4,ProcedurePermissions,CanRead;4,ProcedurePermissions,CanWrite;4,ProcedurePermissions,CanCheck;4,ProcedurePermissions,CanDelete;4,ProjectPermissions,CanRead;4,ProjectPermissions,CanRegister;5,OperationalMapPermissions,CanRead;5,OperationalMapPermissions,CanWrite;5,ProcedurePermissions,CanRead;5,ProcedurePermissions,CanWrite;5,ProcedurePermissions,CanCheck;5,ProcedurePermissions,CanDelete;5,ProjectPermissions,CanRead;5,ProjectPermissions,CanRegister;6,OperationalMapPermissions,CanRead;6,OperationalMapPermissions,CanWrite;6,ProcedurePermissions,CanRead;6,ProcedurePermissions,CanWrite;6,ProcedurePermissions,CanCheck;6,ProcedurePermissions,CanDelete;6,ProjectPermissions,CanRead;6,ProjectPermissions,CanRegister;7,OperationalMapPermissions,CanRead;7,OperationalMapPermissions,CanWrite;7,ProcedurePermissions,CanRead;7,ProcedurePermissions,CanWrite;7,ProcedurePermissions,CanCheck;7,ProcedurePermissions,CanDelete;7,ProjectPermissions,CanRead;7,ProjectPermissions,CanRegister' WHERE PermissionTemplateId = 1
UPDATE UserPermissions SET Permission = 'CanRegister' WHERE PermissionType = N'Project' AND Permission = 'CanWrite';
UPDATE u SET PermissionTemplate = pt.PermissionsString
    FROM Users u
    INNER JOIN UserTypes ut on u.UserTypeId = ut.UserTypeId
    INNER JOIN PermissionTemplates pt on ut.PermissionTemplateId = pt.PermissionTemplateId
    WHERE pt.PermissionTemplateId = 1;
