CREATE TABLE [dbo].[MapNodeIndicatorReportedAmounts] (
    [MapNodeId]         INT NOT NULL,
    [IndicatorId]       INT NOT NULL,
    [Men2014]           INT NOT NULL    DEFAULT 0,
    [Men2015]           INT NOT NULL    DEFAULT 0,
    [Men2016]           INT NOT NULL    DEFAULT 0,
    [Men2017]           INT NOT NULL    DEFAULT 0,
    [Men2018]           INT NOT NULL    DEFAULT 0,
    [Men2019]           INT NOT NULL    DEFAULT 0,
    [Men2020]           INT NOT NULL    DEFAULT 0,
    [Men2021]           INT NOT NULL    DEFAULT 0,
    [Men2022]           INT NOT NULL    DEFAULT 0,
    [Men2023]           INT NOT NULL    DEFAULT 0,
    [Women2014]         INT NOT NULL    DEFAULT 0,
    [Women2015]         INT NOT NULL    DEFAULT 0,
    [Women2016]         INT NOT NULL    DEFAULT 0,
    [Women2017]         INT NOT NULL    DEFAULT 0,
    [Women2018]         INT NOT NULL    DEFAULT 0,
    [Women2019]         INT NOT NULL    DEFAULT 0,
    [Women2020]         INT NOT NULL    DEFAULT 0,
    [Women2021]         INT NOT NULL    DEFAULT 0,
    [Women2022]         INT NOT NULL    DEFAULT 0,
    [Women2023]         INT NOT NULL    DEFAULT 0,
    [Total2014]         INT NOT NULL    DEFAULT 0,
    [Total2015]         INT NOT NULL    DEFAULT 0,      
    [Total2016]         INT NOT NULL    DEFAULT 0,
    [Total2017]         INT NOT NULL    DEFAULT 0,
    [Total2018]         INT NOT NULL    DEFAULT 0,
    [Total2019]         INT NOT NULL    DEFAULT 0,
    [Total2020]         INT NOT NULL    DEFAULT 0,
    [Total2021]         INT NOT NULL    DEFAULT 0,
    [Total2022]         INT NOT NULL    DEFAULT 0,
    [Total2023]         INT NOT NULL    DEFAULT 0,
    CONSTRAINT [PK_MapNodeIndicatorReportedAmounts]                 PRIMARY KEY ([MapNodeId], [IndicatorId]),
    CONSTRAINT [FK_MapNodeIndicatorReportedAmounts_MapNodes]        FOREIGN KEY ([MapNodeId])       REFERENCES [dbo].[MapNodes] ([MapNodeId]),
    CONSTRAINT [FK_MapNodeIndicatorReportedAmounts_Indicators]      FOREIGN KEY ([IndicatorId])     REFERENCES [dbo].[Indicators] ([IndicatorId])
);
