// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Eumis.Portal.Web.Controllers
{
    public partial class SubmitController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SubmitController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LoadIsunFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadIsunFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Preview()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Preview);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult SaveDeclaration()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.SaveDeclaration);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.FileResult SaveLabel()
        {
            return new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.SaveLabel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QR()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QR);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ContentResult DeleteSignature()
        {
            return new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.DeleteSignature);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ContentResult Save()
        {
            return new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Save);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SubmitController Actions { get { return MVC.Submit; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Submit";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Submit";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Disclaimer = "Disclaimer";
            public readonly string LoadIsunFile = "LoadIsunFile";
            public readonly string Finalized = "Finalized";
            public readonly string Preview = "Preview";
            public readonly string HowToSubmit = "HowToSubmit";
            public readonly string SaveForPaper = "SaveForPaper";
            public readonly string Paper = "Paper";
            public readonly string SaveDeclaration = "SaveDeclaration";
            public readonly string SaveLabel = "SaveLabel";
            public readonly string Signature = "Signature";
            public readonly string Download = "Download";
            public readonly string Finish = "Finish";
            public readonly string QR = "QR";
            public readonly string DeleteSignature = "DeleteSignature";
            public readonly string Prepare = "Prepare";
            public readonly string Display = "Display";
            public readonly string Save = "Save";
            public readonly string Print = "Print";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Disclaimer = "Disclaimer";
            public const string LoadIsunFile = "LoadIsunFile";
            public const string Finalized = "Finalized";
            public const string Preview = "Preview";
            public const string HowToSubmit = "HowToSubmit";
            public const string SaveForPaper = "SaveForPaper";
            public const string Paper = "Paper";
            public const string SaveDeclaration = "SaveDeclaration";
            public const string SaveLabel = "SaveLabel";
            public const string Signature = "Signature";
            public const string Download = "Download";
            public const string Finish = "Finish";
            public const string QR = "QR";
            public const string DeleteSignature = "DeleteSignature";
            public const string Prepare = "Prepare";
            public const string Display = "Display";
            public const string Save = "Save";
            public const string Print = "Print";
        }


        static readonly ActionParamsClass_Disclaimer s_params_Disclaimer = new ActionParamsClass_Disclaimer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Disclaimer DisclaimerParams { get { return s_params_Disclaimer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Disclaimer
        {
            public readonly string isAcceptedDisclaimer = "isAcceptedDisclaimer";
        }
        static readonly ActionParamsClass_LoadIsunFile s_params_LoadIsunFile = new ActionParamsClass_LoadIsunFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadIsunFile LoadIsunFileParams { get { return s_params_LoadIsunFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadIsunFile
        {
            public readonly string form = "form";
        }
        static readonly ActionParamsClass_Finalized s_params_Finalized = new ActionParamsClass_Finalized();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Finalized FinalizedParams { get { return s_params_Finalized; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Finalized
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Preview s_params_Preview = new ActionParamsClass_Preview();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Preview PreviewParams { get { return s_params_Preview; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Preview
        {
            public readonly string gid = "gid";
        }
        static readonly ActionParamsClass_SaveDeclaration s_params_SaveDeclaration = new ActionParamsClass_SaveDeclaration();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDeclaration SaveDeclarationParams { get { return s_params_SaveDeclaration; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDeclaration
        {
            public readonly string hash = "hash";
        }
        static readonly ActionParamsClass_SaveLabel s_params_SaveLabel = new ActionParamsClass_SaveLabel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveLabel SaveLabelParams { get { return s_params_SaveLabel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveLabel
        {
            public readonly string hash = "hash";
        }
        static readonly ActionParamsClass_Signature s_params_Signature = new ActionParamsClass_Signature();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Signature SignatureParams { get { return s_params_Signature; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Signature
        {
            public readonly string form = "form";
        }
        static readonly ActionParamsClass_QR s_params_QR = new ActionParamsClass_QR();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QR QRParams { get { return s_params_QR; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QR
        {
            public readonly string hash = "hash";
            public readonly string width = "width";
            public readonly string height = "height";
        }
        static readonly ActionParamsClass_DeleteSignature s_params_DeleteSignature = new ActionParamsClass_DeleteSignature();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSignature DeleteSignatureParams { get { return s_params_DeleteSignature; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSignature
        {
            public readonly string key = "key";
        }
        static readonly ActionParamsClass_Prepare s_params_Prepare = new ActionParamsClass_Prepare();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Prepare PrepareParams { get { return s_params_Prepare; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Prepare
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Save s_params_Save = new ActionParamsClass_Save();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Save SaveParams { get { return s_params_Save; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Save
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _BreadcrubSteps = "_BreadcrubSteps";
                public readonly string Declaration = "Declaration";
                public readonly string Disclaimer = "Disclaimer";
                public readonly string Finalized = "Finalized";
                public readonly string Finish = "Finish";
                public readonly string HowToSubmit = "HowToSubmit";
                public readonly string Label = "Label";
                public readonly string Paper = "Paper";
                public readonly string Preview = "Preview";
                public readonly string Signature = "Signature";
            }
            public readonly string _BreadcrubSteps = "~/Views/Submit/_BreadcrubSteps.cshtml";
            public readonly string Declaration = "~/Views/Submit/Declaration.cshtml";
            public readonly string Disclaimer = "~/Views/Submit/Disclaimer.cshtml";
            public readonly string Finalized = "~/Views/Submit/Finalized.cshtml";
            public readonly string Finish = "~/Views/Submit/Finish.cshtml";
            public readonly string HowToSubmit = "~/Views/Submit/HowToSubmit.cshtml";
            public readonly string Label = "~/Views/Submit/Label.cshtml";
            public readonly string Paper = "~/Views/Submit/Paper.cshtml";
            public readonly string Preview = "~/Views/Submit/Preview.cshtml";
            public readonly string Signature = "~/Views/Submit/Signature.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SubmitController : Eumis.Portal.Web.Controllers.SubmitController
    {
        public T4MVC_SubmitController() : base(Dummy.Instance) { }

        [NonAction]
        partial void DisclaimerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Disclaimer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Disclaimer);
            DisclaimerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DisclaimerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool isAcceptedDisclaimer);

        [NonAction]
        public override System.Web.Mvc.ActionResult Disclaimer(bool isAcceptedDisclaimer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Disclaimer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isAcceptedDisclaimer", isAcceptedDisclaimer);
            DisclaimerOverride(callInfo, isAcceptedDisclaimer);
            return callInfo;
        }

        [NonAction]
        partial void LoadIsunFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection form);

        [NonAction]
        public override System.Web.Mvc.ActionResult LoadIsunFile(System.Web.Mvc.FormCollection form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LoadIsunFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            LoadIsunFileOverride(callInfo, form);
            return callInfo;
        }

        [NonAction]
        partial void FinalizedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Finalized(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Finalized);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            FinalizedOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void PreviewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid? gid);

        [NonAction]
        public override System.Web.Mvc.ActionResult Preview(System.Guid? gid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Preview);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gid", gid);
            PreviewOverride(callInfo, gid);
            return callInfo;
        }

        [NonAction]
        partial void HowToSubmitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HowToSubmit()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HowToSubmit);
            HowToSubmitOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveForPaperOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveForPaper()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveForPaper);
            SaveForPaperOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PaperOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Paper()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Paper);
            PaperOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveDeclarationOverride(T4MVC_System_Web_Mvc_FileResult callInfo, string hash);

        [NonAction]
        public override System.Web.Mvc.FileResult SaveDeclaration(string hash)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.SaveDeclaration);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hash", hash);
            SaveDeclarationOverride(callInfo, hash);
            return callInfo;
        }

        [NonAction]
        partial void SaveLabelOverride(T4MVC_System_Web_Mvc_FileResult callInfo, string hash);

        [NonAction]
        public override System.Web.Mvc.FileResult SaveLabel(string hash)
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.SaveLabel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hash", hash);
            SaveLabelOverride(callInfo, hash);
            return callInfo;
        }

        [NonAction]
        partial void SignatureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Signature()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Signature);
            SignatureOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SignatureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection form);

        [NonAction]
        public override System.Web.Mvc.ActionResult Signature(System.Web.Mvc.FormCollection form)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Signature);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "form", form);
            SignatureOverride(callInfo, form);
            return callInfo;
        }

        [NonAction]
        partial void DownloadOverride(T4MVC_System_Web_Mvc_FileResult callInfo);

        [NonAction]
        public override System.Web.Mvc.FileResult Download()
        {
            var callInfo = new T4MVC_System_Web_Mvc_FileResult(Area, Name, ActionNames.Download);
            DownloadOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FinishOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Finish()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Finish);
            FinishOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void QROverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string hash, int width, int height);

        [NonAction]
        public override System.Web.Mvc.ActionResult QR(string hash, int width, int height)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QR);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hash", hash);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "width", width);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "height", height);
            QROverride(callInfo, hash, width, height);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSignatureOverride(T4MVC_System_Web_Mvc_ContentResult callInfo, string key);

        [NonAction]
        public override System.Web.Mvc.ContentResult DeleteSignature(string key)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.DeleteSignature);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "key", key);
            DeleteSignatureOverride(callInfo, key);
            return callInfo;
        }

        [NonAction]
        partial void PrepareOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Prepare()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Prepare);
            PrepareOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PrepareOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Eumis.Portal.Web.Models.ValidationVM model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Prepare(Eumis.Portal.Web.Models.ValidationVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Prepare);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PrepareOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DisplayOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Display()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Display);
            DisplayOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveOverride(T4MVC_System_Web_Mvc_ContentResult callInfo, Eumis.Portal.Web.Models.ValidationVM model);

        [NonAction]
        public override System.Web.Mvc.ContentResult Save(Eumis.Portal.Web.Models.ValidationVM model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Save);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PrintOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Print()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Print);
            PrintOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
