INSERT INTO [UserPermissions]
    ([UserId], [PermissionType] , [Permission]                     , [ProgrammeId])
VALUES
--admin
    (2       , N'UserAdmin'     , 'CanAdministrate'                , NULL         ),
    (2       , N'UserAdmin'     , 'CanControl'                     , NULL         ),

    (2       , N'Company'       , 'CanRead'                        , NULL         ),
    (2       , N'Company'       , 'CanWrite'                       , NULL         ),

    (2       , N'Registration'  , 'CanRead'                        , NULL         ),

    (2       , N'OperationalMap', 'CanRead'                        , 1            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 1            ),
    (2       , N'OperationalMap', 'CanRead'                        , 2            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 2            ),
    (2       , N'OperationalMap', 'CanRead'                        , 3            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 3            ),
    (2       , N'OperationalMap', 'CanRead'                        , 4            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 4            ),
    (2       , N'OperationalMap', 'CanRead'                        , 5            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 5            ),
    (2       , N'OperationalMap', 'CanRead'                        , 6            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 6            ),
    (2       , N'OperationalMap', 'CanRead'                        , 7            ),
    (2       , N'OperationalMap', 'CanWrite'                       , 7            ),

    (2       , N'Procedure'     , 'CanRead'                        , 1            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (2       , N'Procedure'     , 'CanRead'                        , 2            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (2       , N'Procedure'     , 'CanRead'                        , 3            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (2       , N'Procedure'     , 'CanRead'                        , 4            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (2       , N'Procedure'     , 'CanRead'                        , 5            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (2       , N'Procedure'     , 'CanRead'                        , 6            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (2       , N'Procedure'     , 'CanRead'                        , 7            ),
    (2       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (2       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (2       , N'Procedure'     , 'CanDelete'                      , 7            ),

    (2       , N'Project'       , 'CanRead'                        , 1            ),
    (2       , N'Project'       , 'CanRegister'                    , 1            ),
    (2       , N'Project'       , 'CanRead'                        , 2            ),
    (2       , N'Project'       , 'CanRegister'                    , 2            ),
    (2       , N'Project'       , 'CanRead'                        , 3            ),
    (2       , N'Project'       , 'CanRegister'                    , 3            ),
    (2       , N'Project'       , 'CanRead'                        , 4            ),
    (2       , N'Project'       , 'CanRegister'                    , 4            ),
    (2       , N'Project'       , 'CanRead'                        , 5            ),
    (2       , N'Project'       , 'CanRegister'                    , 5            ),
    (2       , N'Project'       , 'CanRead'                        , 6            ),
    (2       , N'Project'       , 'CanRegister'                    , 6            ),
    (2       , N'Project'       , 'CanRead'                        , 7            ),
    (2       , N'Project'       , 'CanRegister'                    , 7            ),

--uis
    (3       , N'UserAdmin'     , 'CanAdministrate'                , NULL         ),
    (3       , N'UserAdmin'     , 'CanControl'                     , NULL         ),

    (3       , N'Company'       , 'CanRead'                        , NULL         ),
    (3       , N'Company'       , 'CanWrite'                       , NULL         ),

    (3       , N'Registration'  , 'CanRead'                        , NULL         ),

    (3       , N'OperationalMap', 'CanRead'                        , 1            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 1            ),
    (3       , N'OperationalMap', 'CanRead'                        , 2            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 2            ),
    (3       , N'OperationalMap', 'CanRead'                        , 3            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 3            ),
    (3       , N'OperationalMap', 'CanRead'                        , 4            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 4            ),
    (3       , N'OperationalMap', 'CanRead'                        , 5            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 5            ),
    (3       , N'OperationalMap', 'CanRead'                        , 6            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 6            ),
    (3       , N'OperationalMap', 'CanRead'                        , 7            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 7            ),

    (3       , N'Procedure'     , 'CanRead'                        , 1            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (3       , N'Procedure'     , 'CanRead'                        , 2            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (3       , N'Procedure'     , 'CanRead'                        , 3            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (3       , N'Procedure'     , 'CanRead'                        , 4            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (3       , N'Procedure'     , 'CanRead'                        , 5            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (3       , N'Procedure'     , 'CanRead'                        , 6            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (3       , N'Procedure'     , 'CanRead'                        , 7            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 7            ),

    (3       , N'Project'       , 'CanRead'                        , 1            ),
    (3       , N'Project'       , 'CanRegister'                    , 1            ),
    (3       , N'Project'       , 'CanRead'                        , 2            ),
    (3       , N'Project'       , 'CanRegister'                    , 2            ),
    (3       , N'Project'       , 'CanRead'                        , 3            ),
    (3       , N'Project'       , 'CanRegister'                    , 3            ),
    (3       , N'Project'       , 'CanRead'                        , 4            ),
    (3       , N'Project'       , 'CanRegister'                    , 4            ),
    (3       , N'Project'       , 'CanRead'                        , 5            ),
    (3       , N'Project'       , 'CanRegister'                    , 5            ),
    (3       , N'Project'       , 'CanRead'                        , 6            ),
    (3       , N'Project'       , 'CanRegister'                    , 6            ),
    (3       , N'Project'       , 'CanRead'                        , 7            ),
    (3       , N'Project'       , 'CanRegister'                    , 7            )
