PRINT 'Insert Users'
GO

DECLARE @suTemplate NVARCHAR(MAX);
SELECT @suTemplate = PermissionsString FROM PermissionTemplates WHERE Name = N'Всички права';

SET IDENTITY_INSERT [Users] ON

INSERT INTO [Users]
    ([UserId], [Gid]                                 , [UserTypeId], [UserOrganizationId], [IsSystem], [Username]          , [PasswordHash]                                                         , [PasswordSalt]             , [Uin]        ,[Fullname]             , [Email]            , [IsActive], [IsDeleted], [IsLocked], [CreateDate], [ModifyDate], [FailedAttempts], [PermissionTemplate])
VALUES
    (1       , '3A459B75-AC1C-40EB-A50E-7A5993850906', 1           , 1                   , 1         , N'system'           , NULL                                                                   , NULL                       , N'1212927890', N'Системен потребител' , N''                , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , N''                 ),
    (2       , '72D84827-31C0-47FA-B7A0-10D3F4C348E8', 1           , 1                   , 0         , N'admin'            , N'AMWr4Peeajc9Q0bsdV7mWBwK6fLJN/Cr/ksp2jV4M50RQ587JQHptHzA7HLDOLSHGg==', N'88SHIJlJUThYeUFDUQKJoQ==', N'1502784562', N'Администратор'       , N'admin@isun.com'  , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , @suTemplate         ),
    (3       , 'F3E14F07-9E10-4645-B08E-DD022CE0B3B2', 1           , 1                   , 0         , N'test1'            , N'AMWr4Peeajc9Q0bsdV7mWBwK6fLJN/Cr/ksp2jV4M50RQ587JQHptHzA7HLDOLSHGg==', N'88SHIJlJUThYeUFDUQKJoQ==', N'0612887525', N'Администратор ЦКЗ'   , N'test1@isun.com'  , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , @suTemplate         ),

--EvalSession test users(password: 'peter')
    (5       , NEWID()                               , 16          , 1                   , 0         , N'adminSessions'    , N'AMWr4Peeajc9Q0bsdV7mWBwK6fLJN/Cr/ksp2jV4M50RQ587JQHptHzA7HLDOLSHGg==', N'88SHIJlJUThYeUFDUQKJoQ==', N'0612887525', N'Админ сесии'         , N'test1@isun.com'  , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , N'CompanyPermissions,CanRead;CompanyPermissions,CanWrite;RegistrationPermissions,CanRead|1,OperationalMapPermissions,CanRead;1,OperationalMapPermissions,CanWrite;1,ProcedurePermissions,CanRead;1,ProcedurePermissions,CanWrite;1,ProcedurePermissions,CanCheck;1,ProcedurePermissions,CanDelete;1,ProjectPermissions,CanRead;1,ProjectPermissions,CanRegister;1,EvalSessionPermissions,CanAdministrate;2,OperationalMapPermissions,CanRead;2,OperationalMapPermissions,CanWrite;2,ProcedurePermissions,CanRead;2,ProcedurePermissions,CanWrite;2,ProcedurePermissions,CanCheck;2,ProcedurePermissions,CanDelete;2,ProjectPermissions,CanRead;2,ProjectPermissions,CanRegister;2,EvalSessionPermissions,CanAdministrate;3,OperationalMapPermissions,CanRead;3,OperationalMapPermissions,CanWrite;3,ProcedurePermissions,CanRead;3,ProcedurePermissions,CanWrite;3,ProcedurePermissions,CanCheck;3,ProcedurePermissions,CanDelete;3,ProjectPermissions,CanRead;3,ProjectPermissions,CanRegister;3,EvalSessionPermissions,CanAdministrate;4,OperationalMapPermissions,CanRead;4,OperationalMapPermissions,CanWrite;4,ProcedurePermissions,CanRead;4,ProcedurePermissions,CanWrite;4,ProcedurePermissions,CanCheck;4,ProcedurePermissions,CanDelete;4,ProjectPermissions,CanRead;4,ProjectPermissions,CanRegister;4,EvalSessionPermissions,CanAdministrate;5,OperationalMapPermissions,CanRead;5,OperationalMapPermissions,CanWrite;5,ProcedurePermissions,CanRead;5,ProcedurePermissions,CanWrite;5,ProcedurePermissions,CanCheck;5,ProcedurePermissions,CanDelete;5,ProjectPermissions,CanRead;5,ProjectPermissions,CanRegister;5,EvalSessionPermissions,CanAdministrate;6,OperationalMapPermissions,CanRead;6,OperationalMapPermissions,CanWrite;6,ProcedurePermissions,CanRead;6,ProcedurePermissions,CanWrite;6,ProcedurePermissions,CanCheck;6,ProcedurePermissions,CanDelete;6,ProjectPermissions,CanRead;6,ProjectPermissions,CanRegister;6,EvalSessionPermissions,CanAdministrate;7,OperationalMapPermissions,CanRead;7,OperationalMapPermissions,CanWrite;7,ProcedurePermissions,CanRead;7,ProcedurePermissions,CanWrite;7,ProcedurePermissions,CanCheck;7,ProcedurePermissions,CanDelete;7,ProjectPermissions,CanRead;7,ProjectPermissions,CanRegister;7,EvalSessionPermissions,CanAdministrate' ),
    (6       , NEWID()                               , 17          , 1                   , 0         , N'adminSession'     , N'AMWr4Peeajc9Q0bsdV7mWBwK6fLJN/Cr/ksp2jV4M50RQ587JQHptHzA7HLDOLSHGg==', N'88SHIJlJUThYeUFDUQKJoQ==', N'0612887525', N'Админ сесия'         , N'test1@isun.com'  , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , N'CompanyPermissions,CanRead;CompanyPermissions,CanWrite;RegistrationPermissions,CanRead|1,OperationalMapPermissions,CanRead;1,OperationalMapPermissions,CanWrite;1,ProcedurePermissions,CanRead;1,ProcedurePermissions,CanWrite;1,ProcedurePermissions,CanCheck;1,ProcedurePermissions,CanDelete;1,ProjectPermissions,CanRead;1,ProjectPermissions,CanRegister;1,EvalSessionPermissions,CanEvaluate;2,OperationalMapPermissions,CanRead;2,OperationalMapPermissions,CanWrite;2,ProcedurePermissions,CanRead;2,ProcedurePermissions,CanWrite;2,ProcedurePermissions,CanCheck;2,ProcedurePermissions,CanDelete;2,ProjectPermissions,CanRead;2,ProjectPermissions,CanRegister;2,EvalSessionPermissions,CanEvaluate;3,OperationalMapPermissions,CanRead;3,OperationalMapPermissions,CanWrite;3,ProcedurePermissions,CanRead;3,ProcedurePermissions,CanWrite;3,ProcedurePermissions,CanCheck;3,ProcedurePermissions,CanDelete;3,ProjectPermissions,CanRead;3,ProjectPermissions,CanRegister;3,EvalSessionPermissions,CanEvaluate;4,OperationalMapPermissions,CanRead;4,OperationalMapPermissions,CanWrite;4,ProcedurePermissions,CanRead;4,ProcedurePermissions,CanWrite;4,ProcedurePermissions,CanCheck;4,ProcedurePermissions,CanDelete;4,ProjectPermissions,CanRead;4,ProjectPermissions,CanRegister;4,EvalSessionPermissions,CanEvaluate;5,OperationalMapPermissions,CanRead;5,OperationalMapPermissions,CanWrite;5,ProcedurePermissions,CanRead;5,ProcedurePermissions,CanWrite;5,ProcedurePermissions,CanCheck;5,ProcedurePermissions,CanDelete;5,ProjectPermissions,CanRead;5,ProjectPermissions,CanRegister;5,EvalSessionPermissions,CanEvaluate;6,OperationalMapPermissions,CanRead;6,OperationalMapPermissions,CanWrite;6,ProcedurePermissions,CanRead;6,ProcedurePermissions,CanWrite;6,ProcedurePermissions,CanCheck;6,ProcedurePermissions,CanDelete;6,ProjectPermissions,CanRead;6,ProjectPermissions,CanRegister;6,EvalSessionPermissions,CanEvaluate;7,OperationalMapPermissions,CanRead;7,OperationalMapPermissions,CanWrite;7,ProcedurePermissions,CanRead;7,ProcedurePermissions,CanWrite;7,ProcedurePermissions,CanCheck;7,ProcedurePermissions,CanDelete;7,ProjectPermissions,CanRead;7,ProjectPermissions,CanRegister;7,EvalSessionPermissions,CanEvaluate' ),
    (7       , NEWID()                               , 17          , 1                   , 0         , N'assessor'         , N'AMWr4Peeajc9Q0bsdV7mWBwK6fLJN/Cr/ksp2jV4M50RQ587JQHptHzA7HLDOLSHGg==', N'88SHIJlJUThYeUFDUQKJoQ==', N'0612887525', N'Оценител'            , N'test1@isun.com'  , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , N'CompanyPermissions,CanRead;CompanyPermissions,CanWrite;RegistrationPermissions,CanRead|1,OperationalMapPermissions,CanRead;1,OperationalMapPermissions,CanWrite;1,ProcedurePermissions,CanRead;1,ProcedurePermissions,CanWrite;1,ProcedurePermissions,CanCheck;1,ProcedurePermissions,CanDelete;1,ProjectPermissions,CanRead;1,ProjectPermissions,CanRegister;1,EvalSessionPermissions,CanEvaluate;2,OperationalMapPermissions,CanRead;2,OperationalMapPermissions,CanWrite;2,ProcedurePermissions,CanRead;2,ProcedurePermissions,CanWrite;2,ProcedurePermissions,CanCheck;2,ProcedurePermissions,CanDelete;2,ProjectPermissions,CanRead;2,ProjectPermissions,CanRegister;2,EvalSessionPermissions,CanEvaluate;3,OperationalMapPermissions,CanRead;3,OperationalMapPermissions,CanWrite;3,ProcedurePermissions,CanRead;3,ProcedurePermissions,CanWrite;3,ProcedurePermissions,CanCheck;3,ProcedurePermissions,CanDelete;3,ProjectPermissions,CanRead;3,ProjectPermissions,CanRegister;3,EvalSessionPermissions,CanEvaluate;4,OperationalMapPermissions,CanRead;4,OperationalMapPermissions,CanWrite;4,ProcedurePermissions,CanRead;4,ProcedurePermissions,CanWrite;4,ProcedurePermissions,CanCheck;4,ProcedurePermissions,CanDelete;4,ProjectPermissions,CanRead;4,ProjectPermissions,CanRegister;4,EvalSessionPermissions,CanEvaluate;5,OperationalMapPermissions,CanRead;5,OperationalMapPermissions,CanWrite;5,ProcedurePermissions,CanRead;5,ProcedurePermissions,CanWrite;5,ProcedurePermissions,CanCheck;5,ProcedurePermissions,CanDelete;5,ProjectPermissions,CanRead;5,ProjectPermissions,CanRegister;5,EvalSessionPermissions,CanEvaluate;6,OperationalMapPermissions,CanRead;6,OperationalMapPermissions,CanWrite;6,ProcedurePermissions,CanRead;6,ProcedurePermissions,CanWrite;6,ProcedurePermissions,CanCheck;6,ProcedurePermissions,CanDelete;6,ProjectPermissions,CanRead;6,ProjectPermissions,CanRegister;6,EvalSessionPermissions,CanEvaluate;7,OperationalMapPermissions,CanRead;7,OperationalMapPermissions,CanWrite;7,ProcedurePermissions,CanRead;7,ProcedurePermissions,CanWrite;7,ProcedurePermissions,CanCheck;7,ProcedurePermissions,CanDelete;7,ProjectPermissions,CanRead;7,ProjectPermissions,CanRegister;7,EvalSessionPermissions,CanEvaluate' ),
    (8       , NEWID()                               , 17          , 1                   , 0         , N'assistantAssessor', N'AMWr4Peeajc9Q0bsdV7mWBwK6fLJN/Cr/ksp2jV4M50RQ587JQHptHzA7HLDOLSHGg==', N'88SHIJlJUThYeUFDUQKJoQ==', N'0612887525', N'Помощник оценител'   , N'test1@isun.com'  , 1         , 0          , 0         , GETDATE()    ,GETDATE()  , 0               , N'CompanyPermissions,CanRead;CompanyPermissions,CanWrite;RegistrationPermissions,CanRead|1,OperationalMapPermissions,CanRead;1,OperationalMapPermissions,CanWrite;1,ProcedurePermissions,CanRead;1,ProcedurePermissions,CanWrite;1,ProcedurePermissions,CanCheck;1,ProcedurePermissions,CanDelete;1,ProjectPermissions,CanRead;1,ProjectPermissions,CanRegister;1,EvalSessionPermissions,CanEvaluate;2,OperationalMapPermissions,CanRead;2,OperationalMapPermissions,CanWrite;2,ProcedurePermissions,CanRead;2,ProcedurePermissions,CanWrite;2,ProcedurePermissions,CanCheck;2,ProcedurePermissions,CanDelete;2,ProjectPermissions,CanRead;2,ProjectPermissions,CanRegister;2,EvalSessionPermissions,CanEvaluate;3,OperationalMapPermissions,CanRead;3,OperationalMapPermissions,CanWrite;3,ProcedurePermissions,CanRead;3,ProcedurePermissions,CanWrite;3,ProcedurePermissions,CanCheck;3,ProcedurePermissions,CanDelete;3,ProjectPermissions,CanRead;3,ProjectPermissions,CanRegister;3,EvalSessionPermissions,CanEvaluate;4,OperationalMapPermissions,CanRead;4,OperationalMapPermissions,CanWrite;4,ProcedurePermissions,CanRead;4,ProcedurePermissions,CanWrite;4,ProcedurePermissions,CanCheck;4,ProcedurePermissions,CanDelete;4,ProjectPermissions,CanRead;4,ProjectPermissions,CanRegister;4,EvalSessionPermissions,CanEvaluate;5,OperationalMapPermissions,CanRead;5,OperationalMapPermissions,CanWrite;5,ProcedurePermissions,CanRead;5,ProcedurePermissions,CanWrite;5,ProcedurePermissions,CanCheck;5,ProcedurePermissions,CanDelete;5,ProjectPermissions,CanRead;5,ProjectPermissions,CanRegister;5,EvalSessionPermissions,CanEvaluate;6,OperationalMapPermissions,CanRead;6,OperationalMapPermissions,CanWrite;6,ProcedurePermissions,CanRead;6,ProcedurePermissions,CanWrite;6,ProcedurePermissions,CanCheck;6,ProcedurePermissions,CanDelete;6,ProjectPermissions,CanRead;6,ProjectPermissions,CanRegister;6,EvalSessionPermissions,CanEvaluate;7,OperationalMapPermissions,CanRead;7,OperationalMapPermissions,CanWrite;7,ProcedurePermissions,CanRead;7,ProcedurePermissions,CanWrite;7,ProcedurePermissions,CanCheck;7,ProcedurePermissions,CanDelete;7,ProjectPermissions,CanRead;7,ProjectPermissions,CanRegister;7,EvalSessionPermissions,CanEvaluate' )
GO

SET IDENTITY_INSERT [Users] OFF
GO
