INSERT INTO [UserPermissions]
    ([UserId], [PermissionType] , [Permission]                     , [ProgrammeId])
VALUES
--admin
    (2       , N'UserAdmin'             , 'CanAdministrate'                , NULL         ),
    (2       , N'UserAdmin'             , 'CanControl'                     , NULL         ),

    (2       , N'Company'               , 'CanRead'                        , NULL         ),
    (2       , N'Company'               , 'CanWrite'                       , NULL         ),

    (2       , N'CertAuthorityCheck'    , 'CanRead'                        , NULL         ),
    (2       , N'CertAuthorityCheck'    , 'CanWrite'                       , NULL         ),

    (2       , N'Registration'          , 'CanRead'                        , NULL         ),

    (2       , N'ActionLog'             , 'CanRead'                        , NULL         ),

    (2       , N'ContractRegistration'  , 'CanRead'                        , NULL         ),

    (2       , N'News'                  , 'CanPublish'                     , NULL         ),

    (2       , N'Guidance'              , 'CanCreate'                      , NULL         ),

    (2       , N'Monitoring'            , 'CanRead'                        , NULL         ),

    (2       , N'SapInterface'          , 'CanImport'                      , NULL         ),

    (2       , N'OperationalMapAdmin'   , 'CanAdministrate'                , NULL         ),

    (2       , N'OperationalMap'             , 'CanRead'                , 1            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 1            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 2            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 2            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 3            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 3            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 4            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 4            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 5            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 5            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 6            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 6            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 7            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 7            ),
    (2       , N'OperationalMap'             , 'CanRead'                , 8            ),
    (2       , N'OperationalMap'             , 'CanWrite'               , 8            ),

    (2       , N'Procedure'                  , 'CanRead'                , 1            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 1            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 1            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 1            ),
    (2       , N'Procedure'                  , 'CanRead'                , 2            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 2            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 2            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 2            ),
    (2       , N'Procedure'                  , 'CanRead'                , 3            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 3            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 3            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 3            ),
    (2       , N'Procedure'                  , 'CanRead'                , 4            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 4            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 4            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 4            ),
    (2       , N'Procedure'                  , 'CanRead'                , 5            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 5            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 5            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 5            ),
    (2       , N'Procedure'                  , 'CanRead'                , 6            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 6            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 6            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 6            ),
    (2       , N'Procedure'                  , 'CanRead'                , 7            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 7            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 7            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 7            ),
    (2       , N'Procedure'                  , 'CanRead'                , 8            ),
    (2       , N'Procedure'                  , 'CanWrite'               , 8            ),
    (2       , N'Procedure'                  , 'CanCheck'               , 8            ),
    (2       , N'Procedure'                  , 'CanDelete'              , 8            ),

    (2       , N'Project'                    , 'CanRead'                , 1            ),
    (2       , N'Project'                    , 'CanRegister'            , 1            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 1            ),
    (2       , N'Project'                    , 'CanRead'                , 2            ),
    (2       , N'Project'                    , 'CanRegister'            , 2            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 2            ),
    (2       , N'Project'                    , 'CanRead'                , 3            ),
    (2       , N'Project'                    , 'CanRegister'            , 3            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 3            ),
    (2       , N'Project'                    , 'CanRead'                , 4            ),
    (2       , N'Project'                    , 'CanRegister'            , 4            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 4            ),
    (2       , N'Project'                    , 'CanRead'                , 5            ),
    (2       , N'Project'                    , 'CanRegister'            , 5            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 5            ),
    (2       , N'Project'                    , 'CanRead'                , 6            ),
    (2       , N'Project'                    , 'CanRegister'            , 6            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 6            ),
    (2       , N'Project'                    , 'CanRead'                , 7            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 7            ),
    (2       , N'Project'                    , 'CanRegister'            , 7            ),
    (2       , N'Project'                    , 'CanRead'                , 8            ),
    (2       , N'Project'                    , 'CanRegister'            , 8            ),
    (2       , N'Project'                    , 'CanWithdraw'            , 8            ),

    (2       , N'Contract'                   , 'CanRead'                , 1            ),
    (2       , N'Contract'                   , 'CanWrite'               , 1            ),
    (2       , N'Contract'                   , 'CanCheck'               , 1            ),
    (2       , N'Contract'                   , 'CanRead'                , 2            ),
    (2       , N'Contract'                   , 'CanWrite'               , 2            ),
    (2       , N'Contract'                   , 'CanCheck'               , 2            ),
    (2       , N'Contract'                   , 'CanRead'                , 3            ),
    (2       , N'Contract'                   , 'CanWrite'               , 3            ),
    (2       , N'Contract'                   , 'CanCheck'               , 3            ),
    (2       , N'Contract'                   , 'CanRead'                , 4            ),
    (2       , N'Contract'                   , 'CanWrite'               , 4            ),
    (2       , N'Contract'                   , 'CanCheck'               , 4            ),
    (2       , N'Contract'                   , 'CanRead'                , 5            ),
    (2       , N'Contract'                   , 'CanWrite'               , 5            ),
    (2       , N'Contract'                   , 'CanCheck'               , 5            ),
    (2       , N'Contract'                   , 'CanRead'                , 6            ),
    (2       , N'Contract'                   , 'CanWrite'               , 6            ),
    (2       , N'Contract'                   , 'CanCheck'               , 6            ),
    (2       , N'Contract'                   , 'CanRead'                , 7            ),
    (2       , N'Contract'                   , 'CanWrite'               , 7            ),
    (2       , N'Contract'                   , 'CanCheck'               , 7            ),

    (2       , N'ContractCommunication'      , 'CanRead'                , 1            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 1            ),
    (2       , N'ContractCommunication'      , 'CanRead'                , 2            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 2            ),
    (2       , N'ContractCommunication'      , 'CanRead'                , 3            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 3            ),
    (2       , N'ContractCommunication'      , 'CanRead'                , 4            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 4            ),
    (2       , N'ContractCommunication'      , 'CanRead'                , 5            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 5            ),
    (2       , N'ContractCommunication'      , 'CanRead'                , 6            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 6            ),
    (2       , N'ContractCommunication'      , 'CanRead'                , 7            ),
    (2       , N'ContractCommunication'      , 'CanWrite'               , 7            ),

    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 1            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 1            ),
    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 2            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 2            ),
    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 3            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 3            ),
    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 4            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 4            ),
    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 5            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 5            ),
    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 6            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 6            ),
    (2       , N'CertAuthorityCommunication' , 'CanRead'                , 7            ),
    (2       , N'CertAuthorityCommunication' , 'CanWrite'               , 7            ),

    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 1            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 1            ),
    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 2            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 2            ),
    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 3            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 3            ),
    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 4            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 4            ),
    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 5            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 5            ),
    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 6            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 6            ),
    (2       , N'AuditAuthorityCommunication', 'CanRead'                , 7            ),
    (2       , N'AuditAuthorityCommunication', 'CanWrite'               , 7            ),

    (2       , N'ContractReport'        , 'CanRead'                , 1            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 1            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 1            ),
    (2       , N'ContractReport'        , 'CanRead'                , 2            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 2            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 2            ),
    (2       , N'ContractReport'        , 'CanRead'                , 3            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 3            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 3            ),
    (2       , N'ContractReport'        , 'CanRead'                , 4            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 4            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 4            ),
    (2       , N'ContractReport'        , 'CanRead'                , 5            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 5            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 5            ),
    (2       , N'ContractReport'        , 'CanRead'                , 6            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 6            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 6            ),
    (2       , N'ContractReport'        , 'CanRead'                , 7            ),
    (2       , N'ContractReport'        , 'CanWrite'               , 7            ),
    (2       , N'ContractReport'        , 'CanCheck'               , 7            ),

    (2       , N'SpotCheck'             , 'CanRead'                , 1            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 1            ),
    (2       , N'SpotCheck'             , 'CanRead'                , 2            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 2            ),
    (2       , N'SpotCheck'             , 'CanRead'                , 3            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 3            ),
    (2       , N'SpotCheck'             , 'CanRead'                , 4            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 4            ),
    (2       , N'SpotCheck'             , 'CanRead'                , 5            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 5            ),
    (2       , N'SpotCheck'             , 'CanRead'                , 6            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 6            ),
    (2       , N'SpotCheck'             , 'CanRead'                , 7            ),
    (2       , N'SpotCheck'             , 'CanWrite'               , 7            ),

    (2       , N'Audit'                 , 'CanRead'                , 1            ),
    (2       , N'Audit'                 , 'CanWrite'               , 1            ),
    (2       , N'Audit'                 , 'CanRead'                , 2            ),
    (2       , N'Audit'                 , 'CanWrite'               , 2            ),
    (2       , N'Audit'                 , 'CanRead'                , 3            ),
    (2       , N'Audit'                 , 'CanWrite'               , 3            ),
    (2       , N'Audit'                 , 'CanRead'                , 4            ),
    (2       , N'Audit'                 , 'CanWrite'               , 4            ),
    (2       , N'Audit'                 , 'CanRead'                , 5            ),
    (2       , N'Audit'                 , 'CanWrite'               , 5            ),
    (2       , N'Audit'                 , 'CanRead'                , 6            ),
    (2       , N'Audit'                 , 'CanWrite'               , 6            ),
    (2       , N'Audit'                 , 'CanRead'                , 7            ),
    (2       , N'Audit'                 , 'CanWrite'               , 7            ),

    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 1            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 1            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 1            ),
    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 2            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 2            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 2            ),
    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 3            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 3            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 3            ),
    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 4            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 4            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 4            ),
    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 5            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 5            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 5            ),
    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 6            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 6            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 6            ),
    (2       , N'MonitoringFinancialControl'       , 'CanRead'                , 7            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteFinancial'      , 7            ),
    (2       , N'MonitoringFinancialControl'       , 'CanWriteTechnical'      , 7            ),

    (2       , N'IrregularitySignal'    , 'CanRead'                , 1            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 1            ),
    (2       , N'IrregularitySignal'    , 'CanRead'                , 2            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 2            ),
    (2       , N'IrregularitySignal'    , 'CanRead'                , 3            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 3            ),
    (2       , N'IrregularitySignal'    , 'CanRead'                , 4            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 4            ),
    (2       , N'IrregularitySignal'    , 'CanRead'                , 5            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 5            ),
    (2       , N'IrregularitySignal'    , 'CanRead'                , 6            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 6            ),
    (2       , N'IrregularitySignal'    , 'CanRead'                , 7            ),
    (2       , N'IrregularitySignal'    , 'CanWrite'               , 7            ),

    (2       , N'Irregularity'          , 'CanRead'                , 1            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 1            ),
    (2       , N'Irregularity'          , 'CanRead'                , 2            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 2            ),
    (2       , N'Irregularity'          , 'CanRead'                , 3            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 3            ),
    (2       , N'Irregularity'          , 'CanRead'                , 4            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 4            ),
    (2       , N'Irregularity'          , 'CanRead'                , 5            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 5            ),
    (2       , N'Irregularity'          , 'CanRead'                , 6            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 6            ),
    (2       , N'Irregularity'          , 'CanRead'                , 7            ),
    (2       , N'Irregularity'          , 'CanWrite'               , 7            ),

    (2       , N'Certification'          , 'CanRead'                , 1            ),
    (2       , N'Certification'          , 'CanWrite'               , 1            ),
    (2       , N'Certification'          , 'CanRead'                , 2            ),
    (2       , N'Certification'          , 'CanWrite'               , 2            ),
    (2       , N'Certification'          , 'CanRead'                , 3            ),
    (2       , N'Certification'          , 'CanWrite'               , 3            ),
    (2       , N'Certification'          , 'CanRead'                , 4            ),
    (2       , N'Certification'          , 'CanWrite'               , 4            ),
    (2       , N'Certification'          , 'CanRead'                , 5            ),
    (2       , N'Certification'          , 'CanWrite'               , 5            ),
    (2       , N'Certification'          , 'CanRead'                , 6            ),
    (2       , N'Certification'          , 'CanWrite'               , 6            ),
    (2       , N'Certification'          , 'CanRead'                , 7            ),
    (2       , N'Certification'          , 'CanWrite'               , 7            ),

    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 1            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 1            ),
    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 2            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 2            ),
    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 3            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 3            ),
    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 4            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 4            ),
    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 5            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 5            ),
    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 6            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 6            ),
    (2       , N'EuReimbursedAmount'     , 'CanRead'                , 7            ),
    (2       , N'EuReimbursedAmount'     , 'CanWrite'               , 7            ),

    (2       , N'ProjectDossier'         , 'CanRead'                , 1            ),
    (2       , N'ProjectDossier'         , 'CanRead'                , 2            ),
    (2       , N'ProjectDossier'         , 'CanRead'                , 3            ),
    (2       , N'ProjectDossier'         , 'CanRead'                , 4            ),
    (2       , N'ProjectDossier'         , 'CanRead'                , 5            ),
    (2       , N'ProjectDossier'         , 'CanRead'                , 6            ),
    (2       , N'ProjectDossier'         , 'CanRead'                , 7            ),

--test1
    (3       , N'UserAdmin'     , 'CanAdministrate'                , NULL         ),
    (3       , N'UserAdmin'     , 'CanControl'                     , NULL         ),

    (3       , N'Company'       , 'CanRead'                        , NULL         ),
    (3       , N'Company'       , 'CanWrite'                       , NULL         ),

    (3       , N'Registration'  , 'CanRead'                        , NULL         ),

    (3       , N'OperationalMap', 'CanRead'                        , 1            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 1            ),
    (3       , N'OperationalMap', 'CanRead'                        , 2            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 2            ),
    (3       , N'OperationalMap', 'CanRead'                        , 3            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 3            ),
    (3       , N'OperationalMap', 'CanRead'                        , 4            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 4            ),
    (3       , N'OperationalMap', 'CanRead'                        , 5            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 5            ),
    (3       , N'OperationalMap', 'CanRead'                        , 6            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 6            ),
    (3       , N'OperationalMap', 'CanRead'                        , 7            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 7            ),
    (3       , N'OperationalMap', 'CanRead'                        , 8            ),
    (3       , N'OperationalMap', 'CanWrite'                       , 8            ),

    (3       , N'Procedure'     , 'CanRead'                        , 1            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (3       , N'Procedure'     , 'CanRead'                        , 2            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (3       , N'Procedure'     , 'CanRead'                        , 3            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (3       , N'Procedure'     , 'CanRead'                        , 4            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (3       , N'Procedure'     , 'CanRead'                        , 5            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (3       , N'Procedure'     , 'CanRead'                        , 6            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (3       , N'Procedure'     , 'CanRead'                        , 7            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 7            ),
    (3       , N'Procedure'     , 'CanRead'                        , 8            ),
    (3       , N'Procedure'     , 'CanWrite'                       , 8            ),
    (3       , N'Procedure'     , 'CanCheck'                       , 8            ),
    (3       , N'Procedure'     , 'CanDelete'                      , 8            ),

    (3       , N'Project'       , 'CanRead'                        , 1            ),
    (3       , N'Project'       , 'CanRegister'                    , 1            ),
    (3       , N'Project'       , 'CanRead'                        , 2            ),
    (3       , N'Project'       , 'CanRegister'                    , 2            ),
    (3       , N'Project'       , 'CanRead'                        , 3            ),
    (3       , N'Project'       , 'CanRegister'                    , 3            ),
    (3       , N'Project'       , 'CanRead'                        , 4            ),
    (3       , N'Project'       , 'CanRegister'                    , 4            ),
    (3       , N'Project'       , 'CanRead'                        , 5            ),
    (3       , N'Project'       , 'CanRegister'                    , 5            ),
    (3       , N'Project'       , 'CanRead'                        , 6            ),
    (3       , N'Project'       , 'CanRegister'                    , 6            ),
    (3       , N'Project'       , 'CanRead'                        , 7            ),
    (3       , N'Project'       , 'CanRegister'                    , 7            ),
    (3       , N'Project'       , 'CanRead'                        , 8            ),
    (3       , N'Project'       , 'CanRegister'                    , 8            ),

    --adminSesii
    (5       , N'Company'       , 'CanRead'                        , NULL         ),
    (5       , N'Company'       , 'CanWrite'                       , NULL         ),

    (5       , N'Registration'  , 'CanRead'                        , NULL         ),

    (5       , N'OperationalMap', 'CanRead'                        , 1            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 1            ),
    (5       , N'OperationalMap', 'CanRead'                        , 2            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 2            ),
    (5       , N'OperationalMap', 'CanRead'                        , 3            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 3            ),
    (5       , N'OperationalMap', 'CanRead'                        , 4            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 4            ),
    (5       , N'OperationalMap', 'CanRead'                        , 5            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 5            ),
    (5       , N'OperationalMap', 'CanRead'                        , 6            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 6            ),
    (5       , N'OperationalMap', 'CanRead'                        , 7            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 7            ),
    (5       , N'OperationalMap', 'CanRead'                        , 8            ),
    (5       , N'OperationalMap', 'CanWrite'                       , 8            ),

    (5       , N'Procedure'     , 'CanRead'                        , 1            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (5       , N'Procedure'     , 'CanRead'                        , 2            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (5       , N'Procedure'     , 'CanRead'                        , 3            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (5       , N'Procedure'     , 'CanRead'                        , 4            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (5       , N'Procedure'     , 'CanRead'                        , 5            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (5       , N'Procedure'     , 'CanRead'                        , 6            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (5       , N'Procedure'     , 'CanRead'                        , 7            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 7            ),
    (5       , N'Procedure'     , 'CanRead'                        , 8            ),
    (5       , N'Procedure'     , 'CanWrite'                       , 8            ),
    (5       , N'Procedure'     , 'CanCheck'                       , 8            ),
    (5       , N'Procedure'     , 'CanDelete'                      , 8            ),

    (5       , N'Project'       , 'CanRead'                        , 1            ),
    (5       , N'Project'       , 'CanRegister'                    , 1            ),
    (5       , N'Project'       , 'CanRead'                        , 2            ),
    (5       , N'Project'       , 'CanRegister'                    , 2            ),
    (5       , N'Project'       , 'CanRead'                        , 3            ),
    (5       , N'Project'       , 'CanRegister'                    , 3            ),
    (5       , N'Project'       , 'CanRead'                        , 4            ),
    (5       , N'Project'       , 'CanRegister'                    , 4            ),
    (5       , N'Project'       , 'CanRead'                        , 5            ),
    (5       , N'Project'       , 'CanRegister'                    , 5            ),
    (5       , N'Project'       , 'CanRead'                        , 6            ),
    (5       , N'Project'       , 'CanRegister'                    , 6            ),
    (5       , N'Project'       , 'CanRead'                        , 7            ),
    (5       , N'Project'       , 'CanRegister'                    , 7            ),
    (5       , N'Project'       , 'CanRead'                        , 8            ),
    (5       , N'Project'       , 'CanRegister'                    , 8            ),

    (5       , N'EvalSession'   , 'CanAdministrate'                , 1            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 2            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 3            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 4            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 5            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 6            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 7            ),
    (5       , N'EvalSession'   , 'CanAdministrate'                , 8            ),

    --adminSesiq
    (6       , N'Company'       , 'CanRead'                        , NULL         ),
    (6       , N'Company'       , 'CanWrite'                       , NULL         ),

    (6       , N'Registration'  , 'CanRead'                        , NULL         ),

    (6       , N'OperationalMap', 'CanRead'                        , 1            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 1            ),
    (6       , N'OperationalMap', 'CanRead'                        , 2            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 2            ),
    (6       , N'OperationalMap', 'CanRead'                        , 3            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 3            ),
    (6       , N'OperationalMap', 'CanRead'                        , 4            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 4            ),
    (6       , N'OperationalMap', 'CanRead'                        , 5            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 5            ),
    (6       , N'OperationalMap', 'CanRead'                        , 6            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 6            ),
    (6       , N'OperationalMap', 'CanRead'                        , 7            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 7            ),
    (6       , N'OperationalMap', 'CanRead'                        , 8            ),
    (6       , N'OperationalMap', 'CanWrite'                       , 8            ),

    (6       , N'Procedure'     , 'CanRead'                        , 1            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (6       , N'Procedure'     , 'CanRead'                        , 2            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (6       , N'Procedure'     , 'CanRead'                        , 3            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (6       , N'Procedure'     , 'CanRead'                        , 4            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (6       , N'Procedure'     , 'CanRead'                        , 5            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (6       , N'Procedure'     , 'CanRead'                        , 6            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (6       , N'Procedure'     , 'CanRead'                        , 7            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 7            ),
    (6       , N'Procedure'     , 'CanRead'                        , 8            ),
    (6       , N'Procedure'     , 'CanWrite'                       , 8            ),
    (6       , N'Procedure'     , 'CanCheck'                       , 8            ),
    (6       , N'Procedure'     , 'CanDelete'                      , 8            ),

    (6       , N'Project'       , 'CanRead'                        , 1            ),
    (6       , N'Project'       , 'CanRegister'                    , 1            ),
    (6       , N'Project'       , 'CanRead'                        , 2            ),
    (6       , N'Project'       , 'CanRegister'                    , 2            ),
    (6       , N'Project'       , 'CanRead'                        , 3            ),
    (6       , N'Project'       , 'CanRegister'                    , 3            ),
    (6       , N'Project'       , 'CanRead'                        , 4            ),
    (6       , N'Project'       , 'CanRegister'                    , 4            ),
    (6       , N'Project'       , 'CanRead'                        , 5            ),
    (6       , N'Project'       , 'CanRegister'                    , 5            ),
    (6       , N'Project'       , 'CanRead'                        , 6            ),
    (6       , N'Project'       , 'CanRegister'                    , 6            ),
    (6       , N'Project'       , 'CanRead'                        , 7            ),
    (6       , N'Project'       , 'CanRegister'                    , 7            ),
    (6       , N'Project'       , 'CanRead'                        , 8            ),
    (6       , N'Project'       , 'CanRegister'                    , 8            ),

    (6       , N'EvalSession'   , 'CanEvaluate'                    , 1            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 2            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 3            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 4            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 5            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 6            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 7            ),
    (6       , N'EvalSession'   , 'CanEvaluate'                    , 8            ),

    --ocenitel
    (7       , N'Company'       , 'CanRead'                        , NULL         ),
    (7       , N'Company'       , 'CanWrite'                       , NULL         ),

    (7       , N'Registration'  , 'CanRead'                        , NULL         ),

    (7       , N'OperationalMap', 'CanRead'                        , 1            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 1            ),
    (7       , N'OperationalMap', 'CanRead'                        , 2            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 2            ),
    (7       , N'OperationalMap', 'CanRead'                        , 3            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 3            ),
    (7       , N'OperationalMap', 'CanRead'                        , 4            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 4            ),
    (7       , N'OperationalMap', 'CanRead'                        , 5            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 5            ),
    (7       , N'OperationalMap', 'CanRead'                        , 6            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 6            ),
    (7       , N'OperationalMap', 'CanRead'                        , 7            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 7            ),
    (7       , N'OperationalMap', 'CanRead'                        , 8            ),
    (7       , N'OperationalMap', 'CanWrite'                       , 8            ),

    (7       , N'Procedure'     , 'CanRead'                        , 1            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (7       , N'Procedure'     , 'CanRead'                        , 2            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (7       , N'Procedure'     , 'CanRead'                        , 3            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (7       , N'Procedure'     , 'CanRead'                        , 4            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (7       , N'Procedure'     , 'CanRead'                        , 5            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (7       , N'Procedure'     , 'CanRead'                        , 6            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (7       , N'Procedure'     , 'CanRead'                        , 7            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 7            ),
    (7       , N'Procedure'     , 'CanRead'                        , 8            ),
    (7       , N'Procedure'     , 'CanWrite'                       , 8            ),
    (7       , N'Procedure'     , 'CanCheck'                       , 8            ),
    (7       , N'Procedure'     , 'CanDelete'                      , 8            ),

    (7       , N'Project'       , 'CanRead'                        , 1            ),
    (7       , N'Project'       , 'CanRegister'                    , 1            ),
    (7       , N'Project'       , 'CanRead'                        , 2            ),
    (7       , N'Project'       , 'CanRegister'                    , 2            ),
    (7       , N'Project'       , 'CanRead'                        , 3            ),
    (7       , N'Project'       , 'CanRegister'                    , 3            ),
    (7       , N'Project'       , 'CanRead'                        , 4            ),
    (7       , N'Project'       , 'CanRegister'                    , 4            ),
    (7       , N'Project'       , 'CanRead'                        , 5            ),
    (7       , N'Project'       , 'CanRegister'                    , 5            ),
    (7       , N'Project'       , 'CanRead'                        , 6            ),
    (7       , N'Project'       , 'CanRegister'                    , 6            ),
    (7       , N'Project'       , 'CanRead'                        , 7            ),
    (7       , N'Project'       , 'CanRegister'                    , 7            ),
    (7       , N'Project'       , 'CanRead'                        , 8            ),
    (7       , N'Project'       , 'CanRegister'                    , 8            ),

    (7       , N'EvalSession'   , 'CanEvaluate'                    , 1            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 2            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 3            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 4            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 5            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 6            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 7            ),
    (7       , N'EvalSession'   , 'CanEvaluate'                    , 8            ),

    -- pomoshtnik ocenitel
    (8       , N'Company'       , N'CanRead'                       , NULL         ),
    (8       , N'Company'       , N'CanWrite'                      , NULL         ),

    (8       , N'Registration'  , 'CanRead'                        , NULL         ),

    (8       , N'OperationalMap', N'CanRead'                       , 1            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 1            ),
    (8       , N'OperationalMap', N'CanRead'                       , 2            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 2            ),
    (8       , N'OperationalMap', N'CanRead'                       , 3            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 3            ),
    (8       , N'OperationalMap', N'CanRead'                       , 4            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 4            ),
    (8       , N'OperationalMap', N'CanRead'                       , 5            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 5            ),
    (8       , N'OperationalMap', N'CanRead'                       , 6            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 6            ),
    (8       , N'OperationalMap', N'CanRead'                       , 7            ),
    (8       , N'OperationalMap', N'CanWrite'                      , 7            ),
    (8       , N'OperationalMap', 'CanRead'                        , 8            ),
    (8       , N'OperationalMap', 'CanWrite'                       , 8            ),

    (8       , N'Procedure'     , 'CanRead'                        , 1            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 1            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 1            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 1            ),
    (8       , N'Procedure'     , 'CanRead'                        , 2            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 2            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 2            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 2            ),
    (8       , N'Procedure'     , 'CanRead'                        , 3            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 3            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 3            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 3            ),
    (8       , N'Procedure'     , 'CanRead'                        , 4            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 4            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 4            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 4            ),
    (8       , N'Procedure'     , 'CanRead'                        , 5            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 5            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 5            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 5            ),
    (8       , N'Procedure'     , 'CanRead'                        , 6            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 6            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 6            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 6            ),
    (8       , N'Procedure'     , 'CanRead'                        , 7            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 7            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 7            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 7            ),
    (8       , N'Procedure'     , 'CanRead'                        , 8            ),
    (8       , N'Procedure'     , 'CanWrite'                       , 8            ),
    (8       , N'Procedure'     , 'CanCheck'                       , 8            ),
    (8       , N'Procedure'     , 'CanDelete'                      , 8            ),

    (8       , N'Project'       , 'CanRead'                        , 1            ),
    (8       , N'Project'       , 'CanRegister'                    , 1            ),
    (8       , N'Project'       , 'CanRead'                        , 2            ),
    (8       , N'Project'       , 'CanRegister'                    , 2            ),
    (8       , N'Project'       , 'CanRead'                        , 3            ),
    (8       , N'Project'       , 'CanRegister'                    , 3            ),
    (8       , N'Project'       , 'CanRead'                        , 4            ),
    (8       , N'Project'       , 'CanRegister'                    , 4            ),
    (8       , N'Project'       , 'CanRead'                        , 5            ),
    (8       , N'Project'       , 'CanRegister'                    , 5            ),
    (8       , N'Project'       , 'CanRead'                        , 6            ),
    (8       , N'Project'       , 'CanRegister'                    , 6            ),
    (8       , N'Project'       , 'CanRead'                        , 7            ),
    (8       , N'Project'       , 'CanRegister'                    , 7            ),
    (8       , N'Project'       , 'CanRead'                        , 8            ),
    (8       , N'Project'       , 'CanRegister'                    , 8            ),

    (8       , N'EvalSession'   , N'CanEvaluate'                   , 1            ),
    (8       , N'EvalSession'   , N'CanEvaluate'                   , 2            ),
    (8       , N'EvalSession'   , N'CanEvaluate'                   , 3            ),
    (8       , N'EvalSession'   , N'CanEvaluate'                   , 4            ),
    (8       , N'EvalSession'   , N'CanEvaluate'                   , 5            ),
    (8       , N'EvalSession'   , N'CanEvaluate'                   , 6            ),
    (8       , N'EvalSession'   , N'CanEvaluate'                   , 7            )
GO
