//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.RegiX.Rio.AVBULSTAT
{




	[XmlType(TypeName="SubjectPropAccountingRecordForm",Namespace="http://www.bulstat.bg/SubjectPropAccountingRecordForm"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class SubjectPropAccountingRecordForm : Eumis.RegiX.Rio.AVBULSTAT.Entry
	{

		[XmlElement(Type=typeof(Eumis.RegiX.Rio.AVBULSTAT.NomenclatureEntry),ElementName="Form",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://www.bulstat.bg/SubjectPropAccountingRecordForm")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.RegiX.Rio.AVBULSTAT.NomenclatureEntry __Form;
		
		[XmlIgnore]
		public Eumis.RegiX.Rio.AVBULSTAT.NomenclatureEntry Form
		{
			get {return __Form;}
			set {__Form = value;}
		}

		public SubjectPropAccountingRecordForm() : base()
		{
		}
	}
}
