//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.RegiX.Rio.AVBULSTAT
{


	[Serializable]
	public enum OperationType
	{
		[XmlEnum(Name="register")] register,
		[XmlEnum(Name="erase")] erase
	}



	[XmlType(TypeName="SubscriptionElement",Namespace="http://www.bulstat.bg/SubscriptionElement"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class SubscriptionElement : Eumis.RegiX.Rio.AVBULSTAT.Entry
	{

		[XmlElement(ElementName="OperationType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://www.bulstat.bg/SubscriptionElement")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public OperationType __OperationType;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __OperationTypeSpecified;
		
		[XmlIgnore]
		public OperationType OperationType
		{ 
			get { return __OperationType; }
			set { __OperationType = value; __OperationTypeSpecified = true; }
		}

		public SubscriptionElement() : base()
		{
		}
	}
}
