//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccessibilityPolicy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessibilityPolicy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Views.Default.App_LocalResources.AccessibilityPolicy", typeof(AccessibilityPolicy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декларация за достъпност.
        /// </summary>
        public static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициатива за уеб достъпност.
        /// </summary>
        public static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3C Стандарти.
        /// </summary>
        public static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изключения.
        /// </summary>
        public static string Header4 {
            get {
                return ResourceManager.GetString("Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дирекция „Централно координационно звено“ към Администрацията на Министерски съвет се ангажира да осигури достъпност на СУНИ за максимално широка група потребители независимо от използваните технологии и умения..
        /// </summary>
        public static string Paragraph11 {
            get {
                return ResourceManager.GetString("Paragraph11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ние активно работим за подобряване на достъпността и използваемостта на ИСУН и в тази си дейност се придържаме към наличните стандарти и добри практики..
        /// </summary>
        public static string Paragraph12 {
            get {
                return ResourceManager.GetString("Paragraph12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да отговорим на поставените изисквания и критерии за ниво на достъпност, поставени от Европейската комисия относно интернет страниците на публичната администрация, и същевременно да посрещнем изискванията на текущите интернет технологии, ще се придържаме към стандартите на WCAG 2.0 и ниво на съответствие &quot;Двойно-A&quot;..
        /// </summary>
        public static string Paragraph13 {
            get {
                return ResourceManager.GetString("Paragraph13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СУНИ ще се опитва да покрие ниво на достъпност двойно-А според последните стандарти на World Wide Web Consortium - Web Content Accessibility Guidelines 2.0 (WCAG 2.0), като използва най-добрите практики и техники..
        /// </summary>
        public static string Paragraph21 {
            get {
                return ResourceManager.GetString("Paragraph21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCAG 2.0 обяснява как съдържанието в интернет страниците да бъде направено по-достъпно за хора с увреждания. Изпълнението на насоките ще помогне на повече хора да се чувстват удобно и да се възползват от предимствата на интернет..
        /// </summary>
        public static string Paragraph22 {
            get {
                return ResourceManager.GetString("Paragraph22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СУНИ е изградена с код, съвместим с W3C стандартите за XHTML и CSS. Кодът се възпроизвежда коректно в наличните към момента интернет браузъри, а използването на W3C стандартите гарантира съвместимост и с бъдещите нови или подобрени браузъри..
        /// </summary>
        public static string Paragraph31 {
            get {
                return ResourceManager.GetString("Paragraph31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макар да се стремим да осигурим съвместимост с наличните стандарти за достъпност, това не винаги е възможно във всеки един аспект. Браузърите и техниките за разработка и достъп до интернет се развиват много бързо и понякога някои от стандартните изисквания за достъпност стават излишни. В тази светлина ние непрекъснато развиваме технологично СУНИ с оглед постигането на високи стандарти на достъпност и използваемост на съдържанието в него..
        /// </summary>
        public static string Paragraph41 {
            get {
                return ResourceManager.GetString("Paragraph41", resourceCulture);
            }
        }
    }
}
