SET IDENTITY_INSERT [dbo].[MapRegions] ON 
GO

INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (1, 1, N'Петрич', N'Petrich',N'Petrich', 5, 20)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (2, 1, N'Сандански', N'Sandanski',N'Sandanski', 5, 22)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (3, 1, N'Струмяни', N'Strumyani',N'Strumyani', 5, 25)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (4, 1, N'Кресна', N'Kresna',N'Kresna', 5, 19)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (5, 1, N'Банско', N'Bansko',N'Bansko', 5, 14)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (6, 1, N'Гоце Делчев', N'Gotse Delchev',N'Gotse Delchev', 5, 17)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (7, 1, N'Гърмен', N'Garmen',N'Garmen', 5, 18)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (8, 1, N'Сатовча', N'Satovcha',N'Satovcha', 5, 23)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (9, 1, N'Хаджидимово', N'Hadzhidimovo',N'Hadzhidimovo', 5, 26)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (10, 1, N'Белица', N'Belica',N'Belica', 5, 15)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (11, 1, N'Разлог', N'Razlog',N'Razlog', 5, 21)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (12, 1, N'Симитли', N'Simitli',N'Simitli', 5, 24)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (13, 1, N'Благоевград', N'Blagoevgrad',N'Blagoevgrad', 5, 16)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (14, 1, N'Якоруда', N'Yakorouda',N'Yakorouda', 5, 27)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (15, 888, N'Югозападен', N'Yugozapaden',N'Southwest', 3, 5)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (16, 888, N'Югоизточен', N'Yugoiztochen',N'Southeast', 3, 4)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (17, 888, N'Североизточен', N'Severoiztochen',N'Northeast', 3, 3)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (18, 888, N'Северен централен', N'Severen tsentralen',N'North Central', 3, 2)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (19, 888, N'Северозападен', N'Severozapaden',N'Northwest', 3, 1)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (20, 888, N'Южен централен', N'Yuzhen tsentralen',N'South Central', 3, 6)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (21, 3, N'Средец', N'Sredets',N'Sredets', 5, 3)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (22, 3, N'Созопол', N'Sozopol',N'Sozopol', 5, 11)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (23, 3, N'Приморско', N'Primorsko',N'Primorsko', 5, 13)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (24, 3, N'Царево', N'Tsarevo',N'Tsarevo', 5, 7)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (25, 3, N'Малко Търново', N'Malko Tarnovo',N'Malko Tarnovo', 5, 6)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (26, 3, N'Камено', N'Kameno',N'Kameno', 5, 4)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (27, 3, N'Несебър', N'Nesebar',N'Nesebar', 5, 8)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (28, 3, N'Карнобат', N'Karnobat',N'Karnobat', 5, 5)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (29, 3, N'Айтос', N'Aytos',N'Aytos', 5, 1)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (30, 3, N'Поморие', N'Pomorie',N'Pomorie', 5, 9)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (31, 3, N'Руен', N'Ruen',N'Ruen', 5, 10)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (32, 3, N'Сунгурларе', N'Sungurlare',N'Sungurlare', 5, 12)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (33, 3, N'Бургас', N'Burgas',N'Burgas', 5, 2)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (34, 4, N'Тервел', N'Tervel',N'Tervel', 5, 33)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (35, 4, N'Добрич', N'Dobrich',N'Dobrich', 5, 34)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (36, 4, N'Добричка', N'Dobrichka',N'Dobrichka', 5, 30)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (37, 4, N'Балчик', N'Balchik',N'Balchik', 5, 28)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (38, 4, N'Каварна', N'Kavarna',N'Kavarna', 5, 31)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (39, 4, N'Крушари', N'Krushari',N'Krushari', 5, 32)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (40, 4, N'Генерал Тошево', N'General Toshevo',N'General Toshevo', 5, 29)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (41, 4, N'Шабла', N'Shabla',N'Shabla', 5, 35)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (42, 5, N'Трявна', N'Tryavna',N'Tryavna', 5, 39)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (43, 5, N'Габрово', N'Gabrovo',N'Gabrovo', 5, 36)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (44, 5, N'Севлиево', N'Sevlievo',N'Sevlievo', 5, 38)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (45, 5, N'Дряново', N'Dryanovo',N'Dryanovo', 5, 37)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (46, 6, N'Ивайловград', N'Ivaylovgrad',N'Ivaylovgrad', 5, 41)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (47, 6, N'Маджарово', N'Madzharovo',N'Madzharovo', 5, 43)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (48, 6, N'Любимец', N'Lyubimets',N'Lyubimets', 5, 42)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (49, 6, N'Свиленград', N'Svilengrad',N'Svilengrad', 5, 45)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (50, 6, N'Тополовград', N'Topolovgrad',N'Topolovgrad', 5, 48)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (51, 6, N'Стамболово', N'Stambolovo',N'Stambolovo', 5, 47)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (52, 6, N'Харманли', N'Harmanli',N'Harmanli', 5, 49)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (53, 6, N'Симеоновград', N'Simeonovgrad',N'Simeonovgrad', 5, 46)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (54, 6, N'Хасково', N'Haskovo',N'Haskovo', 5, 50)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (55, 6, N'Минерални бани', N'Mineral bani',N'Mineral bani', 5, 44)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (56, 6, N'Димитровград', N'Dimitrovgrad',N'Dimitrovgrad', 5, 40)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (57, 7, N'Кирково', N'Kirkovo',N'Kirkovo', 5, 67)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (58, 7, N'Крумовград', N'Krumovgrad',N'Krumovgrad', 5, 68)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (59, 7, N'Момчилград', N'Momchilgrad',N'Momchilgrad', 5, 70)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (60, 7, N'Джебел', N'Dzhebel',N'Dzhebel', 5, 66)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (61, 7, N'Ардино', N'Ardino',N'Ardino', 5, 65)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (62, 7, N'Черноочене', N'Chernoochene',N'Chernoochene', 5, 71)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (63, 7, N'Кърджали', N'Kardzhali',N'Kardzhali', 5, 69)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (64, 8, N'Трекляно', N'Treklyano',N'Treklyano', 5, 64)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (65, 8, N'Кюстендил', N'Kyustendil',N'Kyustendil', 5, 59)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (66, 8, N'Невестино', N'Nevestino',N'Nevestino', 5, 60)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (67, 8, N'Кочериново', N'Kocherinovo',N'Kocherinovo', 5, 58)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (68, 8, N'Бобошево', N'Boboshevo',N'Boboshevo', 5, 57)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (69, 8, N'Дупница', N'Dupnitsa',N'Dupnitsa', 5, 63)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (70, 8, N'Бобов дол', N'Bobov Dol',N'Bobov Dol', 5, 56)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (71, 8, N'Сапарева Баня', N'Sapareva Banya',N'Sapareva Banya', 5, 62)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (72, 8, N'Рила', N'Rila',N'Rila', 5, 61)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (73, 9, N'Ябланица', N'Yablanica',N'Yablanica', 5, 79)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (74, 9, N'Тетевен', N'Teteven',N'Teteven', 5, 76)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (75, 9, N'Троян', N'Troyan',N'Troyan', 5, 77)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (76, 9, N'Ловеч', N'Lovech',N'Lovech', 5, 74)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (77, 9, N'Летница', N'Letnitsa',N'Letnitsa', 5, 73)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (78, 9, N'Априлци', N'Apriltsi',N'Apriltsi', 5, 72)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (79, 9, N'Угърчин', N'Ugarchin',N'Ugarchin', 5, 78)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (80, 9, N'Луковит', N'Lukovit',N'Lukovit', 5, 75)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (81, 10, N'Берковица', N'Berkovitsa',N'Berkovitsa', 5, 80)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (82, 10, N'Бойчиновци', N'Boychinovtsi',N'Boychinovtsi', 5, 81)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (83, 10, N'Брусарци', N'Brusartsi',N'Brusartsi', 5, 82)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (84, 10, N'Вълчедръм', N'Valchedram',N'Valchedram', 5, 83)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (85, 10, N'Вършец', N'Varshets',N'Varshets', 5, 84)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (86, 10, N'Георги Дамяново', N'Georgi Damyanovo',N'Georgi Damyanovo', 5, 85)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (87, 10, N'Лом', N'Lom',N'Lom', 5, 86)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (88, 10, N'Медковец', N'Medkovets',N'Medkovets', 5, 87)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (89, 10, N'Монтана', N'Montana',N'Montana', 5, 88)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (90, 10, N'Чипровци', N'Chiprovtsi',N'Chiprovtsi', 5, 89)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (91, 10, N'Якимово', N'Yakimovo',N'Yakimovo', 5, 90)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (92, 11, N'Габрово', N'Gabrovo',N'Gabrovo', 4, 7)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (93, 11, N'Велико Търново', N'Veliko Tarnovo',N'Veliko Tarnovo', 4, 4)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (94, 11, N'Русе', N'Ruse',N'Ruse', 4, 18)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (95, 11, N'Разград', N'Razgrad',N'Razgrad', 4, 17)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (96, 11, N'Силистра', N'Silistra',N'Silistra', 4, 19)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (97, 12, N'Търговище', N'Targovishte',N'Targovishte', 4, 25)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (98, 12, N'Шумен', N'Shumen',N'Shumen', 4, 27)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (99, 12, N'Варна', N'Varna',N'Varna', 4, 3)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (100, 12, N'Добрич', N'Dobrich',N'Dobrich', 4, 8)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (101, 13, N'Ловеч', N'Lovech',N'Lovech', 4, 11)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (102, 13, N'Плевен', N'Pleven',N'Pleven', 4, 15)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (103, 13, N'Враца', N'Vratsa',N'Vratsa', 4, 6)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (104, 13, N'Монтана', N'Montana',N'Montana', 4, 12)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (105, 13, N'Видин', N'Vidin',N'Vidin', 4, 5)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (106, 14, N'Велинград', N'Velingrad',N'Velingrad', 5, 94)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (107, 14, N'Белово', N'Belovo',N'Belovo', 5, 92)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (108, 14, N'Септември', N'Septemvri',N'Septemvri', 5, 100)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (109, 14, N'Ракитово', N'Rakitovo',N'Rakitovo', 5, 99)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (110, 14, N'Батак', N'Batak',N'Batak', 5, 91)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (111, 14, N'Пещера', N'Peshtera',N'Peshtera', 5, 98)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (112, 14, N'Пазарджик', N'Pazardzhik',N'Pazardzhik', 5, 96)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (113, 14, N'Брацигово', N'Bratsigovo',N'Bratsigovo', 5, 93)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (114, 14, N'Лесичово', N'Lesichovo',N'Lesichovo', 5, 95)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (115, 14, N'Панагюрище', N'Panagyurishte',N'Panagyurishte', 5, 97)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (116, 14, N'Стрелча', N'Strelcha',N'Strelcha', 5, 101)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (117, 15, N'Трън', N'Tran',N'Tran', 5, 125)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (118, 15, N'Земен', N'Zemen',N'Zemen', 5, 121)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (119, 15, N'Ковачевци', N'Kovachevtsi',N'Kovachevtsi', 5, 122)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (120, 15, N'Радомир', N'Radomir',N'Radomir', 5, 124)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (121, 15, N'Перник', N'Pernik',N'Pernik', 5, 123)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (122, 15, N'Брезник', N'Breznik',N'Breznik', 5, 120)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (123, 16, N'Кнежа', N'Knezha',N'Knezha', 5, 136)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (124, 16, N'Червен Бряг', N'Cherven bryag',N'Cherven bryag', 5, 135)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (125, 16, N'Искър', N'Iskar',N'Iskar', 5, 132)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (126, 16, N'Долна Митрополия', N'Dolna Mitropolia',N'Dolna Mitropolia', 5, 128)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (127, 16, N'Гулянци', N'Gulyantsi',N'Gulyantsi', 5, 127)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (128, 16, N'Долни Дъбник', N'Dolni Dabnik',N'Dolni Dabnik', 5, 129)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (129, 16, N'Плевен', N'Pleven',N'Pleven', 5, 133)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (130, 16, N'Пордим', N'Pordim',N'Pordim', 5, 134)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (131, 16, N'Левски', N'Levski',N'Levski', 5, 130)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (132, 16, N'Никопол', N'Nikopol',N'Nikopol', 5, 131)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (133, 16, N'Белене', N'Belene',N'Belene', 5, 126)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (134, 17, N'Кричим', N'Krichim',N'Krichim', 5, 115)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (135, 17, N'Стамболийски', N'Stamboliyski',N'Stamboliyski', 5, 117)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (136, 17, N'Перущица', N'Perushtitsa',N'Perushtitsa', 5, 116)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (137, 17, N'Куклен', N'Kuklen',N'Kuklen', 5, 118)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (138, 17, N'Родопи', N'Rodopi',N'Rodopi', 5, 111)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (139, 17, N'Пловдив', N'Plovdiv',N'Plovdiv', 5, 108)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (140, 17, N'Садово', N'Sadovo',N'Sadovo', 5, 112)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (141, 17, N'Асеновград', N'Asenovgrad',N'Asenovgrad', 5, 102)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (142, 17, N'Лъки', N'Laki',N'Laki', 5, 106)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (143, 17, N'Първомай', N'Parvomay',N'Parvomay', 5, 109)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (144, 17, N'Марица', N'Maritsa',N'Maritsa', 5, 107)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (145, 17, N'Раковски', N'Rakovski',N'Rakovski', 5, 110)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (146, 17, N'Съединение', N'Saedinenie',N'Saedinenie', 5, 113)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (147, 17, N'Калояново', N'Kaloyanovo',N'Kaloyanovo', 5, 104)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (148, 17, N'Брезово', N'Brezovo',N'Brezovo', 5, 103)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (149, 17, N'Хисаря', N'Hisar',N'Hisar', 5, 114)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (150, 17, N'Карлово', N'Karlovo',N'Karlovo', 5, 105)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (151, 18, N'Разград', N'Razgrad',N'Razgrad', 5, 141)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (152, 18, N'Лозница', N'Loznitsa',N'Loznitsa', 5, 140)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (153, 18, N'Цар Калоян', N'Tsar Kaloyan',N'Tsar Kaloyan', 5, 143)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (154, 18, N'Самуил', N'Samuil',N'Samuil', 5, 142)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (155, 18, N'Исперих', N'Isperih',N'Isperih', 5, 138)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (156, 18, N'Завет', N'Zavet',N'Zavet', 5, 137)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (157, 18, N'Кубрат', N'Kubrat',N'Kubrat', 5, 139)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (158, 19, N'Ценово', N'Tsenovo',N'Tsenovo', 5, 151)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (159, 19, N'Бяла', N'Byala',N'Byala', 5, 145)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (160, 19, N'Две Могили', N'Dve mogili',N'Dve mogili', 5, 147)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (161, 19, N'Борово', N'Borovo',N'Borovo', 5, 144)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (162, 19, N'Иваново', N'Ivanovo',N'Ivanovo', 5, 148)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (163, 19, N'Русе', N'Ruse',N'Ruse', 5, 149)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (164, 19, N'Сливо Поле', N'Slivo Pole',N'Slivo Pole', 5, 150)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (165, 19, N'Ветово', N'Vetovo',N'Vetovo', 5, 146)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (166, 20, N'Смядово', N'Smiyadovo',N'Smiyadovo', 5, 182)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (167, 20, N'Върбица', N'Varbitsa',N'Varbitsa', 5, 175)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (168, 20, N'Велики Преслав', N'Veliki Preslav',N'Veliki Preslav', 5, 181)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (169, 20, N'Шумен', N'Shumen',N'Shumen', 5, 183)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (170, 20, N'Каспичан', N'Kaspichan',N'Kaspichan', 5, 178)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (171, 20, N'Хитрино', N'Hitrino',N'Hitrino', 5, 176)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (172, 20, N'Венец', N'Venets',N'Venets', 5, 174)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (173, 20, N'Каолиново', N'Kaolinovo',N'Kaolinovo', 5, 177)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (174, 20, N'Никола Козлево', N'Nicola Kozlevo',N'Nicola Kozlevo', 5, 179)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (175, 20, N'Нови пазар', N'Novi Pazar',N'Novi Pazar', 5, 180)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (176, 21, N'Тутракан', N'Tutrakan',N'Tutrakan', 5, 190)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (177, 21, N'Главиница', N'Glavinica',N'Glavinica', 5, 185)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (178, 21, N'Ситово', N'Sitovo',N'Sitovo', 5, 189)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (179, 21, N'Силистра', N'Silistra',N'Silistra', 5, 188)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (180, 21, N'Дулово', N'Dulovo',N'Dulovo', 5, 186)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (181, 21, N'Алфатар', N'Alfatar',N'Alfatar', 5, 184)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (182, 21, N'Кайнарджа', N'Kaynardzha',N'Kaynardzha', 5, 187)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (183, 22, N'Нова Загора', N'Nova Zagora',N'Nova Zagora', 5, 192)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (184, 22, N'Твърдица', N'Tvarditsa',N'Tvarditsa', 5, 194)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (185, 22, N'Сливен', N'Sliven',N'Sliven', 5, 193)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (186, 22, N'Котел', N'Kotel',N'Kotel', 5, 191)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (187, 23, N'Доспат', N'Dospat',N'Dospat', 5, 198)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (188, 23, N'Борино', N'Borino',N'Borino', 5, 196)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (189, 23, N'Девин', N'Devin',N'Devin', 5, 197)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (190, 23, N'Чепеларе', N'Chepelare',N'Chepelare', 5, 204)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (191, 23, N'Смолян', N'Smolyan',N'Smolyan', 5, 203)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (192, 23, N'Рудозем', N'Rudozem',N'Rudozem', 5, 202)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (193, 23, N'Златоград', N'Zlatograd',N'Zlatograd', 5, 199)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (194, 23, N'Неделино', N'Nedelino',N'Nedelino', 5, 201)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (195, 23, N'Мадан', N'Madan',N'Madan', 5, 200)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (196, 23, N'Баните', N'Banite',N'Banite', 5, 195)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (197, 24, N'Драгоман', N'Dragoman',N'Dragoman', 5, 156)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (198, 24, N'Сливница', N'Slivnitsa',N'Slivnitsa', 5, 166)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (199, 24, N'Божурище', N'Bozhurishte',N'Bozhurishte', 5, 152)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (200, 24, N'Столична', N'Stolichna',N'Sofia', 5, 205)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (201, 24, N'Самоков', N'Samokov',N'Samokov', 5, 164)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (202, 24, N'Долна Баня', N'Dolna Banya',N'Dolna Banya', 5, 173)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (203, 24, N'Костенец', N'Kostenets',N'Kostenets', 5, 161)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (204, 24, N'Ихтиман', N'Ihtiman',N'Ihtiman', 5, 159)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (205, 24, N'Елин Пелин', N'Elin Pelin',N'Elin Pelin', 5, 157)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (206, 24, N'Горна Малина', N'Gorna Malina',N'Gorna Malina', 5, 155)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (207, 24, N'Мирково', N'Mirkovo',N'Mirkovo', 5, 170)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (208, 24, N'Челопеч', N'Chelopech',N'Chelopech', 5, 172)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (209, 24, N'Чавдар', N'Chavdar',N'Chavdar', 5, 171)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (210, 24, N'Златица', N'Zlatitsa',N'Zlatitsa', 5, 167)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (211, 24, N'Пирдоп', N'Pirdop',N'Pirdop', 5, 169)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (212, 24, N'Антон', N'Anton',N'Anton', 5, 168)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (213, 24, N'Копривщица', N'Koprivshtitsa',N'Koprivshtitsa', 5, 160)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (214, 24, N'Костинброд', N'Kostinbrod',N'Kostinbrod', 5, 162)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (215, 24, N'Годеч', N'Godech',N'Godech', 5, 154)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (216, 24, N'Своге', N'Svoge',N'Svoge', 5, 165)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (217, 24, N'Ботевград', N'Botevgrad',N'Botevgrad', 5, 153)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (218, 24, N'Правец', N'Pravets',N'Pravets', 5, 163)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (219, 24, N'Етрополе', N'Etropole',N'Etropole', 5, 158)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (220, 25, N'Кърджали', N'Kardzhali',N'Kardzhali', 4, 9)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (221, 25, N'Хасково', N'Haskovo',N'Haskovo', 4, 26)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (222, 25, N'Смолян', N'Smolyan',N'Smolyan', 4, 21)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (223, 25, N'Пловдив', N'Plovdiv',N'Plovdiv', 4, 16)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (224, 25, N'Пазарджик', N'Pazardzhik',N'Pazardzhik', 4, 13)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (225, 26, N'Стара Загора', N'Stara Zagora',N'Stara Zagora', 4, 24)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (226, 26, N'Ямбол', N'Yambol',N'Yambol', 4, 28)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (227, 26, N'Сливен', N'Sliven',N'Sliven', 4, 20)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (228, 26, N'Бургас', N'Burgas',N'Burgas', 4, 2)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (229, 27, N'Благоевград', N'Blagoevgrad',N'Blagoevgrad', 4, 1)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (230, 27, N'Кюстендил', N'Kyustendil',N'Kyustendil', 4, 10)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (231, 27, N'Перник', N'Pernik',N'Pernik', 4, 14)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (232, 27, N'София-град', N'Sofia-grad',N'Sofia City', 4, 22)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (233, 27, N'София-област', N'Sofia-oblast',N'Sofia Region', 4, 23)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (234, 28, N'Павел Баня', N'Pavel Banya',N'Pavel Banya', 5, 211)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (235, 28, N'Казанлък', N'Kazanlak',N'Kazanlak', 5, 208)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (236, 28, N'Мъглиж', N'Maglizh',N'Maglizh', 5, 209)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (237, 28, N'Николаево', N'Nikolaevo',N'Nikolaevo', 5, 216)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (238, 28, N'Гурково', N'Gurkovo',N'Gurkovo', 5, 215)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (239, 28, N'Стара Загора', N'Stara Zagora',N'Stara Zagora', 5, 213)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (240, 28, N'Раднево', N'Radnevo',N'Radnevo', 5, 212)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (241, 28, N'Гълъбово', N'Galabovo',N'Galabovo', 5, 207)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (242, 28, N'Опан', N'Opan',N'Opan', 5, 210)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (243, 28, N'Чирпан', N'Chirpan',N'Chirpan', 5, 214)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (244, 28, N'Братя Даскалови', N'Bratya Daskalovi',N'Bratya Daskalovi', 5, 206)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (245, 29, N'Антоново', N'Antonovo',N'Antonovo', 5, 217)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (246, 29, N'Омуртаг', N'Omurtag',N'Omurtag', 5, 218)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (247, 29, N'Търговище', N'Targovishte',N'Targovishte', 5, 221)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (248, 29, N'Попово', N'Popovo',N'Popovo', 5, 220)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (249, 29, N'Опака', N'Opaka',N'Opaka', 5, 219)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (250, 30, N'Дългопол', N'Dalgopol',N'Dalgopol', 5, 231)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (251, 30, N'Долни Чифлик', N'Dolni Chiflik',N'Dolni Chiflik', 5, 229)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (252, 30, N'Бяла', N'Byala',N'Byala', 5, 225)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (253, 30, N'Аврен', N'Avren',N'Avren', 5, 222)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (254, 30, N'Провадия', N'Provadia',N'Provadia', 5, 232)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (255, 30, N'Ветрино', N'Vetrino',N'Vetrino', 5, 227)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (256, 30, N'Вълчи Дол', N'Valchi dol',N'Valchi dol', 5, 228)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (257, 30, N'Суворово', N'Suvorovo',N'Suvorovo', 5, 233)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (258, 30, N'Девня', N'Devnya',N'Devnya', 5, 230)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (259, 30, N'Белослав', N'Beloslav',N'Beloslav', 5, 224)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (260, 30, N'Варна', N'Varna',N'Varna', 5, 226)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (261, 30, N'Аксаково', N'Aksakovo',N'Aksakovo', 5, 223)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (262, 31, N'Велико Търново', N'Veliko Tarnovo',N'Veliko Tarnovo', 5, 255)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (263, 31, N'Горна Оряховица', N'Gorna Oryahovitsa',N'Gorna Oryahovitsa', 5, 256)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (264, 31, N'Елена', N'Elena',N'Elena', 5, 257)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (265, 31, N'Златарица', N'Zlataritsa',N'Zlataritsa', 5, 258)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (266, 31, N'Лясковец', N'Lyaskovets',N'Lyaskovets', 5, 259)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (267, 31, N'Павликени', N'Pavlikeni',N'Pavlikeni', 5, 260)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (268, 31, N'Полски Тръмбеш', N'Polski Trambesh',N'Polski Trambesh', 5, 261)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (269, 31, N'Свищов', N'Svishtov',N'Svishtov', 5, 262)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (270, 31, N'Стражица', N'Strazhitsa',N'Strazhitsa', 5, 263)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (271, 31, N'Сухиндол', N'Suhindol',N'Suhindol', 5, 264)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (272, 32, N'Белоградчик', N'Belogradchik',N'Belogradchik', 5, 234)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (273, 32, N'Чупрене', N'Chuprene',N'Chuprene', 5, 244)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (274, 32, N'Ружинци', N'Ruzhintsi',N'Ruzhintsi', 5, 243)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (275, 32, N'Димово', N'Dimovo',N'Dimovo', 5, 239)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (276, 32, N'Макреш', N'Makresh',N'Makresh', 5, 241)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (277, 32, N'Грамада', N'Gramada',N'Gramada', 5, 238)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (278, 32, N'Видин', N'Vidin',N'Vidin', 5, 237)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (279, 32, N'Кула', N'Kula',N'Kula', 5, 240)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (280, 32, N'Брегово', N'Bregovo',N'Bregovo', 5, 236)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (281, 32, N'Ново село', N'Novo Selo',N'Novo Selo', 5, 242)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (282, 32, N'Бойница', N'Boynitsa',N'Boynitsa', 5, 235)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (283, 33, N'Криводол', N'Krivodol',N'Krivodol', 5, 249)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (284, 33, N'Враца', N'Vratsa',N'Vratsa', 5, 247)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (285, 33, N'Борован', N'Borovan',N'Borovan', 5, 245)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (286, 33, N'Бяла Слатина', N'Byala Slatina',N'Byala Slatina', 5, 246)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (287, 33, N'Мездра', N'Mezdra',N'Mezdra', 5, 250)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (288, 33, N'Роман', N'Roman',N'Roman', 5, 253)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (289, 33, N'Оряхово', N'Oryahovo',N'Oryahovo', 5, 252)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (290, 33, N'Хайредин', N'Hayredin',N'Hayredin', 5, 254)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (291, 33, N'Козлодуй', N'Kozloduy',N'Kozloduy', 5, 248)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (292, 33, N'Мизия', N'Mizia',N'Mizia', 5, 251)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (293, 34, N'Елхово', N'Elhovo',N'Elhovo', 5, 52)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (294, 34, N'Болярово', N'Bolyarovo',N'Bolyarovo', 5, 51)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (295, 34, N'Ямбол', N'Yambol',N'Yambol', 5, 55)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (296, 34, N'Тунджа', N'Tundzha',N'Tundzha', 5, 54)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (297, 34, N'Стралджа', N'Straldzha',N'Straldzha', 5, 53)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (298, 14, N'Сърница', N'Sarnica',N'Sarnica', 5, 265)
INSERT [dbo].[MapRegions] ([Id], [MapId], [Name], [NameAlt], [NameAltEnglish], [NutsLevel], [RegionId]) VALUES (299, 17, N'Сопот', N'Sopot',N'Sopot', 5, 119)
GO

SET IDENTITY_INSERT [dbo].[MapRegions] OFF
GO
