//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BFPContractSAPData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BFPContractSAPData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Views.Shared.App_LocalResources.BFPContractSAPData", typeof(BFPContractSAPData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование на бенефициент.
        /// </summary>
        public static string BeneficiaryName {
            get {
                return ResourceManager.GetString("BeneficiaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор на бенефициент.
        /// </summary>
        public static string BeneficiaryUin {
            get {
                return ResourceManager.GetString("BeneficiaryUin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансиране от ЕС.
        /// </summary>
        public static string BudgetEU {
            get {
                return ResourceManager.GetString("BudgetEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национално финансиране.
        /// </summary>
        public static string BudgetNational {
            get {
                return ResourceManager.GetString("BudgetNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо.
        /// </summary>
        public static string BudgetTotal {
            get {
                return ResourceManager.GetString("BudgetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стойност на бюджета в лева:.
        /// </summary>
        public static string BudgetValueLv {
            get {
                return ResourceManager.GetString("BudgetValueLv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на приключване.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на договор/анекс.
        /// </summary>
        public static string ContractRegNumber {
            get {
                return ResourceManager.GetString("ContractRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на приоритетна ос.
        /// </summary>
        public static string PriorityCode {
            get {
                return ResourceManager.GetString("PriorityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на процедура.
        /// </summary>
        public static string ProcedureCode {
            get {
                return ResourceManager.GetString("ProcedureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на оперативна програма.
        /// </summary>
        public static string ProgrammeCode {
            get {
                return ResourceManager.GetString("ProgrammeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на проектно предложение.
        /// </summary>
        public static string ProjectRegNumber {
            get {
                return ResourceManager.GetString("ProjectRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на стартиране.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
    }
}
