//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Views.Shared.App_LocalResources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несъществуващ адрес на страница.
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсващи данни за заявител.
        /// </summary>
        public static string ApplicantMissingData {
            get {
                return ResourceManager.GetString("ApplicantMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рестартирайте браузъра и опитайте по-късно!.
        /// </summary>
        public static string BrowserRestart {
            get {
                return ResourceManager.GetString("BrowserRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заредете електронен подпис, отговарящ на изискванията и рестартирайте браузъра!.
        /// </summary>
        public static string BrowserRestartPrompt {
            get {
                return ResourceManager.GetString("BrowserRestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комуникационна грешка.
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В базата данни липсват данни за лице с ЕГН:.
        /// </summary>
        public static string DatabaseMissingPersonData {
            get {
                return ResourceManager.GetString("DatabaseMissingPersonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В базата данни липсват данни за месторождение на лице с ЕГН:.
        /// </summary>
        public static string DatabaseMissingPersonPlaceOfBirth {
            get {
                return ResourceManager.GetString("DatabaseMissingPersonPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ за издаване на електронно свидетелство за съдимост.
        /// </summary>
        public static string Denial {
            get {
                return ResourceManager.GetString("Denial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анулиран или блокиран електронен подпис.
        /// </summary>
        public static string DigitalSignatureBlocked {
            get {
                return ResourceManager.GetString("DigitalSignatureBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият електронен подпис е анулиран или блокиран от издателя..
        /// </summary>
        public static string DigitalSignatureBlockedByIssuer {
            get {
                return ResourceManager.GetString("DigitalSignatureBlockedByIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтекъл срок на валидност на електронен подпис.
        /// </summary>
        public static string DigitalSignatureExpired {
            get {
                return ResourceManager.GetString("DigitalSignatureExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият електронен подпис е с изтекъл срок на валидност..
        /// </summary>
        public static string DigitalSignatureExpiredLong {
            get {
                return ResourceManager.GetString("DigitalSignatureExpiredLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден електронен подпис.
        /// </summary>
        public static string DigitalSignatureInvalid {
            get {
                return ResourceManager.GetString("DigitalSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неразпознат издател на електронен подпис.
        /// </summary>
        public static string DigitalSignatureIssuerNotRecognized {
            get {
                return ResourceManager.GetString("DigitalSignatureIssuerNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издателят на Вашия електронен подпис не се поддържа от системата..
        /// </summary>
        public static string DigitalSignatureIssuerNotRecognizedLong {
            get {
                return ResourceManager.GetString("DigitalSignatureIssuerNotRecognizedLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсващи данни в електронния подпис.
        /// </summary>
        public static string DigitalSignatureMissingData {
            get {
                return ResourceManager.GetString("DigitalSignatureMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият електронен подпис не съдържа информация за ЕГН..
        /// </summary>
        public static string DigitalSignatureMissingEGN {
            get {
                return ResourceManager.GetString("DigitalSignatureMissingEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системата не може да зареди електронен подпис..
        /// </summary>
        public static string DigitalSignatureNotLoaded {
            get {
                return ResourceManager.GetString("DigitalSignatureNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден или неразпознат електронен подпис.
        /// </summary>
        public static string DigitalSignatureNotRecognized {
            get {
                return ResourceManager.GetString("DigitalSignatureNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият електронен подпис е невалиден или неразпознат от системата..
        /// </summary>
        public static string DigitalSignatureNotRecognizedLong {
            get {
                return ResourceManager.GetString("DigitalSignatureNotRecognizedLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системата не може да зареди квалифициран електронен подпис..
        /// </summary>
        public static string DigitalSignatureQualified {
            get {
                return ResourceManager.GetString("DigitalSignatureQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да достъпите подадените от Вас заявления и/или образуваните във връзка с тях преписки, е необходимо да се идентифицирате с квалифициран електронен подпис..
        /// </summary>
        public static string DigitalSignatureQualifiedLong {
            get {
                return ResourceManager.GetString("DigitalSignatureQualifiedLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да подадете заявление за издаване на електронно свидетелство съдимост или да достъпите Вашите заявления и свидетелства, е необходимо да се идентифицирате с квалифициран електронен подпис, издаден на физическо лице..
        /// </summary>
        public static string DigitalSignatureQualifiedLongPhysicalPerson {
            get {
                return ResourceManager.GetString("DigitalSignatureQualifiedLongPhysicalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видът на Вашия електронен подпис не се поддържа от системата. Електронния подпис за идентифициране в системата трябва да бъде издаден на физическо лице..
        /// </summary>
        public static string DigitalSignatureTypeNotSupported {
            get {
                return ResourceManager.GetString("DigitalSignatureTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код за грешка:.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to код за грешка:.
        /// </summary>
        public static string ErrorCodeLower {
            get {
                return ResourceManager.GetString("ErrorCodeLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изисква се идентификация с електронен подпис.
        /// </summary>
        public static string ErrorDigitalSignatureIdentification {
            get {
                return ResourceManager.GetString("ErrorDigitalSignatureIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощ, въпроси и отговори.
        /// </summary>
        public static string HelpQA {
            get {
                return ResourceManager.GetString("HelpQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да бъде издадено електронно свидетелство за съдимост на лице с ЕГН:.
        /// </summary>
        public static string IssuerUnableWithEGN {
            get {
                return ResourceManager.GetString("IssuerUnableWithEGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информационната система няма възможност да Ви издаде електронно свидетелство за съдимост..
        /// </summary>
        public static string IssueUnable1 {
            get {
                return ResourceManager.GetString("IssueUnable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За допълнителна информация се обърнете към Централно бюро за съдимост или към Вашия районен съд по месторождение..
        /// </summary>
        public static string IssueUnable2 {
            get {
                return ResourceManager.GetString("IssueUnable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка. Моля, опитайте отново по-късно..
        /// </summary>
        public static string MainError {
            get {
                return ResourceManager.GetString("MainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За повече информация виж.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навигационна грешка.
        /// </summary>
        public static string NavigationError {
            get {
                return ResourceManager.GetString("NavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съгласно Наредба № 8 от 26 февруари 2008 г. за функциите и организацията на дейността на бюрата за съдимост електронни свидетелства за съдимост могат да бъдат издавани само на лица, за които не са издавани бюлетини за съдимост и за наложени административни наказания по чл. 78а НК..
        /// </summary>
        public static string OrganizationFunctionsOrdinance {
            get {
                return ResourceManager.GetString("OrganizationFunctionsOrdinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За справка се обърнете към Вашия районен съд по месторождение..
        /// </summary>
        public static string RegionalCourt {
            get {
                return ResourceManager.GetString("RegionalCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникнала грешка при заявка към сървъра..
        /// </summary>
        public static string ServerRequestError {
            get {
                return ResourceManager.GetString("ServerRequestError", resourceCulture);
            }
        }
    }
}
