//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinanceInstrumentsReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinanceInstrumentsReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Views.Shared.App_LocalResources.FinanceInstrumentsReport", typeof(FinanceInstrumentsReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стойност.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средства, за които са поети задължения по договори за гаранции.
        /// </summary>
        public static string CommitmentsGuaranteeAmount {
            get {
                return ResourceManager.GetString("CommitmentsGuaranteeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обща сума на приноса от програмата, реално изплатен като допустими разходи съгласно член 41 (1) (а), (б) и (г) на Регламент (ЕС) № 1303/2013.
        /// </summary>
        public static string ContributionProgramActuallyPaidTotalAmount {
            get {
                return ResourceManager.GetString("ContributionProgramActuallyPaidTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума на съответстващите публични разходи.
        /// </summary>
        public static string CorrespondingPublicSpendingAmount {
            get {
                return ResourceManager.GetString("CorrespondingPublicSpendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очакван лостов ефект за заем/гаранция/дялови или квазидялови инвестиции/друг финансов продукт.
        /// </summary>
        public static string ExpectedLeverageLoanAmount {
            get {
                return ResourceManager.GetString("ExpectedLeverageLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходи за управление.
        /// </summary>
        public static string ExpenseManagementAmount {
            get {
                return ResourceManager.GetString("ExpenseManagementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на инвестициите и участието спрямо предходните години.
        /// </summary>
        public static string InvestmentParticipationPreviousYearsAmount {
            get {
                return ResourceManager.GetString("InvestmentParticipationPreviousYearsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такси за управление на финансовия инструмент.
        /// </summary>
        public static string ManagementFeesAmount {
            get {
                return ResourceManager.GetString("ManagementFeesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общ размер на другия принос, извън ЕСИ фондовете, за които е поет ангажимент в споразумението за финансиране с органа, изпълняващ финансовия инструмент (за финансови инструменти).
        /// </summary>
        public static string OtherContributionsOutsideESI {
            get {
                return ResourceManager.GetString("OtherContributionsOutsideESI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общ размер на другия принос, извън ЕСИ фондовете, мобилизиран на равнището на крайните получатели.
        /// </summary>
        public static string OtherContributionsOutsideESIMobilizedFinalRecipients {
            get {
                return ResourceManager.GetString("OtherContributionsOutsideESIMobilizedFinalRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума на плащанията към крайни получатели.
        /// </summary>
        public static string PaymentsFinalRecipientsAmount {
            get {
                return ResourceManager.GetString("PaymentsFinalRecipientsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частен принос.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постигнат ефект на лоста в края на отчетната година за съответния продукт.
        /// </summary>
        public static string ProgressLeverageYearProductAmount {
            get {
                return ResourceManager.GetString("ProgressLeverageYearProductAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичен принос.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на повторно използваните ресурси, които са били възстановени на финансовия инструмент и се отнасят към ЕСИ фондовете.
        /// </summary>
        public static string ReusableResourcesSizeAmount {
            get {
                return ResourceManager.GetString("ReusableResourcesSizeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
