//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Splashes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Splashes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Views.Shared.App_LocalResources.Splashes", typeof(Splashes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приемам.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                        Ако желаете да кандидатствате, системата е достъпна на официалния интернет адрес: &lt;a href=&quot;https://eumis2020.government.bg&quot; target=&quot;_blank&quot;&gt;&lt;b&gt;eumis2020.government.bg&lt;/b&gt;&lt;/a&gt;
        ///                    &lt;p&gt;&lt;b&gt;Екипът на СУНИ&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        public static string ApplyProposal {
            get {
                return ResourceManager.GetString("ApplyProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаеми потребители,.
        /// </summary>
        public static string DearUsers {
            get {
                return ResourceManager.GetString("DearUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СРЕДА ЗА РАЗРАБОТКА НА СУНИ.
        /// </summary>
        public static string DevelopmentEnvironment {
            get {
                return ResourceManager.GetString("DevelopmentEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to във.
        /// </summary>
        public static string InLong {
            get {
                return ResourceManager.GetString("InLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВЪТРЕШНА СРЕДАТА ЗА ТЕСТВАНЕ НА СУНИ.
        /// </summary>
        public static string InnerTestEnvironment {
            get {
                return ResourceManager.GetString("InnerTestEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СРЕДА ЗА ОБУЧЕНИЕ НА СУНИ.
        /// </summary>
        public static string LearnEnvironment {
            get {
                return ResourceManager.GetString("LearnEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в момента се намирате.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и ние не може да Ви гарантираме актуалност на данните. Тук може да разгледате цялата или част от функционалността на приложението..
        /// </summary>
        public static string NoGuarantee {
            get {
                return ResourceManager.GetString("NoGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако имате отворен документ за редакция, няма да можете да запазите направените от Вас промени. Сигурни ли сте, че искате да излезете?.
        /// </summary>
        public static string OpenDocument {
            get {
                return ResourceManager.GetString("OpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ако подадете проектно предложение  от достъпения в момента адрес, то със сигурност няма да бъде обработено, а част от данните Ви при актуализация могат да бъдат изтрити..
        /// </summary>
        public static string SubmitProjectProposal {
            get {
                return ResourceManager.GetString("SubmitProjectProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екипът на СУНИ.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СРЕДАТА ЗА ТЕСТВАНЕ НА СУНИ.
        /// </summary>
        public static string TestEnvironment {
            get {
                return ResourceManager.GetString("TestEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
