USE [master]
GO

print 'Create database SsisLog'
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'SsisLog')
BEGIN
    ALTER DATABASE [SsisLog] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [SsisLog]
END
GO

CREATE DATABASE [SsisLog]
GO

ALTER DATABASE [SsisLog]
SET ALLOW_SNAPSHOT_ISOLATION ON

ALTER DATABASE [SsisLog]
SET READ_COMMITTED_SNAPSHOT ON
GO
