//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.Rio
{


	[Serializable]
	public enum CompanyTypeNomenclature
	{
		[XmlEnum(Name="Beneficiary")] Beneficiary,
		[XmlEnum(Name="Partner")] Partner,
		[XmlEnum(Name="Contractor")] Contractor
	}

}
