//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.Rio
{




	[XmlType(TypeName="TechnicalReportTeamMember",Namespace="http://ereg.egov.bg/segment/R-10057"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class TechnicalReportTeamMember
	{

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="Position",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Position;
		
		[XmlIgnore]
		public string Position
		{ 
			get { return __Position; }
			set { __Position = value; }
		}

		[XmlElement(ElementName="Uin",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Uin;
		
		[XmlIgnore]
		public string Uin
		{ 
			get { return __Uin; }
			set { __Uin = value; }
		}

		[XmlElement(Type=typeof(Eumis.Rio.PrivateNomenclature),ElementName="UinType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.Rio.PrivateNomenclature __UinType;
		
		[XmlIgnore]
		public Eumis.Rio.PrivateNomenclature UinType
		{
			get {return __UinType;}
			set {__UinType = value;}
		}

		[XmlElement(Type=typeof(Eumis.Rio.EnumNomenclature),ElementName="CommitmentType",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.Rio.EnumNomenclature __CommitmentType;
		
		[XmlIgnore]
		public Eumis.Rio.EnumNomenclature CommitmentType
		{
			get {return __CommitmentType;}
			set {__CommitmentType = value;}
		}

		[XmlElement(ElementName="Date",Form=XmlSchemaForm.Qualified,DataType="date",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __Date;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __DateSpecified { get { return __Date.HasValue; } }
		
		[XmlIgnore]
		public DateTime? Date
		{ 
			get { return __Date; }
			set { __Date = value; }
		}
		


		[XmlElement(ElementName="Hours",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="decimal",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public decimal __Hours;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HoursSpecified;
		
		[XmlIgnore]
		public decimal Hours
		{ 
			get { return __Hours; }
			set { __Hours = value; __HoursSpecified = true; }
		}

		[XmlElement(ElementName="Activity",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Activity;
		
		[XmlIgnore]
		public string Activity
		{ 
			get { return __Activity; }
			set { __Activity = value; }
		}

		[XmlElement(ElementName="Result",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10057")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Result;
		
		[XmlIgnore]
		public string Result
		{ 
			get { return __Result; }
			set { __Result = value; }
		}

		public TechnicalReportTeamMember()
		{
		}
	}
}
