//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.Rio
{




	[XmlType(TypeName="EvalTableCriteria",Namespace="http://ereg.egov.bg/segment/R-10021"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class EvalTableCriteria
	{

		[XmlAttribute(AttributeName="gid",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __gid;
		
		[XmlIgnore]
		public string gid
		{ 
			get { return __gid; }
			set { __gid = value; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10021")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="IsRejection",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean",Namespace="http://ereg.egov.bg/segment/R-10021")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IsRejection;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __IsRejectionSpecified;
		
		[XmlIgnore]
		public bool IsRejection
		{ 
			get { return __IsRejection; }
			set { __IsRejection = value; __IsRejectionSpecified = true; }
		}

		[XmlElement(ElementName="Weight",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="decimal",Namespace="http://ereg.egov.bg/segment/R-10021")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public decimal __Weight;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __WeightSpecified;
		
		[XmlIgnore]
		public decimal Weight
		{ 
			get { return __Weight; }
			set { __Weight = value; __WeightSpecified = true; }
		}

		public EvalTableCriteria()
		{
		}
	}
}
