//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.Rio
{




	[XmlType(TypeName="SubcontractorMember",Namespace="http://ereg.egov.bg/segment/R-10069"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class SubcontractorMember
	{

		[XmlElement(Type=typeof(Eumis.Rio.EnumNomenclature),ElementName="Type",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10069")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.Rio.EnumNomenclature __Type;
		
		[XmlIgnore]
		public Eumis.Rio.EnumNomenclature Type
		{
			get {return __Type;}
			set {__Type = value;}
		}

		[XmlElement(Type=typeof(Eumis.Rio.PrivateNomenclature),ElementName="Contractor",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10069")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.Rio.PrivateNomenclature __Contractor;
		
		[XmlIgnore]
		public Eumis.Rio.PrivateNomenclature Contractor
		{
			get {return __Contractor;}
			set {__Contractor = value;}
		}

		[XmlElement(ElementName="ContractDate",Form=XmlSchemaForm.Qualified,DataType="date",Namespace="http://ereg.egov.bg/segment/R-10069")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime? __ContractDate;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ContractDateSpecified { get { return __ContractDate.HasValue; } }
		
		[XmlIgnore]
		public DateTime? ContractDate
		{ 
			get { return __ContractDate; }
			set { __ContractDate = value; }
		}
		


		[XmlElement(ElementName="ContractNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10069")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ContractNumber;
		
		[XmlIgnore]
		public string ContractNumber
		{ 
			get { return __ContractNumber; }
			set { __ContractNumber = value; }
		}

		[XmlElement(ElementName="ContractAmount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="decimal",Namespace="http://ereg.egov.bg/segment/R-10069")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public decimal __ContractAmount;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ContractAmountSpecified;
		
		[XmlIgnore]
		public decimal ContractAmount
		{ 
			get { return __ContractAmount; }
			set { __ContractAmount = value; __ContractAmountSpecified = true; }
		}

		public SubcontractorMember()
		{
		}
	}
}
