//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.Rio
{


	using ProgrammeDetailsExpenseBudgetCollection = System.Collections.Generic.List<Eumis.Rio.ProgrammeDetailsExpenseBudget>;



	[XmlType(TypeName="ProgrammeExpenseBudget",Namespace="http://ereg.egov.bg/segment/R-10008"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class ProgrammeExpenseBudget
	{

		[XmlAttribute(AttributeName="gid",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __gid;
		
		[XmlIgnore]
		public string gid
		{ 
			get { return __gid; }
			set { __gid = value; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10008")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="NameEN",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10008")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __NameEN;
		
		[XmlIgnore]
		public string NameEN
		{ 
			get { return __NameEN; }
			set { __NameEN = value; }
		}

		[XmlElement(ElementName="OrderNum",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10008")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __OrderNum;
		
		[XmlIgnore]
		public string OrderNum
		{ 
			get { return __OrderNum; }
			set { __OrderNum = value; }
		}

		[XmlElement(ElementName="ProgrammePriorityCode",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10008")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ProgrammePriorityCode;
		
		[XmlIgnore]
		public string ProgrammePriorityCode
		{ 
			get { return __ProgrammePriorityCode; }
			set { __ProgrammePriorityCode = value; }
		}

		[XmlElement(Type=typeof(Eumis.Rio.EnumNomenclature),ElementName="AidMode",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10008")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.Rio.EnumNomenclature __AidMode;
		
		[XmlIgnore]
		public Eumis.Rio.EnumNomenclature AidMode
		{
			get {return __AidMode;}
			set {__AidMode = value;}
		}

		[XmlElement(Type=typeof(Eumis.Rio.ProgrammeDetailsExpenseBudget),ElementName="ProgrammeDetailsExpenseBudget",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10008")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ProgrammeDetailsExpenseBudgetCollection __ProgrammeDetailsExpenseBudgetCollection;
		
		[XmlIgnore]
		public ProgrammeDetailsExpenseBudgetCollection ProgrammeDetailsExpenseBudgetCollection
		{
			get
			{
				if (__ProgrammeDetailsExpenseBudgetCollection == null) __ProgrammeDetailsExpenseBudgetCollection = new ProgrammeDetailsExpenseBudgetCollection();
				return __ProgrammeDetailsExpenseBudgetCollection;
			}
			set {__ProgrammeDetailsExpenseBudgetCollection = value;}
		}

		public ProgrammeExpenseBudget()
		{
		}
	}
}
