//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.Rio
{




	[XmlType(TypeName="DifferentiatedPosition",Namespace="http://ereg.egov.bg/segment/R-10071"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class DifferentiatedPosition
	{

		[XmlAttribute(AttributeName="gid",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __gid;
		
		[XmlIgnore]
		public string gid
		{ 
			get { return __gid; }
			set { __gid = value; }
		}

		[XmlElement(ElementName="Name",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10071")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Name;
		
		[XmlIgnore]
		public string Name
		{ 
			get { return __Name; }
			set { __Name = value; }
		}

		[XmlElement(ElementName="SubmittedOffersCount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace="http://ereg.egov.bg/segment/R-10071")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SubmittedOffersCount;
		
		[XmlIgnore]
		public string SubmittedOffersCount
		{ 
			get { return __SubmittedOffersCount; }
			set { __SubmittedOffersCount = value; }
		}

		[XmlElement(ElementName="RankedOffersCount",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="integer",Namespace="http://ereg.egov.bg/segment/R-10071")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __RankedOffersCount;
		
		[XmlIgnore]
		public string RankedOffersCount
		{ 
			get { return __RankedOffersCount; }
			set { __RankedOffersCount = value; }
		}

		[XmlElement(ElementName="Comment",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://ereg.egov.bg/segment/R-10071")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Comment;
		
		[XmlIgnore]
		public string Comment
		{ 
			get { return __Comment; }
			set { __Comment = value; }
		}

		[XmlElement(Type=typeof(Eumis.Rio.PrivateNomenclature),ElementName="ContractContractor",IsNullable=false,Form=XmlSchemaForm.Qualified,Namespace="http://ereg.egov.bg/segment/R-10071")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Eumis.Rio.PrivateNomenclature __ContractContractor;
		
		[XmlIgnore]
		public Eumis.Rio.PrivateNomenclature ContractContractor
		{
			get {return __ContractContractor;}
			set {__ContractContractor = value;}
		}

		public DifferentiatedPosition()
		{
		}
	}
}
