//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.0.0.0
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Eumis.RegiX.Rio.MVR
{




	[XmlType(TypeName="PersonalIdentityInfoRequestType",Namespace="http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class PersonalIdentityInfoRequestType
	{

		[XmlElement(ElementName="IdentityDocumentNumber",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __IdentityDocumentNumber;
		
		[XmlIgnore]
		public string IdentityDocumentNumber
		{ 
			get { return __IdentityDocumentNumber; }
			set { __IdentityDocumentNumber = value; }
		}

		[XmlElement(ElementName="EGN",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string",Namespace="http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __EGN;
		
		[XmlIgnore]
		public string EGN
		{ 
			get { return __EGN; }
			set { __EGN = value; }
		}

		public PersonalIdentityInfoRequestType()
		{
		}
	}


	[XmlRoot(ElementName="PersonalIdentityInfoRequest",Namespace="http://egov.bg/RegiX/MVR/BDS/PersonalIdentityInfoRequest",IsNullable=false),Serializable]
	public partial class PersonalIdentityInfoRequest : Eumis.RegiX.Rio.MVR.PersonalIdentityInfoRequestType
	{

		public PersonalIdentityInfoRequest() : base()
		{
		}
	}
}
