//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще получите съобщение на имейл адрес &lt;b&gt;{0}&lt;/b&gt; с линк за потвърждение..
        /// </summary>
        public static string ForgotPasswordSuccess {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е променена успешно..
        /// </summary>
        public static string RecoveryPasswordSuccess {
            get {
                return ResourceManager.GetString("RecoveryPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрацията премина успешно. На посочения електронен адрес &lt;b&gt;{0}&lt;/b&gt; ще получите линк за потвърждение, с който може да активирате профила си..
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полетата &quot;Парола&quot; и &quot;Парола отново&quot; не съвпадат..
        /// </summary>
        public static string ValidationActivationConfirmPasswordInvalid {
            get {
                return ResourceManager.GetString("ValidationActivationConfirmPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Парола отново&quot; е задължително..
        /// </summary>
        public static string ValidationActivationConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationActivationConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Парола&quot; трябва да съдържа поне 8 символа..
        /// </summary>
        public static string ValidationActivationPasswordInvalid {
            get {
                return ResourceManager.GetString("ValidationActivationPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Парола&quot; е задължително..
        /// </summary>
        public static string ValidationActivationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationActivationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полетата &quot;Нова парола&quot; и &quot;Въведи новата парола повторно&quot; не съвпадат..
        /// </summary>
        public static string ValidationConfirmPasswordInvalid {
            get {
                return ResourceManager.GetString("ValidationConfirmPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Въведи новата парола повторно&quot; е задължително..
        /// </summary>
        public static string ValidationConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot; е невалидно..
        /// </summary>
        public static string ValidationEmailForgottenInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailForgottenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot; е задължително..
        /// </summary>
        public static string ValidationEmailForgottenRequired {
            get {
                return ResourceManager.GetString("ValidationEmailForgottenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot;, съдържащо Вашия имейл адрес е невалидно..
        /// </summary>
        public static string ValidationEmailInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot; не може да съдържа повече от 100 символа..
        /// </summary>
        public static string ValidationEmailLength {
            get {
                return ResourceManager.GetString("ValidationEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot;, съдържащо Вашия имейл адрес е задължително..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Собствено име&quot; не може да съдържа повече от 100 символа..
        /// </summary>
        public static string ValidationFirstNameLength {
            get {
                return ResourceManager.GetString("ValidationFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Собствено име&quot; е задължително..
        /// </summary>
        public static string ValidationFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidationFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Фамилия&quot; не може да съдържа повече от 100 символа..
        /// </summary>
        public static string ValidationLastNameLength {
            get {
                return ResourceManager.GetString("ValidationLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Фамилия&quot; е задължително..
        /// </summary>
        public static string ValidationLastNameRequired {
            get {
                return ResourceManager.GetString("ValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Име&quot; е задължително..
        /// </summary>
        public static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Стара парола&quot; е задължително..
        /// </summary>
        public static string ValidationOldPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Нова парола&quot; трябва да съдържа поне 6 символа..
        /// </summary>
        public static string ValidationPasswordInvalid {
            get {
                return ResourceManager.GetString("ValidationPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Парола&quot; не може да съдържа повече от 100 символа..
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Нова парола&quot; е задължително..
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа минимум осем знака, като поне два от тях трябва да са: главни букви, малки букви, числа и специални символи. Пример: Pr0gr@m1..
        /// </summary>
        public static string ValidationPasswordSymbols {
            get {
                return ResourceManager.GetString("ValidationPasswordSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Телефон&quot; не е задължително, но може да съдържа само цифри, интервали, символа „+“ и не трябва да е по-голямо от 50 знака..
        /// </summary>
        public static string ValidationPhoneInvalid {
            get {
                return ResourceManager.GetString("ValidationPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Телефон&quot; не може да съдържа повече от 50 символа..
        /// </summary>
        public static string ValidationPhoneLengthInvalid {
            get {
                return ResourceManager.GetString("ValidationPhoneLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot;, съдържащо Вашия имейл адрес е невалидно..
        /// </summary>
        public static string ValidationUserInvalid {
            get {
                return ResourceManager.GetString("ValidationUserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;Потребителско име&quot;, съдържащо Вашия имейл адрес е задължително..
        /// </summary>
        public static string ValidationUserRequired {
            get {
                return ResourceManager.GetString("ValidationUserRequired", resourceCulture);
            }
        }
    }
}
