PRINT 'Insert InterventionCategories'
GO

SET IDENTITY_INSERT [InterventionCategories] ON

INSERT INTO [InterventionCategories]
    ([InterventionCategoryId], [Dimension], [Code], [Name], [NameAlt])
VALUES
    --ОБЛАСТ НА ИНТЕРВЕНЦИЯ
    (1 ,  1, N'001', N'Общи производствени инвестиции в малки и средни предприятия („МСП“)', N'Generic productive investment in small and medium – sized enterprises (‘SMEs’)'),
    (2 ,  1, N'002', N'Научноизследователски и иновационни процеси в големи предприятия', N'Research and innovation processes in large enterprises'),
    (3 ,  1, N'003', N'Производствени инвестиции в големи предприятия, свързани с нисковъглеродната икономика', N'Productive investment in large enterprises linked to the low-carbon economy'),
    (4 ,  1, N'004', N'Производствени инвестиции, свързани със сътрудничеството между големи предприятия и МСП за разработване на продукти и услуги на информационните и комуникационните технологии (ИКТ), електронната търговия и повишаването на търсенето на ИКТ', N'Productive investment linked to the cooperation between large enterprises and SMEs for developing information and communication technology (‘ICT’) products and services, e-commerce and enhancing demand for ICT'),
    (5 ,  1, N'005', N'Електроенергия (съхранение и пренос)', N'Electricity (storage and transmission)'),
    (6 ,  1, N'006', N'Електроенергия (съхранение и пренос чрез TEN-E — трансевропейската енергийна мрежа)', N'Electricity (TEN-E storage and transmission)'),
    (7 ,  1, N'007', N'Природен газ', N'Natural gas'),
    (8 ,  1, N'008', N'Природен газ (TEN-E)', N'Natural gas (TEN-E)'),
    (9 ,  1, N'009', N'Енергия от възобновяеми източници: вятър', N'Renewable energy: wind'),
    (10,  1, N'010', N'Енергия от възобновяеми източници: слънце',N'Renewable energy: solar'),
    (11,  1, N'011', N'Енергия от възобновяеми източници: биомаса', N'Renewable energy: biomass'),
    (12,  1, N'012', N'Други видове енергия от възобновяеми източници (включително водноелектрическа, геотермална и морска енергия) и интегриране на енергията от възобновяеми източници (включително съхранение, инфраструктура за технологията „електроенергия в газ“ и водород от възобновяеми източници)', N'Other renewable energy (including hydroelectric, geothermal and marine energy) and renewable energy integration (including storage, power to gas and renewable hydrogen infrastructure)'),
    (13,  1, N'013', N'Обновяване на обществената инфраструктура с цел повишаване на енергийната ефективност, демонстрационни проекти и подкрепящи мерки', N'Energy efficiency renovation of public infrastructure, demonstration projects and supporting measures'),
    (14,  1, N'014', N'Обновяване на наличния жилищен фонд с цел повишаване на енергийната ефективност, демонстрационни проекти и подкрепящи мерки', N'Energy efficiency renovation of existing housing stock, demonstration projects and supporting measures'),
    (15,  1, N'015', N'Интелигентни системи за разпределение на електроенергия със средно и ниско напрежение (включително интелигентни мрежи и ИКТ системи)', N'Intelligent Energy Distribution Systems at medium and low voltage levels (including smart grids and ICT systems)'),
    (16,  1, N'016', N'Високоефективно комбинирано производство на енергия и централно отопление', N'High efficiency co-generation and district heating'),
    (17,  1, N'017', N'Управление на битови отпадъци (включващо мерки за минимизиране, сортиране и рециклиране на отпадъците)', N'Household waste management (including minimisation, sorting, recycling measures)'),
    (18,  1, N'018', N'Управление на битови отпадъци (включващо мерки за механично-биологично третиране, термично третиране, изгаряне и депониране)', N'Household waste management (including mechanical biological treatment, thermal treatment, incineration and landfill measures)'),
    (19,  1, N'019', N'Управление на търговски, промишлени и опасни отпадъци', N'Commercial, industrial or hazardous waste management'),
    (20,  1, N'020', N'Осигуряване на питейна вода (инфраструктура за добив, пречистване, съхранение и водоразпределение)', N'Provision of water for human consumption (extraction, treatment, storage and distribution infrastructure)'),
    (21,  1, N'021', N'Управление на водите и опазване на питейната вода (включително управление на речните басейни, водоснабдяване, специфични мерки за адаптиране към изменението на климата, отчитане на потреблението на централно равнище и равнище отделен потребител, системи за таксуване и намаляване на течовете)', N'Water management and drinking water conservation (including river basin management, water supply, specific climate change adaptation measures, district and consumer metering, charging systems and leak reduction)'),
    (22,  1, N'022', N'Пречистване на отпадъчни води', N'Waste water treatment'),
    (23,  1, N'023', N'Мерки, свързани с опазването на околната среда, които са насочени към намаляване и/или предотвратяване на емисиите на парникови газове (включващи обработка и съхранение на метан и компостиране)', N'Environmental measures aimed at reducing and / or avoiding greenhouse gas emissions (including treatment and storage of methane gas and composting)'),
    (24,  1, N'024', N'Железопътен транспорт (основна мрежа на TEN-T — трансевропейската транспортна мрежа)', N'Railways (TEN-T Core)'),
    (25,  1, N'025', N'Железопътен транспорт (цялостна мрежа на TEN-T)', N'Railways (TEN-T comprehensive)'),
    (26,  1, N'026', N'Друг железопътен транспорт', N'Other Railways'),
    (27,  1, N'027', N'Подвижен железопътен състав', N'Mobile rail assets'),
    (28,  1, N'028', N'Магистрали и пътища на TEN-T — основна мрежа (ново строителство)', N'TEN-T motorways and roads — core network (new build)'),
    (29,  1, N'029', N'Магистрали и пътища на TEN-T — цялостна мрежа (ново строителство)', N'TEN-T motorways and roads — comprehensive network (new build)'),
    (30,  1, N'030', N'Второстепенни пътни връзки към пътната мрежа и възли на TEN-T (ново строителство)', N'Secondary road links to TEN-T road network and nodes (new build)'),
    (31,  1, N'031', N'Други национални и регионални пътища (ново строителство)', N'Other national and regional roads (new build)'),
    (32,  1, N'032', N'Местни пътища за достъп (ново строителство)', N'Local access roads (new build)'),
    (33,  1, N'033', N'Реконструиран или ремонтиран път от TEN-T', N'TEN-T reconstructed or improved road'),
    (34,  1, N'034', N'Друг реконструиран или ремонтиран път (магистрала, национален, регионален или местен път)', N'Other reconstructed or improved road (motorway, national, regional or local)'),
    (35,  1, N'035', N'Мултимодален транспорт (TEN-T)', N'Multimodal transport (TEN-T)'),
    (36,  1, N'036', N'Мултимодален транспорт', N'Multimodal transport'),
    (37,  1, N'037', N'Летища (TEN-T) ( 1 )', N'Airports (TEN-T)'),
    (38,  1, N'038', N'Други летища ( 1 )', N'Other airports'),
    (39,  1, N'039', N'Морски пристанища (TEN-T)', N'Seaports (TEN-T)'),
    (40,  1, N'040', N'Други морски пристанища', N'Other seaports'),
    (41,  1, N'041', N'Вътрешни водни пътища и пристанища (TEN-T)', N'Inland waterways and ports (TEN-T)'),
    (42,  1, N'042', N'Вътрешни водни пътища и пристанища (регионални и местни)', N'Inland waterways and ports (regional and local)'),
    (43,  1, N'043', N'Инфраструктура за екологосъобразен градски транспорт и насърчаване (включително оборудване и подвижен състав)', N'Clean urban transport infrastructure and promotion (including equipment and rolling stock)'),
    (44,  1, N'044', N'Интелигентни транспортни системи (включително въвеждане на управление на търсенето, системи за събиране на такси, ИТ системи за наблюдение, контрол и информиране)', N'Intelligent transport systems (including the introduction of demand management, tolling systems, IT monitoring, control and information systems)'),
    (45,  1, N'045', N'ИКТ: Основна/преносна мрежа', N'ICT: Backbone/backhaul network'),
    (46,  1, N'046', N'ИКТ: Високоскоростна широколентова мрежа (абонатен достъп/абонатна линия; >/= 30 Mbps)', N'ICT: High-speed broadband network (access/local loop; >/= 30 Mbps)'),
    (47,  1, N'047', N'ИКТ: Свръхвисокоскоростна широколентова мрежа (абонатен достъп/ абонатна линия; >/= 100 Mbps)', N'ICT: Very high-speed broadband network (access/local loop; >/= 100 Mbps)'),
    (48,  1, N'048', N'ИКТ: Други видове ИКТ инфраструктура/широкомащабни компютърни ресурси/оборудване (включително електронна инфраструктура, центрове и сензори за данни; също така, когато са вградени в друга инфраструктура, като например научноизследователски съоръжения, инфраструктура, свързана с опазването на околната среда, и социална инфраструктура)', N'ICT: Other types of ICT infrastructure/large-scale computer resources/equipment (including e-infrastructure, data centres and sensors; also where embedded in other infrastructure such as research facilities, environmental and social infrastructure)'),
    (49,  1, N'049', N'Образователна инфраструктура в областта на висшето образование', N'Education infrastructure for tertiary education'),
    (50,  1, N'050', N'Образователна инфраструктура в областта на професионалното образование и обучение и ученето за възрастни', N'Education infrastructure for vocational education and training and adult learning'),
    (51,  1, N'051', N'Образователна инфраструктура в областта на училищното образование (основно и общо средно образование)', N'Education infrastructure for school education (primary and general secondary education)'),
    (52,  1, N'052', N'Инфраструктура в областта на образованието и грижите в ранна детска възраст', N'Infrastructure for early childhood education and care'),
    (53,  1, N'053', N'Здравна инфраструктура', N'Health infrastructure'),
    (54,  1, N'054', N'Жилищна инфраструктура', N'Housing infrastructure'),
    (55,  1, N'055', N'Друга инфраструктура, която допринася за регионалното и местното развитие', N'Other social infrastructure contributing to regional and local development'),
    (56,  1, N'056', N'Инвестиции в инфраструктура, капацитет и оборудване в МСП, пряко свързани с научноизследователски и иновационни дейности', N'Investment in infrastructure, capacities and equipment in SMEs directly linked to research and innovation activities'),
    (57,  1, N'057', N'Инвестиции в инфраструктура, капацитет и оборудване в големи дружества, пряко свързани с научноизследователски и иновационни дейности', N'Investment in infrastructure, capacities and equipment in large companies directly linked to research and innovation activities'),
    (58,  1, N'058', N'Инфраструктура за научни изследвания и иновации (публична)', N'Research and innovation infrastructure (public)'),
    (59,  1, N'059', N'Инфраструктура за научни изследвания и иновации (частна, включително научни паркове)', N'Research and innovation infrastructure (private, including science parks)'),
    (60,  1, N'060', N'Научноизследователски и иновационни дейности в публични научноизследователски центрове и центрове на компетентност, включително изграждане на мрежи', N'Research and innovation activities in public research centres and centres of competence including networking'),
    (61,  1, N'061', N'Научноизследователски и иновационни дейности в частни научноизследователски центрове, включително изграждане на мрежи', N'Research and innovation activities in private research centres including networking'),
    (62,  1, N'062', N'Трансфер на технологии и сътрудничество между университети и предприятия, основно в полза на МСП', N'Technology transfer and university-enterprise cooperation primarily benefiting SMEs'),
    (63,  1, N'063', N'Подкрепа за клъстери и бизнес мрежи, основно в полза на МСП', N'Cluster support and business networks primarily benefiting SMEs'),
    (64,  1, N'064', N'Научноизследователски и иновационни процеси в МСП (включително схеми за ваучери, както и иновации в процесите, проектирането и сектора на услугите и социални иновации)', N'Research and innovation processes in SMEs (including voucher schemes, process, design, service and social innovation)'),
    (65,  1, N'065', N'Инфраструктура за научноизследователска и иновационна дейност, процеси, трансфер на технологии и сътрудничество в предприятия с акцент върху нисковъглеродната икономика и устойчивостта към изменението на климата', N'Research and innovation infrastructure, processes, technology transfer and cooperation in enterprises focusing on the low carbon economy and on resilience to climate change'),
    (66,  1, N'066', N'Специализирани услуги за подкрепа за МСП и групи от МСП (включително услуги за управление, маркетинг и проектиране)', N'Advanced support services for SMEs and groups of SMEs (including management, marketing and design services)'),
    (67,  1, N'067', N'Развитие на дейността на МСП, подкрепа за предприемачеството и създаването на предприятия (включително подкрепа за отделяне и разделяне на предприятия)', N'SME business development, support to entrepreneurship and incubation (including support to spin offs and spin outs)'),
    (68,  1, N'068', N'Енергийна ефективност и демонстрационни проекти в МСП и спомагателни мерки', N'Energy efficiency and demonstration projects in SMEs and supporting measures'),
    (69,  1, N'069', N'Подкрепа за благоприятни за околната среда производствени процеси и ефективно използване на ресурсите в МСП', N'Support to environmentally-friendly production processes and resource efficiency in SMEs'),
    (70,  1, N'070', N'Повишаване на енергийната ефективност в големите предприятия', N'Promotion of energy efficiency in large enterprises'),
    (71,  1, N'071', N'Развитие и насърчаване на предприятия, специализирани в предоставянето на услуги, които допринасят за нисковъглеродна икономика и устойчивост към изменението на климата (включително подкрепа за такива услуги)', N'Development and promotion of enterprises specialised in providing services contributing to the low carbon economy and to resilience to climate change (including support to such services)'),
    (72,  1, N'072', N'Стопанска инфраструктура за МСП (включително промишлени паркове и обекти)', N'Business infrastructure for SMEs (including industrial parks and sites)'),
    (73,  1, N'073', N'Подкрепа за социални предприятия (МСП)', N'Support to social enterprises (SMEs)'),
    (74,  1, N'074', N'Развитие и популяризиране на търговски туристически активи в МСП', N'Development and promotion of commercial tourism assets in SMEs'),
    (75,  1, N'075', N'Развитие и популяризиране на търговски туристически услуги във или за МСП', N'Development and promotion of commercial tourism services in or for SMEs'),
    (76,  1, N'076', N'Развитие и популяризиране на културни и творчески активи в МСП', N'Development and promotion of cultural and creative assets in SMEs'),
    (77,  1, N'077', N'Развитие и популяризиране на културни и творчески услуги във или за МСП', N'Development and promotion of cultural and creative services in or for SMEs'),
    (78,  1, N'078', N'Услуги и приложения за електронно управление (включително електронни обществени поръчки, ИКТ мерки за подкрепа за реформата на публичната администрация, сигурност в кибернетичното пространство, мерки за неприкосновеност на личния живот и доверие, електронно правосъдие и електронна демокрация)', N'e-Government services and applications (including e-Procurement, ICT measures supporting the reform of public administration, cyber-security, trust and privacy measures, e-Justice and e-Democracy)'),
    (79,  1, N'079', N'Достъп до информация в обществения сектор (включително открити данни в областта на електронната култура, цифровите библиотеки, електронното съдържание и електронния туризъм)', N'Access to public sector information (including open data e-Culture, digital libraries, e-Content and e-Tourism)'),
    (80,  1, N'080', N'Електронно приобщаване, електронна достъпност, услуги и приложения в областта на електронното учене и електронното образование, грамотност в областта на цифровите технологии', N'e-Inclusion, e-Accessibility, e-Learning and e-Education services and applications, digital literacy'),
    (81,  1, N'081', N'ИКТ решения, насочени към активен живот на възрастните хора и остаряване в добро здраве, и услуги и приложения в областта на електронното здравеопазване (включително електронни здравни грижи и интелигентна заобикаляща среда)', N'ICT solutions addressing the healthy active ageing challenge and e-Health services and applications (including e-Care and ambient assisted living)'),
    (82,  1, N'082', N'ИКТ услуги и приложения за МСП (включително електронна търговия, електронен бизнес и бизнес процеси в мрежа), „живи лаборатории“, интернет предприемачи и нови ИКТ предприятия', N'ICT Services and applications for SMEs (including e-Commerce, e-Business and networked business processes), living labs, web entrepreneurs and ICT start-ups)'),
    (83,  1, N'083', N'Мерки, свързани с качеството на въздуха', N'Air quality measures'),
    (84,  1, N'084', N'Комплексно предотвратяване и контрол на замърсяването (КПКЗ)', N'Integrated pollution prevention and control (IPPC)'),
    (85,  1, N'085', N'Опазване и укрепване на биологичното разнообразие, опазване на природата и екологосъобразна инфраструктура', N'Protection and enhancement of biodiversity, nature protection and green infrastructure'),
    (86,  1, N'086', N'Опазване, възстановяване и устойчиво използване на зони по „Натура 2000“', N'Protection, restoration and sustainable use of Natura 2000 sites'),
    (87,  1, N'087', N'Мерки за адаптиране към изменението на климата и предотвратяване и управление на рискове, свързани с климата, например ерозия, пожари, наводнения, бури и засушавания, включително повишаване на осведомеността, системи и инфраструктури за гражданска защита и управление на бедствия', N'Adaptation to climate change measures and prevention and management of climate related risks e.g. erosion, fires, flooding, storms and drought, including awareness raising, civil protection and disaster management systems and infrastructures'),
    (88,  1, N'088', N'Предотвратяване и управление на природни рискове, които не са свързани с климата (т.е. земетресения), и рискове, свързани с човешки дейности (например технологични аварии), включително повишаване на осведомеността, системи и инфраструктури за гражданска защита и управление на бедствия', N'Risk prevention and management of non-climate related natural risks (i.e. earthquakes) and risks linked to human activities (e.g. technological accidents), including awareness raising, civil protection and disaster management systems and infrastructures'),
    (89,  1, N'089', N'Рехабилитация на индустриални площи и замърсени земи', N'Rehabilitation of industrial sites and contaminated land'),
    (90,  1, N'090', N'Велосипедни и пешеходни алеи', N'Cycle tracks and footpaths'),
    (91,  1, N'091', N'Развитие и насърчаване на туристическия потенциал на природни територии', N'Development and promotion of the tourism potential of natural areas'),
    (92,  1, N'092', N'Опазване, развитие и популяризиране на публични туристически активи', N'Protection, development and promotion of public tourism assets'),
    (93,  1, N'093', N'Развитие и популяризиране на публични туристически услуги', N'Development and promotion of public tourism services'),
    (94,  1, N'094', N'Опазване, развитие и популяризиране на публични активи в областта на културата и културното наследство', N'Protection, development and promotion of public cultural and heritage assets'),
    (95,  1, N'095', N'Развитие и популяризиране на публични услуги в областта на културата и културното наследство', N'Development and promotion of public cultural and heritage services'),
    (96,  1, N'096', N'Институционален капацитет на публичните администрации и публичните служби, свързани с изпълнението на дейността на ЕФРР, или действия в подкрепа на инициативи на ЕСФ за институционален капацитет', N'Institutional capacity of public administrations and public services related to implementation of the ERDF or actions supporting ESF institutional capacity initiatives'),
    (97,  1, N'097', N'Инициативи за водено от общностите местно развитие в градски и селски райони', N'Community-led local development initiatives in urban and rural areas'),
    (98,  1, N'098', N'Най-отдалечени региони: компенсиране на допълнителните разходи вследствие на ограничения достъп и териториалната разпокъсаност', N'Outermost regions: compensation of any additional costs due to accessibility deficit and territorial fragmentation'),
    (99,  1, N'099', N'Най-отдалечени региони: специфични действия за компенсиране на допълнителните разходи вследствие на фактори, свързани с размера на пазара', N'Outermost regions: specific action to compensate additional costs due to size market factors'),
    (100, 1, N'100', N'Най-отдалечени региони: подкрепа за компенсиране на допълнителните разходи, свързани с климатичните условия и затрудненията поради релефа', N'Outermost regions: support to compensate additional costs due to climate conditions and relief difficulties'),
    (101, 1, N'101', N'Кръстосано финансиране по ЕФРР (подкрепа за свързани с ЕСФ действия, необходими за задоволителното изпълнение на частта на ЕФРР от операцията и пряко свързани с нея)', N'Cross-financing under the ERDF (support to ESF-type actions necessary for the satisfactory implementation of the ERDF part of the operation and directly linked to it)'),
    (102, 1, N'102', N'Достъп до заетост за търсещите работа и за неактивните лица, включително трайно безработните и лицата, отдалечени от пазара на труда, също и чрез местни инициативи за заетост и подкрепа за мобилността на работната сила', N'Access to employment for job-seekers and inactive people, including the long-term unemployed and people far from the labour market, also through local employment initiatives and support for labour mobility'),
    (103, 1, N'103', N'Устойчиво интегриране на пазара на труда на младите хора, в частност тези, които не са ангажирани с трудова дейност, образование или обучение, включително младите хора, изложени на риск от социално изключване, и младите хора от маргинализирани общности, включително чрез прилагане на схемата за гаранция за младежта', N'Sustainable integration into the labour market of young people, in particular those not in employment, education or training, including young people at risk of social exclusion and young people from marginalised communities, including through the implementation of the Youth Guarantee'),
    (104, 1, N'104', N'Самостоятелна заетост, предприемачество и създаване на предприятия, включително иновативни микро-, малки и средни предприятия', N'Self-employment, entrepreneurship and business creation including innovative micro, small and medium sized enterprises'),
    (105, 1, N'105', N'Равенство между мъжете и жените във всички области, включително в достъпа до заетост, напредъка в кариерата, съчетаване на професионалния и личния живот и насърчаване на равно заплащане за равен труд', N'Equality between men and women in all areas, including in access to employment, career progression, reconciliation of work and private life and promotion of equal pay for equal work'),
    (106, 1, N'106', N'Приспособяване на работниците, предприятията и предприемачите към промените', N'Adaptation of workers, enterprises and entrepreneurs to change'),
    (107, 1, N'107', N'Активен живот на възрастните хора и остаряване в добро здраве', N'Active and healthy ageing'),
    (108, 1, N'108', N'Модернизиране на институциите на пазара на труда, като публични и частни служби по заетостта, и повишаване на адекватността спрямо потребностите на пазара на труда, включително чрез действия за повишаване на транснационалната мобилност на работната сила, както и чрез схеми за мобилност и по-добро сътрудничество между институциите и съответните заинтересовани страни', N'Modernisation of labour market institutions, such as public and private employment services, and improving the matching of labour market needs, including throughactions that enhance transnational labour mobility as well as through mobility schemes and better cooperation between institutions and relevant stakeholders'),
    (109, 1, N'109', N'Активно приобщаване, включително с оглед насърчаване на равните възможности и активното участие и по-добрата пригодност за работа', N'Active inclusion, including with a view to promoting equal opportunities and active participation, and improving employability'),
    (110, 1, N'110', N'Социално-икономическа интеграция на маргинализирани общности като ромите', N'Socio-economic integration of marginalised communities such as the Roma'),
    (111, 1, N'111', N'Борба срещу всички форми на дискриминация и насърчаване на равенството на възможностите', N'Combating all forms of discrimination and promoting equal opportunities'),
    (112, 1, N'112', N'Повишаване на достъпа до услуги, които са на приемлива цена, устойчиви и висококачествени, включително здравни и социални услуги от общ интерес', N'Enhancing access to affordable, sustainable and high-quality services, including health care and social services of general interest'),
    (113, 1, N'113', N'Насърчаване на социалното предприемачество и на професионалната интеграция в социалните предприятия и насърчаване на социалната и солидарна икономика с цел улесняване на достъпа до заетост', N'Promoting social entrepreneurship and vocational integration in social enterprises and the social and solidarity economy in order to facilitate access to employment'), 
    (114, 1, N'114', N'Стратегии за водено от общностите местно развитие', N'Community-led local development strategies'),
    (115, 1, N'115', N'Намаляване и предотвратяване на преждевременното напускане на училище и насърчаване на равния достъп до висококачествено предучилищно, основно и средно образование, включващо формални, неформални и неофициални процеси на учене за повторно включване в образователната и обучителната система', N'Reducing and preventing early school-leaving and promoting equal access to good quality early-childhood, primary and secondary education including formal, non-formal and informal learning pathways for reintegrating into education and training'),
    (116, 1, N'116', N'Подобряване на качеството и ефективността и достъпа до висшето и равностойното на него образование с цел увеличаване на участието и подобряване на равнищата на образование, по-специално за групите в неравностойно положение', N'Improving the quality and efficiency of, and access to, tertiary and equivalent education with a view to increasing participation and attainment levels, especially for disadvantaged groups'),
    (117, 1, N'117', N'Подобряване на равния достъп до възможностите за учене през целия живот за всички възрастови групи във формален, неформален и неофициален вид, осъвременяване на познанията, уменията и компетенциите на работната ръка, както и насърчаване на гъвкави процеси на учене, включително чрез професионална ориентация и утвърждаване на придобитите компетенции', N'Enhancing equal access to lifelong learning for all age groups in formal, non-formal and informal settings, upgrading the knowledge, skills and competences of the workforce, and promoting flexible learning pathways including through career guidance and validation of acquired competences'),
    (118, 1, N'118', N'Подобряване на системите за образование и обучение спрямо пазара на труда, улесняване на прехода от образование към работа и укрепване на професионалното образование и системите на обучение, както и тяхното качество, включително чрез механизми за предвиждане на уменията, адаптиране на учебните програми и създаване и развитие на основаващи се на работата системи за учене, включително двойни системи на учене и схеми за чиракуване', N'Improving the labour market relevance of education and training systems, facilitating the transition from education to work, and strengthening vocational education and training systems and their quality, including through mechanisms for skills anticipation, adaptation of curricula and the establishment and development of work-based learning systems, including dual learning systems and apprenticeship schemes'),
    (119, 1, N'119', N'Инвестиции в институционален капацитет и в ефективността на публичните администрации и публичните служби на национално, регионално и местно равнище с цел осъществяването на реформи и постигането на по-добро регулиране и добро управление', N'Investment in institutional capacity and in the efficiency of public administrations and public services at the national, regional and local levels with a view to reforms, better regulation and good governance'),
    (120, 1, N'120', N'Изграждане на капацитет по отношение на всички заинтересовани страни, които изпълняват политики в областта на образованието, ученето през целия живот, обучението и политиките в областта на заетостта или социалната сфера, включително чрез секторни и териториални пактове за мобилизиране с цел осъществяването на реформи на национално, регионално и местно равнище', N'Capacity building for all stakeholders delivering education, lifelong learning, training and employment and social policies, including through sectoral and territorial pacts to mobilise for reform at the national, regional and local levels'),
    (121, 1, N'121', N'Подготовка, изпълнение, наблюдение и контрол' ,N'Preparation, implementation, monitoring and inspection'),
    (122, 1, N'122', N'Оценка и проучвания', N'Evaluation and studies'),
    (123, 1, N'123', N'Информиране и комуникация', N'Information and communication'),
    (190, 1, N'124', N'Не се прилага', N'Not applicable'),
    --ФОРМА НА ФИНАНСИРАНЕ
    (124, 2, N'01' , N'Безвъзмездни средства', N'Non-repayable grant'),
    (125, 2, N'02' , N'Средства, подлежащи на възстановяване', N'Repayable grant'),
    (126, 2, N'03' , N'Подкрепа чрез финансови инструменти: рисково инвестиране и дялов капитал или еквивалентен инструмент', N'Support through financial instruments: venture and equity capital or equivalent'),
    (127, 2, N'04' , N'Подкрепа чрез финансови инструменти: заем или еквивалентен инструмент', N'Support through financial instruments: loan or equivalent'),
    (128, 2, N'05' , N'Подкрепа чрез финансови инструменти: гаранция или еквивалентен инструмент', N'upport through financial instruments: guarantee or equivalent'),
    (129, 2, N'06' , N'Подкрепа чрез финансови инструменти: лихвена субсидия, субсидия за гаранционна такса, техническа помощ или еквивалентен инструмент', N'Support through financial instruments: interest rate subsidy, guarantee fee subsidy, technical support or equivalent'),
    (130, 2, N'07' , N'Награда', N'Prize'),
    --ВИД НА ТЕРИТОРИЯТА
    (131, 3, N'01' , N'Големи градски райони (гъстонаселени, с население >50 000 души)', N'Large Urban areas (densely populated > 50 000 population)'),
    (132, 3, N'02' , N'Малки градски райони (среднонаселени, с население >5 000 души)', N'Small Urban areas (intermediate density > 5 000 population)'),
    (133, 3, N'03' , N'Селски райони (слабонаселени)', N'Rural areas (thinly populated)'),
    (134, 3, N'04' , N'Макрорегионален район за сътрудничество', N'Macro regional cooperation area'),
    (135, 3, N'05' , N'Сътрудничество в райони по национални или регионални програми в национален контекст', N'Cooperation across national or regional programme areas in national context'),
    (136, 3, N'06' , N'Транснационално сътрудничество по ЕСФ', N'ESF transnational cooperation'),
    (137, 3, N'07' , N'Не се прилага', N'Not applicable'),
    --МЕХАНИЗМИ ЗА ТЕРИТОРИАЛНО ИЗПЪЛНЕНИЕ
    (138, 4, N'01' , N'Интегрирани териториални инвестиции — градски райони', N'Integrated Territorial Investment — Urban'),
    (139, 4, N'02' , N'Други интегрирани подходи за устойчиво развитие на градските райони', N'Other integrated approaches to sustainable urban development'),
    (140, 4, N'03' , N'Интегрирани териториални инвестиции — други', N'Integrated Territorial Investment — Other'),
    (141, 4, N'04' , N'Други интегрирани подходи за устойчиво развитие на селските райони', N'Other integrated approaches to sustainable rural development'),
    (142, 4, N'05' , N'Други интегрирани подходи към устойчиво развитие на градските/ селските райони', N'Other integrated approaches to sustainable urban/rural development'),
    (143, 4, N'06' , N'Инициативи за водено от общностите местно развитие', N'Community-led local development initiatives'),
    (144, 4, N'07' , N'Не се прилага', N'Not applicable'),
    --ТЕМАТИЧНА ЦЕЛ(ЕФРР И КОХЕЗИОНЕН ФОНД)
    (145, 5, N'01' , N'Засилване на научноизследователската дейност, развойната дейност в областта на технологиите и иновациите', N'Strengthening research, technological development and innovation'),
    (146, 5, N'02' , N'Подобряване на достъпа до информационни и комуникационни технологии и на тяхното използване и качество', N'Enhancing access to, and use and quality of, information and communication technologies'),
    (147, 5, N'03' , N'Повишаване на конкурентоспособността на малките и средните предприятия', N'Enhancing the competitiveness of small and medium-sized enterprises'),
    (148, 5, N'04' , N'Подпомагане на преминаването към нисковъглеродна икономика във всички сектори', N'Supporting the shift towards a low-carbon economy in all sectors'),
    (149, 5, N'05' , N'Насърчаване на адаптацията към изменението на климата и предотвратяването и управлението на риска', N'Promoting climate change adaptation, risk prevention and management'),
    (150, 5, N'06' , N'Съхраняване и опазване на околната среда и насърчаване на ресурсната ефективност', N'Preserving and protecting the environment and promoting resource efficiency'),
    (151, 5, N'07' , N'Насърчаване на устойчивия транспорт и премахване на участъците с недостатъчен капацитет във всички ключови мрежови инфраструктури', N'Promoting sustainable transport and removing bottlenecks in key network infrastructures'),
    (152, 5, N'08' , N'Насърчаване на устойчивата и качествена заетост и подкрепа за мобилността на работната сила', N'Promoting sustainable and quality employment and supporting labour mobility'),
    (153, 5, N'09' , N'Насърчаване на социалното приобщаване, борбата с бедността и всяка форма на дискриминация', N'Promoting social inclusion and combating poverty and any discrimination'),
    (154, 5, N'10' , N'Инвестиции в образованието, в обучението, включително професионалното обучение за придобиване на умения, и в ученето през целия живот', N'Investing in education, training and vocational training for skills and lifelong learning'),
    (155, 5, N'11' , N'Повишаване на институционалния капацитет на публичните органи и заинтересованите страни и допринасяне за ефикасността на публичната администрация', N'Enhancing the institutional capacity of public authorities and stakeholders and an efficient public administration'),
    (156, 5, N'12' , N'Не се прилага (само техническа помощ)', N'Not applicable (Technical assistance only)'),
    --ВТОРИЧНА ТЕМА НА ЕСФ
    (157, 6, N'01' , N'Подкрепа за преминаването към нисковъглеродна икономика и икономика с ефективно използване на ресурсите', N'Supporting the shift to a low-carbon, resource efficient economy'),
    (158, 6, N'02' , N'Социални иновации', N'Social innovation'),
    (159, 6, N'03' , N'Повишаване на конкурентоспособността на МСП', N'Enhancing the competitiveness of SMEs'),
    (160, 6, N'04' , N'Засилване на научноизследователската дейност, развойната дейност в областта на технологиите и иновациите', N'Strengthening research, technological development and innovation'),
    (161, 6, N'05' , N'Подобряване на достъпа до информационни и комуникационни технологии и на тяхното използване и качество', N'Enhancing the accessibility, use and quality of information and communication technologies'),
    (162, 6, N'06' , N'Недискриминация', N'Non-discrimination'),
    (163, 6, N'07' , N'Равенство между половете', N'Gender equality'),
    (164, 6, N'08' , N'Не се прилага', N'Not applicable'),
    --ИКОНОМИЧЕСКА ДЕЙНОСТ
    (165, 7, N'01' , N'Селско и горско стопанство', N'Agriculture and forestry'),
    (166, 7, N'02' , N'Рибарство и аквакултури' ,N'Fishing and aquaculture'),
    (167, 7, N'03' , N'Производство на хранителни продукти и напитки', N'Manufacture of food products and beverages'),
    (168, 7, N'04' , N'Производство на текстил и текстилни изделия', N'Manufacture of textiles and textile products'),
    (169, 7, N'05' , N'Производство на транспортно оборудване', N'Manufacture of transport equipment'),
    (170, 7, N'06' , N'Производство на компютърна техника, електронни и оптични продукти', N'Manufacture of computer, electronic and optical products'),
    (171, 7, N'07' , N'Други некласифицирани производствени отрасли', N'Other unspecified manufacturing industries'),
    (172, 7, N'08' , N'Строителство', N'Construction'),
    (173, 7, N'09' , N'Минно дело и добивна промишленост (включително добив на суровини за производство на енергия)', N'Mining and quarrying (including mining of energy producing materials)'),
    (174, 7, N'10' , N'Електрическа енергия, газообразни горива, топлинна енергия и климатизация', N'Electricity, gas, steam, hot water and air conditioning'),
    (175, 7, N'11' , N'Доставяне на води, канализационни услуги, управление на отпадъци и възстановяване', N'Water supply, sewerage, waste management and remediation activities'),
    (176, 7, N'12' , N'Транспорт и складиране', N'Transport and storage'),
    (177, 7, N'13' , N'Информационни и комуникационни дейности, включително телекомуникации, информационни услуги, компютърно програмиране, консултантска дейност и свързаните с тях дейности', N'Information and communication activities, including telecommunication, information service activities, computer programming, consultancy and related activities'),
    (178, 7, N'14' , N'Търговия на едро и дребно', N'Wholesale and retail trade'),
    (179, 7, N'15' , N'Туризъм, хотелиерство и ресторантьорство', N'Tourism, accommodation and food service activities'),
    (180, 7, N'16' , N'Финансови и застрахователни дейности', N'Financial and insurance activities'),
    (181, 7, N'17' , N'Недвижими имоти, отдаване под наем и услуги за предприятията', N'Real estate, renting and business activities'),
    (182, 7, N'18' , N'Публична администрация', N'Public administration'),
    (183, 7, N'19' , N'Образование', N'Education'),
    (184, 7, N'20' , N'Хуманно здравеопазване', N'Human health activities'),
    (185, 7, N'21' , N'Социална работа, колективни, социални и персонални услуги', N'Social work activities, community, social and personal services'),
    (186, 7, N'22' , N'Дейности, свързани с околната среда и изменението на климата', N'Activities linked to the environment and to climate change'),
    (187, 7, N'23' , N'Изкуство, развлечения, творчески индустрии и отдих', N'Arts, entertainment, creative industries and recreation'),
    (188, 7, N'24' , N'Други услуги, некласифицирани другаде', N'Other unspecified services'),
    (189, 7, N'25' , N'Не се прилага', N'Not applicable')

SET IDENTITY_INSERT [InterventionCategories] OFF
GO
