//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eumis.Portal.Web.Views.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageFinish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageFinish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eumis.Portal.Web.Views.Message.App_LocalResources.MessageFinish", typeof(MessageFinish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е приет от системата..
        /// </summary>
        public static string AcceptedBySystem {
            get {
                return ResourceManager.GetString("AcceptedBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , с наименование:.
        /// </summary>
        public static string Named {
            get {
                return ResourceManager.GetString("Named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оперативна програма.
        /// </summary>
        public static string OperationalProgramme {
            get {
                return ResourceManager.GetString("OperationalProgramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият отговор на въпрос от оценителната комисия по процедура:.
        /// </summary>
        public static string ProcedureAnswer {
            get {
                return ResourceManager.GetString("ProcedureAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорът ще се съхрани в системата и може да бъде намерен в менюто &lt;b&gt;„Проектни предложения“&lt;/b&gt;, раздел &lt;b&gt;„Подадени“&lt;/b&gt;, &lt;b&gt;„История“&lt;/b&gt;..
        /// </summary>
        public static string SaveAnswer {
            get {
                return ResourceManager.GetString("SaveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to към комуникация с регистрационен номер:.
        /// </summary>
        public static string ToCommunication {
            get {
                return ResourceManager.GetString("ToCommunication", resourceCulture);
            }
        }
    }
}
