/**
<summary>
Restore diagram 'Nuts'
</summary>
<remarks>
Generated by Tool_ScriptDiagram2008
Will attempt to create [sysdiagrams] table if it doesn't already exist
</remarks>
<generated>2014-10-08 11:15</generated>
*/
PRINT 'Restore diagram [Nuts]'
    -- If the sysdiagrams table has not been created in this database, create it!
                IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'sysdiagrams')
                BEGIN
                    -- Create table script generated by Sql Server Management Studio
                    -- _Assume_ this is roughly equivalent to what Sql Server/Management Studio
                    -- creates the first time you add a diagram to a 2008 database
                    CREATE TABLE [dbo].[sysdiagrams](
                        [name] [sysname] NOT NULL,
                        [principal_id] [int] NOT NULL,
                        [diagram_id] [int] IDENTITY(1,1) NOT NULL,
                        [version] [int] NULL,
                        [definition] [varbinary](max) NULL,
                    PRIMARY KEY CLUSTERED 
                    (
                        [diagram_id] ASC
                    )WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ,
                     CONSTRAINT [UK_principal_name] UNIQUE NONCLUSTERED 
                    (
                        [principal_id] ASC,
                        [name] ASC
                    )WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) 
                    ) 
                    EXEC sys.sp_addextendedproperty @name=N'microsoft_database_tools_support', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'sysdiagrams'
                END
                -- Target table will now exist, if it didn't before
SET NOCOUNT ON -- Hide (1 row affected) messages
DECLARE @newid INT
DECLARE @DiagramSuffix          varchar (50)
 
SET @DiagramSuffix = ' ' --+ LEFT(CONVERT(VARCHAR(23), GETDATE(), 121), 16)
 
BEGIN TRY
    INSERT INTO sysdiagrams ([name], [principal_id], [version], [definition]) VALUES ('Nuts'+@DiagramSuffix, 1, 1, 0x)
    SET @newid = SCOPE_IDENTITY()
END TRY
BEGIN CATCH
    PRINT 'XxXxX ' + Error_Message() + ' XxXxX'
    PRINT 'XxXxX END Tool_ScriptDiagram2008 - fix the error before running again XxXxX'
    RETURN
END CATCH
 
BEGIN TRY
    UPDATE sysdiagrams SET [definition] .Write ( 0XD0CF11E0A1B11AE1000000000000000000000000000000003E000300FEFF0900, null, 0) WHERE diagram_id = @newid -- index:1
    UPDATE sysdiagrams SET [definition] .Write ( 0X0600000000000000000000000100000001000000000000000010000002000000, null, 0) WHERE diagram_id = @newid -- index:33
    UPDATE sysdiagrams SET [definition] .Write ( 0X01000000FEFFFFFF0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:65
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:97
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:129
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:161
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:193
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:225
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:257
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:289
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:321
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:353
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:385
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:417
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:449
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:481
    UPDATE sysdiagrams SET [definition] .Write ( 0XFDFFFFFF10000000FEFFFFFF0400000005000000110000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:513
    UPDATE sysdiagrams SET [definition] .Write ( 0X090000000A0000000B0000000C0000000D0000000E0000000F000000FEFFFFFF, null, 0) WHERE diagram_id = @newid -- index:545
    UPDATE sysdiagrams SET [definition] .Write ( 0XFEFFFFFF12000000130000001400000015000000160000001700000018000000, null, 0) WHERE diagram_id = @newid -- index:577
    UPDATE sysdiagrams SET [definition] .Write ( 0X190000001A000000FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:609
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:641
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:673
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:705
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:737
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:769
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:801
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:833
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:865
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:897
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:929
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:961
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:993
    UPDATE sysdiagrams SET [definition] .Write ( 0X52006F006F007400200045006E00740072007900000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1025
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1057
    UPDATE sysdiagrams SET [definition] .Write ( 0X16000500FFFFFFFFFFFFFFFF0200000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1089
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000008026AE3ECCE2CF0103000000C019000000000000, null, 0) WHERE diagram_id = @newid -- index:1121
    UPDATE sysdiagrams SET [definition] .Write ( 0X6600000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1153
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1185
    UPDATE sysdiagrams SET [definition] .Write ( 0X04000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1217
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000006A05000000000000, null, 0) WHERE diagram_id = @newid -- index:1249
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F00000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1281
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1313
    UPDATE sysdiagrams SET [definition] .Write ( 0X040002010100000004000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1345
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000060000005F13000000000000, null, 0) WHERE diagram_id = @newid -- index:1377
    UPDATE sysdiagrams SET [definition] .Write ( 0X010043006F006D0070004F0062006A0000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1409
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1441
    UPDATE sysdiagrams SET [definition] .Write ( 0X12000201FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:1473
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000160000005F00000000000000, null, 0) WHERE diagram_id = @newid -- index:1505
    UPDATE sysdiagrams SET [definition] .Write ( 0X0100000002000000030000000400000005000000060000000700000008000000, null, 0) WHERE diagram_id = @newid -- index:1537
    UPDATE sysdiagrams SET [definition] .Write ( 0X090000000A0000000B0000000C0000000D0000000E0000000F00000010000000, null, 0) WHERE diagram_id = @newid -- index:1569
    UPDATE sysdiagrams SET [definition] .Write ( 0X1100000012000000130000001400000015000000FEFFFFFF17000000FEFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1601
    UPDATE sysdiagrams SET [definition] .Write ( 0X190000001A0000001B0000001C0000001D0000001E0000001F00000020000000, null, 0) WHERE diagram_id = @newid -- index:1633
    UPDATE sysdiagrams SET [definition] .Write ( 0X2100000022000000230000002400000025000000260000002700000028000000, null, 0) WHERE diagram_id = @newid -- index:1665
    UPDATE sysdiagrams SET [definition] .Write ( 0X290000002A0000002B0000002C0000002D0000002E0000002F00000030000000, null, 0) WHERE diagram_id = @newid -- index:1697
    UPDATE sysdiagrams SET [definition] .Write ( 0X3100000032000000330000003400000035000000360000003700000038000000, null, 0) WHERE diagram_id = @newid -- index:1729
    UPDATE sysdiagrams SET [definition] .Write ( 0X390000003A0000003B0000003C0000003D0000003E0000003F00000040000000, null, 0) WHERE diagram_id = @newid -- index:1761
    UPDATE sysdiagrams SET [definition] .Write ( 0X4100000042000000430000004400000045000000460000004700000048000000, null, 0) WHERE diagram_id = @newid -- index:1793
    UPDATE sysdiagrams SET [definition] .Write ( 0X490000004A0000004B0000004C0000004D0000004E0000004F00000050000000, null, 0) WHERE diagram_id = @newid -- index:1825
    UPDATE sysdiagrams SET [definition] .Write ( 0X51000000520000005300000054000000550000005600000057000000FEFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1857
    UPDATE sysdiagrams SET [definition] .Write ( 0XFEFFFFFF5A0000005B0000005C0000005D0000005E0000005F00000060000000, null, 0) WHERE diagram_id = @newid -- index:1889
    UPDATE sysdiagrams SET [definition] .Write ( 0X6100000062000000630000006400000065000000FEFFFFFFFEFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1921
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1953
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:1985
    UPDATE sysdiagrams SET [definition] .Write ( 0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, null, 0) WHERE diagram_id = @newid -- index:2017
    UPDATE sysdiagrams SET [definition] .Write ( 0X000428000A0E100C05000080100000000F00FFFF10000000007D000022510000, null, 0) WHERE diagram_id = @newid -- index:2049
    UPDATE sysdiagrams SET [definition] .Write ( 0X8F6700000C5D0000667E0000DE805B10F195D011B0A000AA00BDCB5C00000800, null, 0) WHERE diagram_id = @newid -- index:2081
    UPDATE sysdiagrams SET [definition] .Write ( 0X30000000000200000300000038002B00000009000000D9E6B0E91C81D011AD51, null, 0) WHERE diagram_id = @newid -- index:2113
    UPDATE sysdiagrams SET [definition] .Write ( 0X00A0C90F5739F43B7F847F61C74385352986E1D552F8A0327DB2D86295428D98, null, 0) WHERE diagram_id = @newid -- index:2145
    UPDATE sysdiagrams SET [definition] .Write ( 0X273C25A2DA2D00002C0043200000000000000000000053444DD2011FD1118E63, null, 0) WHERE diagram_id = @newid -- index:2177
    UPDATE sysdiagrams SET [definition] .Write ( 0X006097D2DF4834C9D2777977D811907000065B840D9C00002C00432000000000, null, 0) WHERE diagram_id = @newid -- index:2209
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000000051444DD2011FD1118E63006097D2DF4834C9D2777977D8119070, null, 0) WHERE diagram_id = @newid -- index:2241
    UPDATE sysdiagrams SET [definition] .Write ( 0X00065B840D9C100000007C0400000090010000006C00A5090000070000800300, null, 0) WHERE diagram_id = @newid -- index:2273
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000520000000180000043000080436F6E74726F6C0099280000564400005265, null, 0) WHERE diagram_id = @newid -- index:2305
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C6174696F6E736869702027464B5F4E75747331735F436F756E747269657327, null, 0) WHERE diagram_id = @newid -- index:2337
    UPDATE sysdiagrams SET [definition] .Write ( 0X206265747765656E2027436F756E74726965732720616E6420274E7574733173, null, 0) WHERE diagram_id = @newid -- index:2369
    UPDATE sysdiagrams SET [definition] .Write ( 0X270000002800B50100000700008004000000310000005900000002800000436F, null, 0) WHERE diagram_id = @newid -- index:2401
    UPDATE sysdiagrams SET [definition] .Write ( 0X6E74726F6C00DF2A00008D4A000000003000A509000007000080050000009E02, null, 0) WHERE diagram_id = @newid -- index:2433
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000080000006000080536368477269640066210000781E00004E7574733273, null, 0) WHERE diagram_id = @newid -- index:2465
    UPDATE sysdiagrams SET [definition] .Write ( 0X640000006800A5090000070000800600000052000000018000003D000080436F, null, 0) WHERE diagram_id = @newid -- index:2497
    UPDATE sysdiagrams SET [definition] .Write ( 0X6E74726F6C0099280000242B000052656C6174696F6E736869702027464B5F4E, null, 0) WHERE diagram_id = @newid -- index:2529
    UPDATE sysdiagrams SET [definition] .Write ( 0X75747332735F4E757473317327206265747765656E20274E7574733173272061, null, 0) WHERE diagram_id = @newid -- index:2561
    UPDATE sysdiagrams SET [definition] .Write ( 0X6E6420274E75747332732700000000002800B501000007000080070000003100, null, 0) WHERE diagram_id = @newid -- index:2593
    UPDATE sysdiagrams SET [definition] .Write ( 0X00005300000002800000436F6E74726F6C00DF2A0000C431000000003000A509, null, 0) WHERE diagram_id = @newid -- index:2625
    UPDATE sysdiagrams SET [definition] .Write ( 0X000007000080020000009E020000008000000600008053636847726964006621, null, 0) WHERE diagram_id = @newid -- index:2657
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000AA3700004E7574733173640000003400A50900000700008008000000A402, null, 0) WHERE diagram_id = @newid -- index:2689
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000080000009000080536368477269640066210000DC050000446973747269, null, 0) WHERE diagram_id = @newid -- index:2721
    UPDATE sysdiagrams SET [definition] .Write ( 0X63747300000000006C00A5090000070000800900000052000000018000004300, null, 0) WHERE diagram_id = @newid -- index:2753
    UPDATE sysdiagrams SET [definition] .Write ( 0X0080436F6E74726F6C00992800008812000052656C6174696F6E736869702027, null, 0) WHERE diagram_id = @newid -- index:2785
    UPDATE sysdiagrams SET [definition] .Write ( 0X464B5F4469737472696374735F4E757473327327206265747765656E20274E75, null, 0) WHERE diagram_id = @newid -- index:2817
    UPDATE sysdiagrams SET [definition] .Write ( 0X747332732720616E642027446973747269637473274000002800B50100000700, null, 0) WHERE diagram_id = @newid -- index:2849
    UPDATE sysdiagrams SET [definition] .Write ( 0X00800A000000310000005900000002800000436F6E74726F6C00DF2A0000DB18, null, 0) WHERE diagram_id = @newid -- index:2881
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000003800A5090000070000800B000000AE020000008000000E0000805363, null, 0) WHERE diagram_id = @newid -- index:2913
    UPDATE sysdiagrams SET [definition] .Write ( 0X684772696400DC0500009A2900004D756E69636970616C697469657300000000, null, 0) WHERE diagram_id = @newid -- index:2945
    UPDATE sysdiagrams SET [definition] .Write ( 0X3400A50900000700008001000000A40200000080000009000080536368477269, null, 0) WHERE diagram_id = @newid -- index:2977
    UPDATE sysdiagrams SET [definition] .Write ( 0X6400FC21000046500000436F756E747269657300000000007C00A50900000700, null, 0) WHERE diagram_id = @newid -- index:3009
    UPDATE sysdiagrams SET [definition] .Write ( 0X00800C000000620000000180000053000080436F6E74726F6CC091160000E30B, null, 0) WHERE diagram_id = @newid -- index:3041
    UPDATE sysdiagrams SET [definition] .Write ( 0X000052656C6174696F6E736869702027464B5F4D756E69636970616C69746965, null, 0) WHERE diagram_id = @newid -- index:3073
    UPDATE sysdiagrams SET [definition] .Write ( 0X735F44697374726963747327206265747765656E202744697374726963747327, null, 0) WHERE diagram_id = @newid -- index:3105
    UPDATE sysdiagrams SET [definition] .Write ( 0X20616E6420274D756E69636970616C6974696573270000002800B50100000700, null, 0) WHERE diagram_id = @newid -- index:3137
    UPDATE sysdiagrams SET [definition] .Write ( 0X00800D000000310000006900000002800000436F6E74726F6C00E6100000F522, null, 0) WHERE diagram_id = @newid -- index:3169
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000003400A5090000070000800E000000A8020000008000000B0000805363, null, 0) WHERE diagram_id = @newid -- index:3201
    UPDATE sysdiagrams SET [definition] .Write ( 0X684772696400DC050000CC420000536574746C656D656E74736900008000A509, null, 0) WHERE diagram_id = @newid -- index:3233
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000070000800F000000520000000180000057000080436F6E74726F6C000F0D, null, 0) WHERE diagram_id = @newid -- index:3265
    UPDATE sysdiagrams SET [definition] .Write ( 0X00004A36000052656C6174696F6E736869702027464B5F536574746C656D656E, null, 0) WHERE diagram_id = @newid -- index:3297
    UPDATE sysdiagrams SET [definition] .Write ( 0X74735F4D756E69636970616C697469657327206265747765656E20274D756E69, null, 0) WHERE diagram_id = @newid -- index:3329
    UPDATE sysdiagrams SET [definition] .Write ( 0X636970616C69746965732720616E642027536574746C656D656E747327000000, null, 0) WHERE diagram_id = @newid -- index:3361
    UPDATE sysdiagrams SET [definition] .Write ( 0X2800B50100000700008010000000310000006D00000002800000436F6E74726F, null, 0) WHERE diagram_id = @newid -- index:3393
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C00DBFDFFFF453E000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3425
    UPDATE sysdiagrams SET [definition] .Write ( 0X0100FEFF030A0000FFFFFFFF0000000000000000000000000000000017000000, null, 0) WHERE diagram_id = @newid -- index:3457
    UPDATE sysdiagrams SET [definition] .Write ( 0X4D6963726F736F66742044445320466F726D20322E300010000000456D626564, null, 0) WHERE diagram_id = @newid -- index:3489
    UPDATE sysdiagrams SET [definition] .Write ( 0X646564204F626A6563740000000000F439B27100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3521
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3553
    UPDATE sysdiagrams SET [definition] .Write ( 0X02000B00302A000046500000302A0000114700000000000002000000F0F0F000, null, 0) WHERE diagram_id = @newid -- index:3585
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000000000000000000000000000010000000400000000000000DF2A0000, null, 0) WHERE diagram_id = @newid -- index:3617
    UPDATE sysdiagrams SET [definition] .Write ( 0X8D4A00009A0B000058010000380000000100000200009A0B0000580100000200, null, 0) WHERE diagram_id = @newid -- index:3649
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000005000080080000800100000015000100000090014442010006546168, null, 0) WHERE diagram_id = @newid -- index:3681
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F6D61130046004B005F004E00750074007300310073005F0043006F0075006E, null, 0) WHERE diagram_id = @newid -- index:3713
    UPDATE sysdiagrams SET [definition] .Write ( 0X00740072006900650073002143341208000000E1110000670F00007856341207, null, 0) WHERE diagram_id = @newid -- index:3745
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000140100004E00750074007300320073000000570069006E0064006F0077, null, 0) WHERE diagram_id = @newid -- index:3777
    UPDATE sysdiagrams SET [definition] .Write ( 0X0073002E0046006F0072006D0073002C002000560065007200730069006F006E, null, 0) WHERE diagram_id = @newid -- index:3809
    UPDATE sysdiagrams SET [definition] .Write ( 0X003D0034002E0030002E0030002E0030002C002000430075006C007400750072, null, 0) WHERE diagram_id = @newid -- index:3841
    UPDATE sysdiagrams SET [definition] .Write ( 0X0065003D006E00650075007400720061006C002C0020005000750062006C0069, null, 0) WHERE diagram_id = @newid -- index:3873
    UPDATE sysdiagrams SET [definition] .Write ( 0X0063004B006500790054006F006B0065006E003D006200370037006100350063, null, 0) WHERE diagram_id = @newid -- index:3905
    UPDATE sysdiagrams SET [definition] .Write ( 0X0035003600310039003300340065003000380039000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3937
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:3969
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000001, null, 0) WHERE diagram_id = @newid -- index:4001
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000005000000540000002C0000002C0000002C000000340000000000000000, null, 0) WHERE diagram_id = @newid -- index:4033
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000A729000039160000000000002D010000070000000C000000070000001C, null, 0) WHERE diagram_id = @newid -- index:4065
    UPDATE sysdiagrams SET [definition] .Write ( 0X010000F708000053070000390300000B040000D0020000DD04000018060000A2, null, 0) WHERE diagram_id = @newid -- index:4097
    UPDATE sysdiagrams SET [definition] .Write ( 0X03000018060000BC070000460500000000000001000000E1110000670F000000, null, 0) WHERE diagram_id = @newid -- index:4129
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000040000000400000002000000020000001C010000DA0700000000000001, null, 0) WHERE diagram_id = @newid -- index:4161
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000F21300009408000000000000020000000200000002000000020000001C, null, 0) WHERE diagram_id = @newid -- index:4193
    UPDATE sysdiagrams SET [definition] .Write ( 0X010000F70800000100000000000000F213000008040000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4225
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000002000000020000001C010000F7080000000000000000000055320000DD, null, 0) WHERE diagram_id = @newid -- index:4257
    UPDATE sysdiagrams SET [definition] .Write ( 0X23000000000000000000000D00000004000000040000001C010000F70800009B, null, 0) WHERE diagram_id = @newid -- index:4289
    UPDATE sysdiagrams SET [definition] .Write ( 0X0A00008106000078563412040000005600000001000000010000000B00000000, null, 0) WHERE diagram_id = @newid -- index:4321
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000100000002000000030000000400000005000000060000000700000008, null, 0) WHERE diagram_id = @newid -- index:4353
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000090000000A00000004000000640062006F000000070000004E00750074, null, 0) WHERE diagram_id = @newid -- index:4385
    UPDATE sysdiagrams SET [definition] .Write ( 0X00730032007300000002000B00302A0000AA370000302A0000DF2D0000000000, null, 0) WHERE diagram_id = @newid -- index:4417
    UPDATE sysdiagrams SET [definition] .Write ( 0X0002000000F0F0F0000000000000000000000000000000000001000000070000, null, 0) WHERE diagram_id = @newid -- index:4449
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000DF2A0000C4310000230A0000580100003600000001000002000023, null, 0) WHERE diagram_id = @newid -- index:4481
    UPDATE sysdiagrams SET [definition] .Write ( 0X0A00005801000002000000000005000080080000800100000015000100000090, null, 0) WHERE diagram_id = @newid -- index:4513
    UPDATE sysdiagrams SET [definition] .Write ( 0X0144420100065461686F6D61100046004B005F004E0075007400730032007300, null, 0) WHERE diagram_id = @newid -- index:4545
    UPDATE sysdiagrams SET [definition] .Write ( 0X5F004E00750074007300310073002143341208000000E1110000670F00007856, null, 0) WHERE diagram_id = @newid -- index:4577
    UPDATE sysdiagrams SET [definition] .Write ( 0X341207000000140100004E007500740073003100730000004400720061007700, null, 0) WHERE diagram_id = @newid -- index:4609
    UPDATE sysdiagrams SET [definition] .Write ( 0X69006E0067002C002000560065007200730069006F006E003D0032002E003000, null, 0) WHERE diagram_id = @newid -- index:4641
    UPDATE sysdiagrams SET [definition] .Write ( 0X2E0030002E0030002C002000430075006C0074007500720065003D006E006500, null, 0) WHERE diagram_id = @newid -- index:4673
    UPDATE sysdiagrams SET [definition] .Write ( 0X75007400720061006C002C0020005000750062006C00690063004B0065007900, null, 0) WHERE diagram_id = @newid -- index:4705
    UPDATE sysdiagrams SET [definition] .Write ( 0X54006F006B0065006E003D006200300033006600350066003700660031003100, null, 0) WHERE diagram_id = @newid -- index:4737
    UPDATE sysdiagrams SET [definition] .Write ( 0X6400350030006100330061000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4769
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4801
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:4833
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000100000005000000540000002C0000002C0000002C000000340000000000, null, 0) WHERE diagram_id = @newid -- index:4865
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000000A729000039160000000000002D010000070000000C0000000700, null, 0) WHERE diagram_id = @newid -- index:4897
    UPDATE sysdiagrams SET [definition] .Write ( 0X00001C010000F708000053070000390300000B040000D0020000DD0400001806, null, 0) WHERE diagram_id = @newid -- index:4929
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000A203000018060000BC070000460500000000000001000000E1110000670F, null, 0) WHERE diagram_id = @newid -- index:4961
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000000040000000400000002000000020000001C010000DA0700000000, null, 0) WHERE diagram_id = @newid -- index:4993
    UPDATE sysdiagrams SET [definition] .Write ( 0X000001000000F213000094080000000000000200000002000000020000000200, null, 0) WHERE diagram_id = @newid -- index:5025
    UPDATE sysdiagrams SET [definition] .Write ( 0X00001C010000F70800000100000000000000F213000008040000000000000000, null, 0) WHERE diagram_id = @newid -- index:5057
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000000002000000020000001C010000F708000000000000000000005532, null, 0) WHERE diagram_id = @newid -- index:5089
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000DD23000000000000000000000D00000004000000040000001C010000F708, null, 0) WHERE diagram_id = @newid -- index:5121
    UPDATE sysdiagrams SET [definition] .Write ( 0X00009B0A00008106000078563412040000005600000001000000010000000B00, null, 0) WHERE diagram_id = @newid -- index:5153
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000100000002000000030000000400000005000000060000000700, null, 0) WHERE diagram_id = @newid -- index:5185
    UPDATE sysdiagrams SET [definition] .Write ( 0X000008000000090000000A00000004000000640062006F000000070000004E00, null, 0) WHERE diagram_id = @newid -- index:5217
    UPDATE sysdiagrams SET [definition] .Write ( 0X7500740073003100730000002143341208000000E1110000670F000078563412, null, 0) WHERE diagram_id = @newid -- index:5249
    UPDATE sysdiagrams SET [definition] .Write ( 0X0700000014010000440069007300740072006900630074007300000077006900, null, 0) WHERE diagram_id = @newid -- index:5281
    UPDATE sysdiagrams SET [definition] .Write ( 0X6E0067002C002000560065007200730069006F006E003D0032002E0030002E00, null, 0) WHERE diagram_id = @newid -- index:5313
    UPDATE sysdiagrams SET [definition] .Write ( 0X30002E0030002C002000430075006C0074007500720065003D006E0065007500, null, 0) WHERE diagram_id = @newid -- index:5345
    UPDATE sysdiagrams SET [definition] .Write ( 0X7400720061006C002C0020005000750062006C00690063004B00650079005400, null, 0) WHERE diagram_id = @newid -- index:5377
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F006B0065006E003D0062003000330066003500660037006600310031006400, null, 0) WHERE diagram_id = @newid -- index:5409
    UPDATE sysdiagrams SET [definition] .Write ( 0X3500300061003300610000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5441
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5473
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5505
    UPDATE sysdiagrams SET [definition] .Write ( 0X0100000005000000540000002C0000002C0000002C0000003400000000000000, null, 0) WHERE diagram_id = @newid -- index:5537
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000A729000039160000000000002D010000070000000C00000007000000, null, 0) WHERE diagram_id = @newid -- index:5569
    UPDATE sysdiagrams SET [definition] .Write ( 0X1C010000F708000053070000390300000B040000D0020000DD04000018060000, null, 0) WHERE diagram_id = @newid -- index:5601
    UPDATE sysdiagrams SET [definition] .Write ( 0XA203000018060000BC070000460500000000000001000000E1110000670F0000, null, 0) WHERE diagram_id = @newid -- index:5633
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000040000000400000002000000020000001C010000DA07000000000000, null, 0) WHERE diagram_id = @newid -- index:5665
    UPDATE sysdiagrams SET [definition] .Write ( 0X01000000F2130000940800000000000002000000020000000200000002000000, null, 0) WHERE diagram_id = @newid -- index:5697
    UPDATE sysdiagrams SET [definition] .Write ( 0X1C010000F70800000100000000000000F2130000080400000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5729
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000002000000020000001C010000F7080000000000000000000055320000, null, 0) WHERE diagram_id = @newid -- index:5761
    UPDATE sysdiagrams SET [definition] .Write ( 0XDD23000000000000000000000D00000004000000040000001C010000F7080000, null, 0) WHERE diagram_id = @newid -- index:5793
    UPDATE sysdiagrams SET [definition] .Write ( 0X9B0A00008106000078563412040000005C00000001000000010000000B000000, null, 0) WHERE diagram_id = @newid -- index:5825
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000001000000020000000300000004000000050000000600000007000000, null, 0) WHERE diagram_id = @newid -- index:5857
    UPDATE sysdiagrams SET [definition] .Write ( 0X08000000090000000A00000004000000640062006F0000000A00000044006900, null, 0) WHERE diagram_id = @newid -- index:5889
    UPDATE sysdiagrams SET [definition] .Write ( 0X7300740072006900630074007300000002000B00302A0000781E0000302A0000, null, 0) WHERE diagram_id = @newid -- index:5921
    UPDATE sysdiagrams SET [definition] .Write ( 0X431500000000000002000000F0F0F00000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:5953
    UPDATE sysdiagrams SET [definition] .Write ( 0X010000000A00000000000000DF2A0000DB180000B40A00005801000036000000, null, 0) WHERE diagram_id = @newid -- index:5985
    UPDATE sysdiagrams SET [definition] .Write ( 0X010000020000B40A000058010000020000000000050000800800008001000000, null, 0) WHERE diagram_id = @newid -- index:6017
    UPDATE sysdiagrams SET [definition] .Write ( 0X150001000000900144420100065461686F6D61130046004B005F004400690073, null, 0) WHERE diagram_id = @newid -- index:6049
    UPDATE sysdiagrams SET [definition] .Write ( 0X007400720069006300740073005F004E00750074007300320073002143341208, null, 0) WHERE diagram_id = @newid -- index:6081
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000E1110000670F00007856341207000000140100004D0075006E00690063, null, 0) WHERE diagram_id = @newid -- index:6113
    UPDATE sysdiagrams SET [definition] .Write ( 0X006900700061006C006900740069006500730000003D0032002E0030002E0030, null, 0) WHERE diagram_id = @newid -- index:6145
    UPDATE sysdiagrams SET [definition] .Write ( 0X002E0030002C002000430075006C0074007500720065003D006E006500750074, null, 0) WHERE diagram_id = @newid -- index:6177
    UPDATE sysdiagrams SET [definition] .Write ( 0X00720061006C002C0020005000750062006C00690063004B006500790054006F, null, 0) WHERE diagram_id = @newid -- index:6209
    UPDATE sysdiagrams SET [definition] .Write ( 0X006B0065006E003D006200370037006100350063003500360031003900330034, null, 0) WHERE diagram_id = @newid -- index:6241
    UPDATE sysdiagrams SET [definition] .Write ( 0X0065003000380039000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6273
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6305
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6337
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000100000005000000540000002C0000002C, null, 0) WHERE diagram_id = @newid -- index:6369
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000002C000000340000000000000000000000A729000039160000000000002D, null, 0) WHERE diagram_id = @newid -- index:6401
    UPDATE sysdiagrams SET [definition] .Write ( 0X010000070000000C000000070000001C010000F708000053070000390300000B, null, 0) WHERE diagram_id = @newid -- index:6433
    UPDATE sysdiagrams SET [definition] .Write ( 0X040000D0020000DD04000018060000A203000018060000BC0700004605000000, null, 0) WHERE diagram_id = @newid -- index:6465
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000001000000E1110000670F00000000000004000000040000000200000002, null, 0) WHERE diagram_id = @newid -- index:6497
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000001C010000DA0700000000000001000000F2130000940800000000000002, null, 0) WHERE diagram_id = @newid -- index:6529
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000200000002000000020000001C010000F70800000100000000000000F2, null, 0) WHERE diagram_id = @newid -- index:6561
    UPDATE sysdiagrams SET [definition] .Write ( 0X1300000804000000000000000000000000000002000000020000001C010000F7, null, 0) WHERE diagram_id = @newid -- index:6593
    UPDATE sysdiagrams SET [definition] .Write ( 0X080000000000000000000055320000DD23000000000000000000000D00000004, null, 0) WHERE diagram_id = @newid -- index:6625
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000040000001C010000F70800009B0A000081060000785634120400000066, null, 0) WHERE diagram_id = @newid -- index:6657
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000001000000010000000B0000000000000001000000020000000300000004, null, 0) WHERE diagram_id = @newid -- index:6689
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000005000000060000000700000008000000090000000A0000000400000064, null, 0) WHERE diagram_id = @newid -- index:6721
    UPDATE sysdiagrams SET [definition] .Write ( 0X0062006F0000000F0000004D0075006E00690063006900700061006C00690074, null, 0) WHERE diagram_id = @newid -- index:6753
    UPDATE sysdiagrams SET [definition] .Write ( 0X00690065007300000021433412080000001F100000EC0C000078563412070000, null, 0) WHERE diagram_id = @newid -- index:6785
    UPDATE sysdiagrams SET [definition] .Write ( 0X001401000043006F0075006E00740072006900650073000000770069006E0067, null, 0) WHERE diagram_id = @newid -- index:6817
    UPDATE sysdiagrams SET [definition] .Write ( 0X002C002000430075006C0074007500720065003D006E00650075007400720061, null, 0) WHERE diagram_id = @newid -- index:6849
    UPDATE sysdiagrams SET [definition] .Write ( 0X006C002C0020005000750062006C00690063004B006500790054006F006B0065, null, 0) WHERE diagram_id = @newid -- index:6881
    UPDATE sysdiagrams SET [definition] .Write ( 0X006E003D00620030003300660035006600370066003100310064003500300061, null, 0) WHERE diagram_id = @newid -- index:6913
    UPDATE sysdiagrams SET [definition] .Write ( 0X0033006100000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6945
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:6977
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7009
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000010000, null, 0) WHERE diagram_id = @newid -- index:7041
    UPDATE sysdiagrams SET [definition] .Write ( 0X0005000000540000002C0000002C0000002C0000003400000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7073
    UPDATE sysdiagrams SET [definition] .Write ( 0X00A729000039160000000000002D010000070000000C000000070000001C0100, null, 0) WHERE diagram_id = @newid -- index:7105
    UPDATE sysdiagrams SET [definition] .Write ( 0X00F708000053070000390300000B040000D0020000DD04000018060000A20300, null, 0) WHERE diagram_id = @newid -- index:7137
    UPDATE sysdiagrams SET [definition] .Write ( 0X0018060000BC0700004605000000000000010000001F100000EC0C0000000000, null, 0) WHERE diagram_id = @newid -- index:7169
    UPDATE sysdiagrams SET [definition] .Write ( 0X00030000000300000002000000020000001C010000DB06000000000000010000, null, 0) WHERE diagram_id = @newid -- index:7201
    UPDATE sysdiagrams SET [definition] .Write ( 0X00F21300004E06000000000000010000000100000002000000020000001C0100, null, 0) WHERE diagram_id = @newid -- index:7233
    UPDATE sysdiagrams SET [definition] .Write ( 0X00F70800000100000000000000F2130000080400000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7265
    UPDATE sysdiagrams SET [definition] .Write ( 0X0002000000020000001C010000F7080000000000000000000055320000DD2300, null, 0) WHERE diagram_id = @newid -- index:7297
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000D00000004000000040000001C010000F70800009B0A00, null, 0) WHERE diagram_id = @newid -- index:7329
    UPDATE sysdiagrams SET [definition] .Write ( 0X008106000078563412040000005C00000001000000010000000B000000000000, null, 0) WHERE diagram_id = @newid -- index:7361
    UPDATE sysdiagrams SET [definition] .Write ( 0X0001000000020000000300000004000000050000000600000007000000080000, null, 0) WHERE diagram_id = @newid -- index:7393
    UPDATE sysdiagrams SET [definition] .Write ( 0X00090000000A00000004000000640062006F0000000A00000043006F0075006E, null, 0) WHERE diagram_id = @newid -- index:7425
    UPDATE sysdiagrams SET [definition] .Write ( 0X0074007200690065007300000004000B00662100007A0D00008D1F00007A0D00, null, 0) WHERE diagram_id = @newid -- index:7457
    UPDATE sysdiagrams SET [definition] .Write ( 0X008D1F000038310000BD170000383100000000000002000000F0F0F000000000, null, 0) WHERE diagram_id = @newid -- index:7489
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000000000000000000000010000000D00000000000000E6100000F52200, null, 0) WHERE diagram_id = @newid -- index:7521
    UPDATE sysdiagrams SET [definition] .Write ( 0X00F80D00005801000038000000010000020000F80D0000580100000200000000, null, 0) WHERE diagram_id = @newid -- index:7553
    UPDATE sysdiagrams SET [definition] .Write ( 0X00FFFFFF000800008001000000150001000000900144420100065461686F6D61, null, 0) WHERE diagram_id = @newid -- index:7585
    UPDATE sysdiagrams SET [definition] .Write ( 0X1B0046004B005F004D0075006E00690063006900700061006C00690074006900, null, 0) WHERE diagram_id = @newid -- index:7617
    UPDATE sysdiagrams SET [definition] .Write ( 0X650073005F004400690073007400720069006300740073002143341208000000, null, 0) WHERE diagram_id = @newid -- index:7649
    UPDATE sysdiagrams SET [definition] .Write ( 0XE1110000670F000078563412070000001401000053006500740074006C006500, null, 0) WHERE diagram_id = @newid -- index:7681
    UPDATE sysdiagrams SET [definition] .Write ( 0X6D0065006E0074007300000069006F006E003D0032002E0030002E0030002E00, null, 0) WHERE diagram_id = @newid -- index:7713
    UPDATE sysdiagrams SET [definition] .Write ( 0X30002C002000430075006C0074007500720065003D006E006500750074007200, null, 0) WHERE diagram_id = @newid -- index:7745
    UPDATE sysdiagrams SET [definition] .Write ( 0X61006C002C0020005000750062006C00690063004B006500790054006F006B00, null, 0) WHERE diagram_id = @newid -- index:7777
    UPDATE sysdiagrams SET [definition] .Write ( 0X65006E003D006200370037006100350063003500360031003900330034006500, null, 0) WHERE diagram_id = @newid -- index:7809
    UPDATE sysdiagrams SET [definition] .Write ( 0X3000380039000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7841
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7873
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:7905
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000100000005000000540000002C0000002C000000, null, 0) WHERE diagram_id = @newid -- index:7937
    UPDATE sysdiagrams SET [definition] .Write ( 0X2C000000340000000000000000000000A729000039160000000000002D010000, null, 0) WHERE diagram_id = @newid -- index:7969
    UPDATE sysdiagrams SET [definition] .Write ( 0X070000000C000000070000001C010000F708000053070000390300000B040000, null, 0) WHERE diagram_id = @newid -- index:8001
    UPDATE sysdiagrams SET [definition] .Write ( 0XD0020000DD04000018060000A203000018060000BC0700004605000000000000, null, 0) WHERE diagram_id = @newid -- index:8033
    UPDATE sysdiagrams SET [definition] .Write ( 0X01000000E1110000670F00000000000004000000040000000200000002000000, null, 0) WHERE diagram_id = @newid -- index:8065
    UPDATE sysdiagrams SET [definition] .Write ( 0X1C010000DA0700000000000001000000F2130000940800000000000002000000, null, 0) WHERE diagram_id = @newid -- index:8097
    UPDATE sysdiagrams SET [definition] .Write ( 0X0200000002000000020000001C010000F70800000100000000000000F2130000, null, 0) WHERE diagram_id = @newid -- index:8129
    UPDATE sysdiagrams SET [definition] .Write ( 0X0804000000000000000000000000000002000000020000001C010000F7080000, null, 0) WHERE diagram_id = @newid -- index:8161
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000000000055320000DD23000000000000000000000D00000004000000, null, 0) WHERE diagram_id = @newid -- index:8193
    UPDATE sysdiagrams SET [definition] .Write ( 0X040000001C010000F70800009B0A000081060000785634120400000060000000, null, 0) WHERE diagram_id = @newid -- index:8225
    UPDATE sysdiagrams SET [definition] .Write ( 0X01000000010000000B0000000000000001000000020000000300000004000000, null, 0) WHERE diagram_id = @newid -- index:8257
    UPDATE sysdiagrams SET [definition] .Write ( 0X05000000060000000700000008000000090000000A0000000400000064006200, null, 0) WHERE diagram_id = @newid -- index:8289
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F0000000C00000053006500740074006C0065006D0065006E00740073000000, null, 0) WHERE diagram_id = @newid -- index:8321
    UPDATE sysdiagrams SET [definition] .Write ( 0X02000B00A60E000001390000A60E0000CC4200000000000002000000F0F0F000, null, 0) WHERE diagram_id = @newid -- index:8353
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000000000000000000000000000010000001000000000000000DBFDFFFF, null, 0) WHERE diagram_id = @newid -- index:8385
    UPDATE sysdiagrams SET [definition] .Write ( 0X453E00001C100000580100003E0000000100000200001C100000580100000200, null, 0) WHERE diagram_id = @newid -- index:8417
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000FFFFFF00080000800100000015000100000090014442010006546168, null, 0) WHERE diagram_id = @newid -- index:8449
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F6D611D0046004B005F0053006500740074006C0065006D0065006E00740073, null, 0) WHERE diagram_id = @newid -- index:8481
    UPDATE sysdiagrams SET [definition] .Write ( 0X005F004D0075006E00690063006900700061006C006900740069006500730000, null, 0) WHERE diagram_id = @newid -- index:8513
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8545
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8577
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8609
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8641
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8673
    UPDATE sysdiagrams SET [definition] .Write ( 0X0300440064007300530074007200650061006D00000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8705
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8737
    UPDATE sysdiagrams SET [definition] .Write ( 0X160002000300000006000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8769
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000000000000000000000000000000000018000000C50F000000000000, null, 0) WHERE diagram_id = @newid -- index:8801
    UPDATE sysdiagrams SET [definition] .Write ( 0X53006300680065006D0061002000550044005600200044006500660061007500, null, 0) WHERE diagram_id = @newid -- index:8833
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C00740000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8865
    UPDATE sysdiagrams SET [definition] .Write ( 0X26000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8897
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000580000001600000000000000, null, 0) WHERE diagram_id = @newid -- index:8929
    UPDATE sysdiagrams SET [definition] .Write ( 0X440053005200450046002D0053004300480045004D0041002D0043004F004E00, null, 0) WHERE diagram_id = @newid -- index:8961
    UPDATE sysdiagrams SET [definition] .Write ( 0X540045004E005400530000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:8993
    UPDATE sysdiagrams SET [definition] .Write ( 0X2C0002010500000007000000FFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9025
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000590000000C03000000000000, null, 0) WHERE diagram_id = @newid -- index:9057
    UPDATE sysdiagrams SET [definition] .Write ( 0X53006300680065006D0061002000550044005600200044006500660061007500, null, 0) WHERE diagram_id = @newid -- index:9089
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C007400200050006F0073007400200056003600000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9121
    UPDATE sysdiagrams SET [definition] .Write ( 0X36000200FFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9153
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000660000001200000000000000, null, 0) WHERE diagram_id = @newid -- index:9185
    UPDATE sysdiagrams SET [definition] .Write ( 0X0C00000000000000000000000100260000007300630068005F006C0061006200, null, 0) WHERE diagram_id = @newid -- index:9217
    UPDATE sysdiagrams SET [definition] .Write ( 0X65006C0073005F00760069007300690062006C0065000000010000000B000000, null, 0) WHERE diagram_id = @newid -- index:9249
    UPDATE sysdiagrams SET [definition] .Write ( 0X1E00000000000000000000000000000000000000640000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9281
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000010000000100000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:9313
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000000D002000006002800000041006300740069007600650054006100, null, 0) WHERE diagram_id = @newid -- index:9345
    UPDATE sysdiagrams SET [definition] .Write ( 0X62006C00650056006900650077004D006F006400650000000100000008000400, null, 0) WHERE diagram_id = @newid -- index:9377
    UPDATE sysdiagrams SET [definition] .Write ( 0X000031000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:9409
    UPDATE sysdiagrams SET [definition] .Write ( 0X640065003A00300000000100000008003A00000034002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:9441
    UPDATE sysdiagrams SET [definition] .Write ( 0X34002C0030002C0032003200390035002C0031002C0031003800370035002C00, null, 0) WHERE diagram_id = @newid -- index:9473
    UPDATE sysdiagrams SET [definition] .Write ( 0X35002C0031003200340035000000200000005400610062006C00650056006900, null, 0) WHERE diagram_id = @newid -- index:9505
    UPDATE sysdiagrams SET [definition] .Write ( 0X650077004D006F00640065003A00310000000100000008001E00000032002C00, null, 0) WHERE diagram_id = @newid -- index:9537
    UPDATE sysdiagrams SET [definition] .Write ( 0X30002C003200380034002C0030002C0031003700350035000000200000005400, null, 0) WHERE diagram_id = @newid -- index:9569
    UPDATE sysdiagrams SET [definition] .Write ( 0X610062006C00650056006900650077004D006F00640065003A00320000000100, null, 0) WHERE diagram_id = @newid -- index:9601
    UPDATE sysdiagrams SET [definition] .Write ( 0X000008001E00000032002C0030002C003200380034002C0030002C0032003200, null, 0) WHERE diagram_id = @newid -- index:9633
    UPDATE sysdiagrams SET [definition] .Write ( 0X390035000000200000005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:9665
    UPDATE sysdiagrams SET [definition] .Write ( 0X640065003A00330000000100000008001E00000032002C0030002C0032003800, null, 0) WHERE diagram_id = @newid -- index:9697
    UPDATE sysdiagrams SET [definition] .Write ( 0X34002C0030002C0032003200390035000000200000005400610062006C006500, null, 0) WHERE diagram_id = @newid -- index:9729
    UPDATE sysdiagrams SET [definition] .Write ( 0X56006900650077004D006F00640065003A00340000000100000008003E000000, null, 0) WHERE diagram_id = @newid -- index:9761
    UPDATE sysdiagrams SET [definition] .Write ( 0X34002C0030002C003200380034002C0030002C0032003200390035002C003100, null, 0) WHERE diagram_id = @newid -- index:9793
    UPDATE sysdiagrams SET [definition] .Write ( 0X32002C0032003700310035002C00310031002C00310036003600350000000200, null, 0) WHERE diagram_id = @newid -- index:9825
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000200000000000000000000000000000000000000D0020000060028000000, null, 0) WHERE diagram_id = @newid -- index:9857
    UPDATE sysdiagrams SET [definition] .Write ( 0X4100630074006900760065005400610062006C00650056006900650077004D00, null, 0) WHERE diagram_id = @newid -- index:9889
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F00640065000000010000000800040000003100000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:9921
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0030000000010000000800, null, 0) WHERE diagram_id = @newid -- index:9953
    UPDATE sysdiagrams SET [definition] .Write ( 0X3A00000034002C0030002C003200380034002C0030002C003200320039003500, null, 0) WHERE diagram_id = @newid -- index:9985
    UPDATE sysdiagrams SET [definition] .Write ( 0X2C0031002C0031003800370035002C0035002C00310032003400350000002000, null, 0) WHERE diagram_id = @newid -- index:10017
    UPDATE sysdiagrams SET [definition] .Write ( 0X00005400610062006C00650056006900650077004D006F00640065003A003100, null, 0) WHERE diagram_id = @newid -- index:10049
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000100000008001E00000032002C0030002C003200380034002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:10081
    UPDATE sysdiagrams SET [definition] .Write ( 0X32003000310030000000200000005400610062006C0065005600690065007700, null, 0) WHERE diagram_id = @newid -- index:10113
    UPDATE sysdiagrams SET [definition] .Write ( 0X4D006F00640065003A00320000000100000008001E00000032002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:10145
    UPDATE sysdiagrams SET [definition] .Write ( 0X3200380034002C0030002C003200320039003500000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:10177
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0033000000010000000800, null, 0) WHERE diagram_id = @newid -- index:10209
    UPDATE sysdiagrams SET [definition] .Write ( 0X1E00000032002C0030002C003200380034002C0030002C003200320039003500, null, 0) WHERE diagram_id = @newid -- index:10241
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000200000005400610062006C00650056006900650077004D006F0064006500, null, 0) WHERE diagram_id = @newid -- index:10273
    UPDATE sysdiagrams SET [definition] .Write ( 0X3A00340000000100000008003E00000034002C0030002C003200380034002C00, null, 0) WHERE diagram_id = @newid -- index:10305
    UPDATE sysdiagrams SET [definition] .Write ( 0X30002C0032003200390035002C00310032002C0032003700310035002C003100, null, 0) WHERE diagram_id = @newid -- index:10337
    UPDATE sysdiagrams SET [definition] .Write ( 0X31002C00310036003600350000000300000003000000000000003800000001A1, null, 0) WHERE diagram_id = @newid -- index:10369
    UPDATE sysdiagrams SET [definition] .Write ( 0XB31001000000640062006F00000046004B005F004E0075007400730031007300, null, 0) WHERE diagram_id = @newid -- index:10401
    UPDATE sysdiagrams SET [definition] .Write ( 0X5F0043006F0075006E007400720069006500730000000000000000000000C402, null, 0) WHERE diagram_id = @newid -- index:10433
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000400000004000000030000000800000001089418F008941800000000, null, 0) WHERE diagram_id = @newid -- index:10465
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000AD0F0000010000050000000500000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:10497
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000D00200000600280000004100630074006900760065005400610062006C, null, 0) WHERE diagram_id = @newid -- index:10529
    UPDATE sysdiagrams SET [definition] .Write ( 0X00650056006900650077004D006F006400650000000100000008000400000031, null, 0) WHERE diagram_id = @newid -- index:10561
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000200000005400610062006C00650056006900650077004D006F00640065, null, 0) WHERE diagram_id = @newid -- index:10593
    UPDATE sysdiagrams SET [definition] .Write ( 0X003A00300000000100000008003A00000034002C0030002C003200380034002C, null, 0) WHERE diagram_id = @newid -- index:10625
    UPDATE sysdiagrams SET [definition] .Write ( 0X0030002C0032003200390035002C0031002C0031003800370035002C0035002C, null, 0) WHERE diagram_id = @newid -- index:10657
    UPDATE sysdiagrams SET [definition] .Write ( 0X0031003200340035000000200000005400610062006C00650056006900650077, null, 0) WHERE diagram_id = @newid -- index:10689
    UPDATE sysdiagrams SET [definition] .Write ( 0X004D006F00640065003A00310000000100000008001E00000032002C0030002C, null, 0) WHERE diagram_id = @newid -- index:10721
    UPDATE sysdiagrams SET [definition] .Write ( 0X003200380034002C0030002C0032003000310030000000200000005400610062, null, 0) WHERE diagram_id = @newid -- index:10753
    UPDATE sysdiagrams SET [definition] .Write ( 0X006C00650056006900650077004D006F00640065003A00320000000100000008, null, 0) WHERE diagram_id = @newid -- index:10785
    UPDATE sysdiagrams SET [definition] .Write ( 0X001E00000032002C0030002C003200380034002C0030002C0032003200390035, null, 0) WHERE diagram_id = @newid -- index:10817
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000200000005400610062006C00650056006900650077004D006F00640065, null, 0) WHERE diagram_id = @newid -- index:10849
    UPDATE sysdiagrams SET [definition] .Write ( 0X003A00330000000100000008001E00000032002C0030002C003200380034002C, null, 0) WHERE diagram_id = @newid -- index:10881
    UPDATE sysdiagrams SET [definition] .Write ( 0X0030002C0032003200390035000000200000005400610062006C006500560069, null, 0) WHERE diagram_id = @newid -- index:10913
    UPDATE sysdiagrams SET [definition] .Write ( 0X00650077004D006F00640065003A00340000000100000008003E00000034002C, null, 0) WHERE diagram_id = @newid -- index:10945
    UPDATE sysdiagrams SET [definition] .Write ( 0X0030002C003200380034002C0030002C0032003200390035002C00310032002C, null, 0) WHERE diagram_id = @newid -- index:10977
    UPDATE sysdiagrams SET [definition] .Write ( 0X0032003700310035002C00310031002C00310036003600350000000600000006, null, 0) WHERE diagram_id = @newid -- index:11009
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000000000003200000001A1B31001000000640062006F00000046004B005F, null, 0) WHERE diagram_id = @newid -- index:11041
    UPDATE sysdiagrams SET [definition] .Write ( 0X004E00750074007300320073005F004E00750074007300310073000000000000, null, 0) WHERE diagram_id = @newid -- index:11073
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000C402000000000700000007000000060000000800000001A1B31038, null, 0) WHERE diagram_id = @newid -- index:11105
    UPDATE sysdiagrams SET [definition] .Write ( 0XA1B3100000000000000000AD0F00000100000800000008000000000000000000, null, 0) WHERE diagram_id = @newid -- index:11137
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000000000000000000D0020000060028000000410063007400690076006500, null, 0) WHERE diagram_id = @newid -- index:11169
    UPDATE sysdiagrams SET [definition] .Write ( 0X5400610062006C00650056006900650077004D006F0064006500000001000000, null, 0) WHERE diagram_id = @newid -- index:11201
    UPDATE sysdiagrams SET [definition] .Write ( 0X08000400000031000000200000005400610062006C0065005600690065007700, null, 0) WHERE diagram_id = @newid -- index:11233
    UPDATE sysdiagrams SET [definition] .Write ( 0X4D006F00640065003A00300000000100000008003A00000034002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:11265
    UPDATE sysdiagrams SET [definition] .Write ( 0X3200380034002C0030002C0032003200390035002C0031002C00310038003700, null, 0) WHERE diagram_id = @newid -- index:11297
    UPDATE sysdiagrams SET [definition] .Write ( 0X35002C0035002C0031003200340035000000200000005400610062006C006500, null, 0) WHERE diagram_id = @newid -- index:11329
    UPDATE sysdiagrams SET [definition] .Write ( 0X56006900650077004D006F00640065003A00310000000100000008001E000000, null, 0) WHERE diagram_id = @newid -- index:11361
    UPDATE sysdiagrams SET [definition] .Write ( 0X32002C0030002C003200380034002C0030002C00320030003100300000002000, null, 0) WHERE diagram_id = @newid -- index:11393
    UPDATE sysdiagrams SET [definition] .Write ( 0X00005400610062006C00650056006900650077004D006F00640065003A003200, null, 0) WHERE diagram_id = @newid -- index:11425
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000100000008001E00000032002C0030002C003200380034002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:11457
    UPDATE sysdiagrams SET [definition] .Write ( 0X32003200390035000000200000005400610062006C0065005600690065007700, null, 0) WHERE diagram_id = @newid -- index:11489
    UPDATE sysdiagrams SET [definition] .Write ( 0X4D006F00640065003A00330000000100000008001E00000032002C0030002C00, null, 0) WHERE diagram_id = @newid -- index:11521
    UPDATE sysdiagrams SET [definition] .Write ( 0X3200380034002C0030002C003200320039003500000020000000540061006200, null, 0) WHERE diagram_id = @newid -- index:11553
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C00650056006900650077004D006F00640065003A0034000000010000000800, null, 0) WHERE diagram_id = @newid -- index:11585
    UPDATE sysdiagrams SET [definition] .Write ( 0X3E00000034002C0030002C003200380034002C0030002C003200320039003500, null, 0) WHERE diagram_id = @newid -- index:11617
    UPDATE sysdiagrams SET [definition] .Write ( 0X2C00310032002C0032003700310035002C00310031002C003100360036003500, null, 0) WHERE diagram_id = @newid -- index:11649
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000900000009000000000000003800000001A1B31001000000640062006F00, null, 0) WHERE diagram_id = @newid -- index:11681
    UPDATE sysdiagrams SET [definition] .Write ( 0X000046004B005F004400690073007400720069006300740073005F004E007500, null, 0) WHERE diagram_id = @newid -- index:11713
    UPDATE sysdiagrams SET [definition] .Write ( 0X740073003200730000000000000000000000C402000000000A0000000A000000, null, 0) WHERE diagram_id = @newid -- index:11745
    UPDATE sysdiagrams SET [definition] .Write ( 0X090000000800000001129418301294180000000000000000AD0F00000100000B, null, 0) WHERE diagram_id = @newid -- index:11777
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000B00000000000000000000000000000000000000D00200000600280000, null, 0) WHERE diagram_id = @newid -- index:11809
    UPDATE sysdiagrams SET [definition] .Write ( 0X004100630074006900760065005400610062006C00650056006900650077004D, null, 0) WHERE diagram_id = @newid -- index:11841
    UPDATE sysdiagrams SET [definition] .Write ( 0X006F006400650000000100000008000400000031000000200000005400610062, null, 0) WHERE diagram_id = @newid -- index:11873
    UPDATE sysdiagrams SET [definition] .Write ( 0X006C00650056006900650077004D006F00640065003A00300000000100000008, null, 0) WHERE diagram_id = @newid -- index:11905
    UPDATE sysdiagrams SET [definition] .Write ( 0X003A00000034002C0030002C003200380034002C0030002C0032003200390035, null, 0) WHERE diagram_id = @newid -- index:11937
    UPDATE sysdiagrams SET [definition] .Write ( 0X002C0031002C0031003800370035002C0035002C003100320034003500000020, null, 0) WHERE diagram_id = @newid -- index:11969
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000005400610062006C00650056006900650077004D006F00640065003A0031, null, 0) WHERE diagram_id = @newid -- index:12001
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000100000008001E00000032002C0030002C003200380034002C0030002C, null, 0) WHERE diagram_id = @newid -- index:12033
    UPDATE sysdiagrams SET [definition] .Write ( 0X0032003000310030000000200000005400610062006C00650056006900650077, null, 0) WHERE diagram_id = @newid -- index:12065
    UPDATE sysdiagrams SET [definition] .Write ( 0X004D006F00640065003A00320000000100000008001E00000032002C0030002C, null, 0) WHERE diagram_id = @newid -- index:12097
    UPDATE sysdiagrams SET [definition] .Write ( 0X003200380034002C0030002C0032003200390035000000200000005400610062, null, 0) WHERE diagram_id = @newid -- index:12129
    UPDATE sysdiagrams SET [definition] .Write ( 0X006C00650056006900650077004D006F00640065003A00330000000100000008, null, 0) WHERE diagram_id = @newid -- index:12161
    UPDATE sysdiagrams SET [definition] .Write ( 0X001E00000032002C0030002C003200380034002C0030002C0032003200390035, null, 0) WHERE diagram_id = @newid -- index:12193
    UPDATE sysdiagrams SET [definition] .Write ( 0X000000200000005400610062006C00650056006900650077004D006F00640065, null, 0) WHERE diagram_id = @newid -- index:12225
    UPDATE sysdiagrams SET [definition] .Write ( 0X003A00340000000100000008003E00000034002C0030002C003200380034002C, null, 0) WHERE diagram_id = @newid -- index:12257
    UPDATE sysdiagrams SET [definition] .Write ( 0X0030002C0032003200390035002C00310032002C0032003700310035002C0031, null, 0) WHERE diagram_id = @newid -- index:12289
    UPDATE sysdiagrams SET [definition] .Write ( 0X0031002C00310036003600350000000C0000000C000000000000004800000001, null, 0) WHERE diagram_id = @newid -- index:12321
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000001000000640062006F00000046004B005F004D0075006E006900630069, null, 0) WHERE diagram_id = @newid -- index:12353
    UPDATE sysdiagrams SET [definition] .Write ( 0X00700061006C00690074006900650073005F0044006900730074007200690063, null, 0) WHERE diagram_id = @newid -- index:12385
    UPDATE sysdiagrams SET [definition] .Write ( 0X007400730000000000000000000000C402000000000D0000000D0000000C0000, null, 0) WHERE diagram_id = @newid -- index:12417
    UPDATE sysdiagrams SET [definition] .Write ( 0X00080000000118CF101818CF100000000000000000AD0F00000100000E000000, null, 0) WHERE diagram_id = @newid -- index:12449
    UPDATE sysdiagrams SET [definition] .Write ( 0X0E00000000000000000000000000000000000000D00200000600280000004100, null, 0) WHERE diagram_id = @newid -- index:12481
    UPDATE sysdiagrams SET [definition] .Write ( 0X630074006900760065005400610062006C00650056006900650077004D006F00, null, 0) WHERE diagram_id = @newid -- index:12513
    UPDATE sysdiagrams SET [definition] .Write ( 0X6400650000000100000008000400000031000000200000005400610062006C00, null, 0) WHERE diagram_id = @newid -- index:12545
    UPDATE sysdiagrams SET [definition] .Write ( 0X650056006900650077004D006F00640065003A00300000000100000008003A00, null, 0) WHERE diagram_id = @newid -- index:12577
    UPDATE sysdiagrams SET [definition] .Write ( 0X000034002C0030002C003200380034002C0030002C0032003200390035002C00, null, 0) WHERE diagram_id = @newid -- index:12609
    UPDATE sysdiagrams SET [definition] .Write ( 0X31002C0031003800370035002C0035002C003100320034003500000020000000, null, 0) WHERE diagram_id = @newid -- index:12641
    UPDATE sysdiagrams SET [definition] .Write ( 0X5400610062006C00650056006900650077004D006F00640065003A0031000000, null, 0) WHERE diagram_id = @newid -- index:12673
    UPDATE sysdiagrams SET [definition] .Write ( 0X0100000008001E00000032002C0030002C003200380034002C0030002C003200, null, 0) WHERE diagram_id = @newid -- index:12705
    UPDATE sysdiagrams SET [definition] .Write ( 0X3000310030000000200000005400610062006C00650056006900650077004D00, null, 0) WHERE diagram_id = @newid -- index:12737
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F00640065003A00320000000100000008001E00000032002C0030002C003200, null, 0) WHERE diagram_id = @newid -- index:12769
    UPDATE sysdiagrams SET [definition] .Write ( 0X380034002C0030002C0032003200390035000000200000005400610062006C00, null, 0) WHERE diagram_id = @newid -- index:12801
    UPDATE sysdiagrams SET [definition] .Write ( 0X650056006900650077004D006F00640065003A00330000000100000008001E00, null, 0) WHERE diagram_id = @newid -- index:12833
    UPDATE sysdiagrams SET [definition] .Write ( 0X000032002C0030002C003200380034002C0030002C0032003200390035000000, null, 0) WHERE diagram_id = @newid -- index:12865
    UPDATE sysdiagrams SET [definition] .Write ( 0X200000005400610062006C00650056006900650077004D006F00640065003A00, null, 0) WHERE diagram_id = @newid -- index:12897
    UPDATE sysdiagrams SET [definition] .Write ( 0X340000000100000008003E00000034002C0030002C003200380034002C003000, null, 0) WHERE diagram_id = @newid -- index:12929
    UPDATE sysdiagrams SET [definition] .Write ( 0X2C0032003200390035002C00310032002C0032003700310035002C0031003100, null, 0) WHERE diagram_id = @newid -- index:12961
    UPDATE sysdiagrams SET [definition] .Write ( 0X2C00310036003600350000000F0000000F000000000000004C000000014A790A, null, 0) WHERE diagram_id = @newid -- index:12993
    UPDATE sysdiagrams SET [definition] .Write ( 0X01000000640062006F00000046004B005F0053006500740074006C0065006D00, null, 0) WHERE diagram_id = @newid -- index:13025
    UPDATE sysdiagrams SET [definition] .Write ( 0X65006E00740073005F004D0075006E00690063006900700061006C0069007400, null, 0) WHERE diagram_id = @newid -- index:13057
    UPDATE sysdiagrams SET [definition] .Write ( 0X69006500730000000000000000000000C4020000000010000000100000000F00, null, 0) WHERE diagram_id = @newid -- index:13089
    UPDATE sysdiagrams SET [definition] .Write ( 0X00000800000001189418301894180000000000000000AD0F0000010000190000, null, 0) WHERE diagram_id = @newid -- index:13121
    UPDATE sysdiagrams SET [definition] .Write ( 0X000300000001000000020000001A0000001D0000000600000002000000050000, null, 0) WHERE diagram_id = @newid -- index:13153
    UPDATE sysdiagrams SET [definition] .Write ( 0X001C0000001D0000000900000005000000080000001C0000001D0000000C0000, null, 0) WHERE diagram_id = @newid -- index:13185
    UPDATE sysdiagrams SET [definition] .Write ( 0X00080000000B00000052000000530000000F0000000B0000000E0000001D0000, null, 0) WHERE diagram_id = @newid -- index:13217
    UPDATE sysdiagrams SET [definition] .Write ( 0X001C000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:13249
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:13281
    UPDATE sysdiagrams SET [definition] .Write ( 0X010003000000000000000C0000000B0000004E61BC0000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:13313
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:13345
    UPDATE sysdiagrams SET [definition] .Write ( 0XDBE6B0E91C81D011AD5100A0C90F57390000020050B1AD3ECCE2CF0102020000, null, 0) WHERE diagram_id = @newid -- index:13377
    UPDATE sysdiagrams SET [definition] .Write ( 0X1048450000000000000000000000000000000000680100004400610074006100, null, 0) WHERE diagram_id = @newid -- index:13409
    UPDATE sysdiagrams SET [definition] .Write ( 0X200053006F0075007200630065003D002E003B0049006E006900740069006100, null, 0) WHERE diagram_id = @newid -- index:13441
    UPDATE sysdiagrams SET [definition] .Write ( 0X6C00200043006100740061006C006F0067003D00450075006D00690073003B00, null, 0) WHERE diagram_id = @newid -- index:13473
    UPDATE sysdiagrams SET [definition] .Write ( 0X5000650072007300690073007400200053006500630075007200690074007900, null, 0) WHERE diagram_id = @newid -- index:13505
    UPDATE sysdiagrams SET [definition] .Write ( 0X200049006E0066006F003D0054007200750065003B0055007300650072002000, null, 0) WHERE diagram_id = @newid -- index:13537
    UPDATE sysdiagrams SET [definition] .Write ( 0X490044003D00730061003B004D0075006C007400690070006C00650041006300, null, 0) WHERE diagram_id = @newid -- index:13569
    UPDATE sysdiagrams SET [definition] .Write ( 0X740069007600650052006500730075006C00740053006500740073003D004600, null, 0) WHERE diagram_id = @newid -- index:13601
    UPDATE sysdiagrams SET [definition] .Write ( 0X61006C00730065003B005000610063006B00650074002000530069007A006500, null, 0) WHERE diagram_id = @newid -- index:13633
    UPDATE sysdiagrams SET [definition] .Write ( 0X3D0034003000390036003B004100700070006C00690063006100740069006F00, null, 0) WHERE diagram_id = @newid -- index:13665
    UPDATE sysdiagrams SET [definition] .Write ( 0X6E0020004E0061006D0065003D0022004D006900630072006F0073006F006600, null, 0) WHERE diagram_id = @newid -- index:13697
    UPDATE sysdiagrams SET [definition] .Write ( 0X74002000530051004C00200053006500720076006500720020004D0061006E00, null, 0) WHERE diagram_id = @newid -- index:13729
    UPDATE sysdiagrams SET [definition] .Write ( 0X6100670065006D0065006E0074002000530074007500640069006F0022000000, null, 0) WHERE diagram_id = @newid -- index:13761
    UPDATE sysdiagrams SET [definition] .Write ( 0X008005000A0000004E007500740073000000000226001400000043006F007500, null, 0) WHERE diagram_id = @newid -- index:13793
    UPDATE sysdiagrams SET [definition] .Write ( 0X6E0074007200690065007300000008000000640062006F000000000226000E00, null, 0) WHERE diagram_id = @newid -- index:13825
    UPDATE sysdiagrams SET [definition] .Write ( 0X00004E0075007400730031007300000008000000640062006F00000000022600, null, 0) WHERE diagram_id = @newid -- index:13857
    UPDATE sysdiagrams SET [definition] .Write ( 0X0E0000004E0075007400730032007300000008000000640062006F0000000002, null, 0) WHERE diagram_id = @newid -- index:13889
    UPDATE sysdiagrams SET [definition] .Write ( 0X2600140000004400690073007400720069006300740073000000080000006400, null, 0) WHERE diagram_id = @newid -- index:13921
    UPDATE sysdiagrams SET [definition] .Write ( 0X62006F000000000226001E0000004D0075006E00690063006900700061006C00, null, 0) WHERE diagram_id = @newid -- index:13953
    UPDATE sysdiagrams SET [definition] .Write ( 0X69007400690065007300000008000000640062006F0000000002240018000000, null, 0) WHERE diagram_id = @newid -- index:13985
    UPDATE sysdiagrams SET [definition] .Write ( 0X53006500740074006C0065006D0065006E007400730000000800000064006200, null, 0) WHERE diagram_id = @newid -- index:14017
    UPDATE sysdiagrams SET [definition] .Write ( 0X6F00000001000000D68509B3BB6BF2459AB8371664F0327008004E0000007B00, null, 0) WHERE diagram_id = @newid -- index:14049
    UPDATE sysdiagrams SET [definition] .Write ( 0X310036003300340043004400440037002D0030003800380038002D0034003200, null, 0) WHERE diagram_id = @newid -- index:14081
    UPDATE sysdiagrams SET [definition] .Write ( 0X450033002D0039004600410032002D0042003600440033003200350036003300, null, 0) WHERE diagram_id = @newid -- index:14113
    UPDATE sysdiagrams SET [definition] .Write ( 0X42003900310044007D0000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14145
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14177
    UPDATE sysdiagrams SET [definition] .Write ( 0X010003000000000000000C0000000B0000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14209
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14241
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14273
    UPDATE sysdiagrams SET [definition] .Write ( 0X0000000000000000000000000000000000000000000000000000000000000000, null, 0) WHERE diagram_id = @newid -- index:14305
    UPDATE sysdiagrams SET [definition] .Write ( 0X62885214, null, 0) WHERE diagram_id = @newid -- index:14337
 
END TRY
BEGIN CATCH
    -- If we got here, the [definition] updates didn't complete, so delete the diagram row
    -- (and hope it doesn't fail!)
    DELETE FROM sysdiagrams WHERE diagram_id = @newid
    PRINT 'XxXxX ' + Error_Message() + ' XxXxX'
    PRINT 'XxXxX END Tool_ScriptDiagram2008 - fix the error before running again XxXxX'
    RETURN
END CATCH
GO
